leet-code-study/leetCode

hyeontaek/TwoSum.java
Given an array of integers `nums` and an integer `target`, return indices of the two numbers such
that they add up to `target`.
You may assume that each input would have exactly one solution, and you may not use the same element
twice.
You can return the answer in any order.
---
Example 1:
> Input: nums = [2,7,11,15], target = 9 \
> Output: [0,1] \
> Explanation: Because nums[0] + nums[1] == 9, \
> we return [0, 1].
```
public static int[] twoSum(int[] nums, int target) {
for (int j = i + 1; j < nums.length; j++) {
if (nums[i] + nums[j] == target) {
return new int[]{i, j};
}
}
}
return new int[] {};
}
```
for문을 두번 반복해서 nums중 i번째 와 j번째 숫자의 합이 타겟숫자가 되면
i와 j의 인덱스 번호가 int[] 배열을 반환하는 함수이다.
```
public int[] twoSum(int[] nums, int target) {
Map<Integer, …
```
=> [1] Two Sum

hyeontaek/IsPalindrome.java, hyeontaek/TwoSum.java
Given an integer `x`, return `true` if `x` is a
`palindrome`, and `false` otherwise.
> An integer is a palindrome when it reads the same forward and backward. \
> For example, 121 is a palindrome while 123 is not.
```
public boolean isPalindrome(int x) {
if (x < 0) {
return false;
}
int y = 0;
int z = x;
while (z != 0) {
y = y * 10 + z % 10;
z = z / 10;
}
return y == x;
}
```
처음 `if (x < 0) `은 x가 0보다 작을때 `false`를 반환하는 if문이다.  
다음 `y`는 거꾸로 뒤집었을때 담을 객체로 만들었다. 
`z`는 `x`를 임시로 담을 객체이다. 
`while (z != 0)`은 `z`가 `0`이 아닐때 반복하는 `while`문이고 \
`{ y = y * 10 + z % 10; z = z / 10; }`은 y를 z의 거꾸로 대입하는 식이다. \
`return y == x;` 이제 그 결과 `x`와 `y`가 같은면 `true`, 다르면 `false`를 반환하는 함수이다.
```
public boolean isPalindrome2(int x) {
if (x < 0 || (x != 0 && x % 10 == 0)) {
return false;
}
String s = String.valueOf(x); …
```
=> [2] Is Palindrome

dlek-user/Palindrome_Number, dlek-user/TwoSum.java
dlek-user-1
Given an array of integers `nums` and an integer `target`, return indices of the two numbers such that they add up to `target`.
You may assume that each input would have exactly one solution, and you may not use the same element twice.
You can return the answer in any order.
---------------------------------------
Input: nums = [2,7,11,15], target = 9
Output: [0,1]
Explanation: Because nums[0] + nums[1] == 9, we return [0, 1].
Input: nums = [3,2,4], target = 6
Output: [1,2]
Input: nums = [3,3], target = 6
Output: [0,1]
HashMap<Integer, Integer> map = new HashMap<>();
해시맵을 사용하여 값과 해당 값의 인덱스를 저장했습니다.
int complement = target - nums[i];
complement를 계산하는 식입니다.
if (map.containsKey(complement)) {
return new int[] { map.get(complement), i };
}
complement가 해시맵에 존재하는지 확인하고 존재한다면 현재 인덱스와 …
=> [1] TwoSum.java

hyeontaek/RomanToInt.java
Roman numerals are represented by seven different symbols: I, V, X, L, C, D and M.
| Symbol | Value |
|:------:|:-----:|
I    |   1   
V    |   5   
X    |  10   
L    |  50   
C    |  100  
D    |  500  
M    | 1000  
For example, `2` is written as `II` in Roman numeral, just two ones added together. 12 is written as
`XII`, which is simply `X + II`. The number `27` is written as `XXVII`, which is `XX + V + II`.
Roman numerals are usually written largest to smallest from left to right. However, the numeral for
four is not `IIII`. Instead, the number four is written as `IV`. Because the one is before the five
we
subtract it making four. The same principle applies to the number nine, which is written as IX.
There are six instances where subtraction is used:
- `I` can be placed before `V` …
=> [13] Roman To Int

hyeontaek/LongestCommonPrefix.java
Write a function to find the longest common prefix string amongst an array of strings.
If there is no common prefix, return an empty string `""`.
> Input: `strs = ["flower","flow","flight"]` \
> Output: `"fl"`
---
```
public String longestCommonPrefix(String[] strs) {
if (strs.length == 0) return "";
String prefix = strs[0];
for (int i = 1; i < strs.length; i++)
while (strs[i].indexOf(prefix) != 0) {
prefix = prefix.substring(0, prefix.length() - 1);
if (prefix.isEmpty()) return "";
}
return prefix;
}
```
`if (strs.length == 0) return "";`
입력으로 주어진 문자열 배열 `strs`가 비어있는 경우, 즉 길이가 0인 경우, 공통 접두사가 존재할 수 없으므로 빈 문자열 `""`을 반환합니다.
`String prefix = strs[0];` 
첫 번째 문자열을 초기 공통 접두사로 가정하고, 이는 비교의 기준이 되며, 이후 반복문을 통해 접두사를 줄여나가는 방식입니다.
`for (int i = 1; i < strs.length; i++)`
두 번째 문자열부터 시작하여 배열의 모든 문자열을 …
=> [14] Longest Common Prefix

redandsilver/easy/LongestCommonPrefix.java
문자열 배열이 주어진다.
각 문자열에서 공통적인 prefix 중 가장 긴 prefix를 찾는다. 
문자열을 오름차순(알파벳순)으로 정렬한다.
첫번째 문자열과 마지막 문자열을 한개씩 비교한다.
같다면 answer에 해당 문자를 추가하고 다르다면 answer를 리턴한다.
~~~ java
Arrays.sort(strs);
String f = strs[0];
String l = strs[strs.length-1];
StringBuilder answer = new StringBuilder();
int n = Math.min(f.length(),l.length());
for(int i=0; i<n; i++){
if(f.charAt(i) != l.charAt(i)){
return answer.toString();
}
answer.append(f.charAt(i));
}
return answer.toString();
~~~
=> redandsilver-3

hyeontaek/ValidParentheses.java
Given a string s containing just the characters `'('`, `')'`, `'{'`, `'}'`, `'['` and `']'`,
determine if the input string is valid.
An input string is valid if:
1. Open brackets must be closed by the same type of brackets.
2. Open brackets must be closed in the correct order.
3. Every close bracket has a corresponding open bracket of the same type.
> Input: s = `"()"` \
> Output: true
```
public boolean isValid(String s) {
Stack<Character> stack = new Stack<>();
if (c == '(') {
stack.push(')');
} else if (c == '[') {
stack.push(']');
} else if (c == '{') {
stack.push('}');
} else if (stack.isEmpty() || stack.pop() != c) {
return false;
}
}
return stack.isEmpty();
}
```
`Stack<Character> stack = new Stack<>();`
문자를 저장하기 위한 Stack 객체를 생성합니다. 이 스택은 열린 괄호를 …
=> [23] Valid Parentheses

dlek-user/Valid_Parentheses
Given a string `s` containing just the characters `'('`, `')'`, `'{'`, `'}'`, `'['` and `']'`, determine if the input string is valid.
An input string is valid if:
1. Open brackets must be closed by the same type of brackets.
2. Open brackets must be closed in the correct order.
3. Every close bracket has a corresponding open bracket of the same type.
> Input: s = "()"
> Output: true
> Input: s = "()[]{}"
> Output: true
> Input: s = "(]"
```
public boolean isValid(String s) {
Stack<Character> stack = new Stack<>();
if (c == '(' || c == '{' || c == '[') {
stack.push(c); // 여는 괄호를 스택에 푸시합니다.
} else {
if (stack.isEmpty()) {
return false; // 스택이 비어있으면 대응하는 여는 괄호가 없습니다.
}
char top = stack.pop(); // 스택의 맨 위 문자를 팝합니다.
// 현재 닫는 괄호가 …
```
=> [20] Valid_Parentheses

hyeontaek/MergeTwoSortedLists.java
You are given the heads of two sorted linked lists list1 and list2.
Merge the two lists into one sorted list. The list should be made by splicing together the nodes of
the first two lists.
Return the head of the merged linked list.
> Input: list1 = [1,2,4], list2 = [1,3,4] \
> Output: [1,1,2,3,4,4]
```
public ListNode mergeTwoLists(ListNode list1, ListNode list2) {
if (list1 == null && list2 == null) {
return null;
}
if (list1 == null) {
return list2;
}
if (list2 == null) {
return list1;
}
if (list1.val < list2.val) {
list1.next = mergeTwoLists(list1.next, list2);
return list1;
}
list2.next = mergeTwoLists(list1, list2.next);
return list2;
}
```
```
if (list1 == null && list2 == null) {
return null;
}
if (list1 == null) {
return list2;
}
if (list2 == null) {
return list1;
}
```
먼저, 두 입력 …
=> [21] Merge Two Sorted Lists

dlek-user/Merge_Two_Sorted_Lists
You are given the heads of two sorted linked lists `list1` and `list2`.
Merge the two lists into one sorted list. The list should be made by splicing together the nodes of the first two lists.
Return the head of the merged linked list.
> Input: list1 = [1,2,4], list2 = [1,3,4]
> Output: [1,1,2,3,4,4]
> 
> Input: list1 = [], list2 = []
> Output: []
> 
> Input: list1 = [], list2 = [0]
> Output: [0]
```
public ListNode mergeTwoLists(ListNode list1, ListNode list2) {
while (list1 != null && list2 != null) {
if (list1.val <= list2.val) {
list1.next = mergeTwoLists(list1.next, list2);
return list1;
} else {
list2.next = mergeTwoLists(list2.next, list1);
return list2;
}
}
return list1 == null ? list2 : list1;
}
}
```
```
while (list1 != null && list2 != null) {
```
while 루프는 두 …
=> [6] Merge_Two_Sorted_Lists

hyeontaek/RemoveDuplicatesfromSortedArray.java
Given an integer array `nums` sorted in non-decreasing order, remove the
duplicates [in-place](https://en.wikipedia.org/wiki/In-place_algorithm) such that
each unique element appears only once. The relative order of the elements should be kept the same.
Then return the number of unique elements in `nums`.
Consider the number of unique elements of `nums` to be `k`, to get accepted, you need to do the
following things:
Change the array `nums` such that the first `k` elements of `nums` contain the unique elements in
the
order they were present in `nums` initially. The remaining elements of `nums` are not important as
well
as the size of nums. \
Return `k`.
The judge will test your solution with the following code:
```
`int[] nums = [...]; // Input array \
int[] expectedNums = [...]; // The …
```
=> [26] Remove Duplicates From Sorted Array

hyeontaek/RemoveElement.java
Given an integer array `nums` and an integer `val`, remove all occurrences of `val`
in `nums` [in-place](https://en.wikipedia.org/wiki/In-place_algorithm). The order of the elements
may be changed. Then return the number of elements in nums which are not equal to `val`.
Consider the number of elements in `nums` which are not equal to `val` be `k`, to get accepted, you
need to do the following things:
- Change the array `nums` such that the first `k` elements of `nums` contain the elements which are
not equal to `val`. The remaining elements of `nums` are not important as well as the size
of `nums`.
- Return `k`.
The judge will test your solution with the following code:
```
int[] nums = [...]; // Input array
int val = ...; // Value to remove
int[] expectedNums = [...]; // The expected …
```
=> [27] Remove Element

hyeontaek/FindTheIndexOfTheFirstOccurrenceInAString.java
Given two strings `needle` and `haystack`, return the index of the first occurrence of `needle`
in `haystack`, or `-1` if `needle` is not part of `haystack`.
> Input: haystack = "sadbutsad", needle = "sad" \
> Output: 0 \
> Explanation: "sad" occurs at index 0 and 6. \
> The first occurrence is at index 0, so we return 0.
```
public int strStr(String haystack, String needle) {
return haystack.indexOf(needle);
}
```
`haystack.indexOf(needle)` 반환하고, 존재하지 않으면 `-1`를 반환한다.
여기서 `haystack.indexOf(needle)`는 needle 문자열이 haystack 문자열 내에서 처음으로 나타나는 위치의 인덱스를 반환합니다.
만약 needle 문자열이 haystack 내에 없으면 -1을 반환합니다.
=> [28] FindTheIndexOfTheFirstOccurrenceInAString

hyeontaek/SearchInsertPosition.java
Given a sorted array of distinct integers and a target value, return the index if the target is
found. If not, return the index where it would be if it were inserted in order.
You must write an algorithm with `O(log n)` runtime complexity.
```
public int searchInsert(int[] nums, int target) {
int index = 0;
if (num >= target) {
return index;
}
index++;
}
return index;
}
```
`int index = 0;`
`index` 변수를 `0`으로 초기화하여, 탐색을 시작할 위치를 설정합니다.
`for (int num : nums)`
`nums` 배열의 각 요소 `num`에 대해, `for-each` 루프를 사용하여 배열을 순차적으로 탐색합니다.
`if (num >= target) {
return index;
}`
만약 현재 요소 `num`이 `target` 값보다 크거나 같다면, `target` 값은 현재 위치 `index`에 삽입되어야 합니다. 이 경우, 현재 `index` 값을
반환합니다.
`index++;`
`num < target`인 경우, `index`를 `1` 증가시켜 다음 위치로 이동합니다.
모든 배열 요소를 탐색한 후에도 target 값이 삽입될 적절한 위치를 찾지 …
=> [35] Search Insert Position

hyeontaek/LengthOfLastWord.java
Given a string s consisting of words and spaces, return the length of the last word in the string.
A word is a maximal substring consisting of non-space characters only.
> ### Substring
> A substring is a contiguous non-empty sequence of characters within a string.
> Input: s = "Hello World" \
Output: 5 \
Explanation: The last word is "World" with length 5.
```
public int lengthOfLastWord(String s) {
String[] sSplit = s.trim().split(" ");
return sSplit[sSplit.length - 1].length();
}
```
`String[] sSplit = s.trim().split(" ");`
이 코드는 `trim()` 메소드를 사용하여 문자열 s의 앞뒤 공백을 제거한 후, 공백을 기준으로 문자열을 분할하여 배열 `sSplit`에 저장합니다.
`
return sSplit[sSplit.length - 1].length();`
배열 `sSplit`의 마지막 요소(즉, 마지막 단어)의 길이를 반환합니다.
```
public int lengthOfLastWord2(String s) {
return s.trim().length() - …
```
=> [58] Length Of Last Word

dlek-user/[58]LengthOfLastWord
Given a string `s` consisting of words and spaces, return the length of the last word in the string.
A word is a maximal substring consisting of non-space characters only.
> Input: s = "Hello World"
> Output: 5
> Explanation: The last word is "World" with length 5.
> Input: s = "   fly me   to   the moon  "
> Output: 4
> Explanation: The last word is "moon" with length 4.
> Input: s = "luffy is still joyboy"
> Output: 6
> Explanation: The last word is "joyboy" with length 6.
```
public int lengthOfLastWord(String s) {
s = s.trim();
String[] words = s.split("\\s+");
if (words.length == 0) {
return 0;
}
return words[words.length - 1].length();
}
}
/*
public int lengthOfLastWord(String s) {
return Arrays.asList(s.split(" ")).stream().reduce("", (m,n) -> …
```
=> [58]LengthOfLastWord

hyeontaek/PlusOne.java
You are given a large integer represented as an integer array `digits`, where each `digits[i]` is
the `i` digit of the integer. The digits are ordered from most significant to least significant in
left-to-right order. The large integer does not contain any leading `0`'s.
Increment the large integer by one and return the resulting array of digits.
> Input: digits = [1,2,3] \
> Output: [1,2,4] \
> Explanation: The array represents the integer 123. \
> Incrementing by one gives 123 + 1 = 124. \
> Thus, the result should be [1,2,4]. \
>
> Input: digits = [9] \
> Output: [1,0] \
> Explanation: The array represents the integer 9. \
> Incrementing by one gives 9 + 1 = 10. \
> Thus, the result should be [1,0].
```
public int[] plusOne(int[] digits) {
for (int i = digits.length - 1; i >= 0; i--) { …
```
=>  [66] Plus One

dlek-user/[66] PlusOne
You are given a large integer represented as an integer array `digits`, where each `digits[i]` is the `ith` digit of the integer. The digits are ordered from most significant to least significant in left-to-right order. The large integer does not contain any leading `0`'s.
Increment the large integer by one and return _the resulting array of digits_.
> Input: digits = [1,2,3]
> Output: [1,2,4]
> Explanation: The array represents the integer 123.
> Incrementing by one gives 123 + 1 = 124.
> Thus, the result should be [1,2,4].
> 
> Input: digits = [4,3,2,1]
> Output: [4,3,2,2]
> Explanation: The array represents the integer 4321.
> Incrementing by one gives 4321 + 1 = 4322.
> Thus, the result should be [4,3,2,2].
> Input: digits = [9]
> Output: [1,0]
> Explanation: The array represents the …
=> [66] PlusOne

hyeontaek/AddBinary.java
Given two binary strings `a` and `b`, return their sum as a binary string.
> Input: a = "11", b = "1" \
> Output: "100"
```
public String addBinary2(String a, String b) {
StringBuilder sb = new StringBuilder();
int aLen = a.length() - 1, bLen = b.length() - 1, carry = 0;
while (aLen >= 0 || bLen >= 0 || carry != 0) {
if (aLen >= 0) {
carry += a.charAt(aLen) - '0';
aLen--;
}
if (bLen >= 0) {
carry += b.charAt(bLen) - '0';
bLen--;
}
sb.append(carry % 2);
carry /= 2;
}
return sb.reverse().toString();
}
```
`aLen`과 `bLen `변수는 각각 `a`와 `b` 문자열의 마지막 인덱스를 저장합니다.
이를 통해 문자열의 끝에서부터 시작하여 앞으로 이동하면서 각 자리의 덧셈을 수행합니다.
`carry` 변수는 이진수 덧셈에서의 올림수를 저장합니다. 초기값은 0입니다.
`while` 반복문은 `aLen` 또는 `bLen` 인덱스가 `0` 이상이거나, `carry` 값이 `0`이 아닌 동안 계속 실행됩니다. 
즉, 두 이진수의 모든 자리를 처리하고, 마지막으로 올림수가 남아있지 않을 때까지 반복합니다.
반복문 내부에서, …
=> [67] Add Binary

dlek-user/[67]Add_Binary
Given two binary strings `a` and `b`, return their sum as a binary string.
> 
> Input: a = "11", b = "1"
> Output: "100"
> 
> Input: a = "1010", b = "1011"
> Output: "10101"
```
public String addBinary(String a, String b) {
StringBuilder sb = new StringBuilder();
int i = a.length() - 1, j = b.length() - 1, carry = 0;
while (i >= 0 || j >= 0 || carry > 0) {
int sum = carry;
if (i >= 0) {
sum += a.charAt(i--) - '0';
}
if (j >= 0) {
sum += b.charAt(j--) - '0';
}
sb.append(sum % 2);
carry = sum / 2;
}
return sb.reverse().toString();
}
}
```
```
int i = a.length() - 1, j = b.length() - 1, carry = 0;
```
포인터 i와 j를 각각 문자열 a와 b의 마지막 문자를 가리키도록 초기화합니다.
덧셈에서 발생한 carry를 추적하기 위해 carry 변수를 초기화
```
while (i >= 0 || j >= 0 || carry > 0) {
int sum = carry;
if (i >= 0) {
sum += …
```
=> [67]Add_Binary

hyeontaek/ClimbingStairs.java
You are climbing a staircase. It takes n steps to reach the top.
Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?
> Input: n = 2 \
Output: 2 \
Explanation: There are two ways to climb to the top.
> 1. 1 step + 1 step
> 2. 2 steps
```
public int climbStairs(int n) {
dp[0] = 1;
dp[1] = 1;
for (int i = 2; i <= n; i++) {
dp[i] = dp[i - 1] + dp[i - 2];
}
return dp[n];
}
```
`int[] dp = new int[n + 1];`
n 개의 계단을 오르는 방법의 수를 저장할 배열 dp를 선언하고, 크기를 n + 1로 설정합니다. 배열의 각 원소는 해당 계단까지 도달하는 방법의 수를 나타냅니다.
`dp[0] = 1;`
계단이 0개일 때(시작 지점에서 시작 지점까지의 방법), 방법의 수는 1가지입니다.
`dp[1] = 1;` 
계단이 1개일 때, 방법의 수는 1가지입니다.
동적 계획법을 이용한 계산
`for (int i = 2; i <= n; i++)`
2개의 계단부터 n 개의 계단까지 각각에 대해 방법의 수를 계산합니다.
`dp[i] = dp[i - 1] + dp[i - 2];`
i 번째 계단에 …
=> [70] Climbing Stairs

dlek-user/[69]Sqrt(x)
Given a non-negative integer `x`, return the square root of `x` rounded down to the nearest integer. The returned integer should be non-negative as well.
You must not use any built-in exponent function or operator.
> Input: x = 4
> Output: 2
> Explanation: The square root of 4 is 2, so we return 2.
> Input: x = 8
> Output: 2
> Explanation: The square root of 8 is 2.82842..., and since we round it down to the nearest integer, 2 is returned.
```
public int mySqrt(int x) {
if (x <= 1) return x;
int left = 1, right = x;
int mid = left + (right - left) / 2;
long square = (long) mid * mid;
if (square <= x) {
left = mid + 1;
} else {
right = mid - 1;
}
}
return left - 1;
}
}
```
```
if (x <= 1) return x;
```
주어진 숫자 x가 0 이하이거나 1인 경우에는 x를 반환합니다. 
```
int …
```
=> [69] Sqrt(x)

dlek-user/[70]Climbing_Staris
You are climbing a staircase. It takes `n` steps to reach the top.
Each time you can either climb `1` or `2` steps. In how many distinct ways can you climb to the top?
> Input: n = 2
> Output: 2
> Explanation: There are two ways to climb to the top.
> 1. 1 step + 1 step
> 2. 2 steps
> Input: n = 3
> Output: 3
> Explanation: There are three ways to climb to the top.
> 1. 1 step + 1 step + 1 step
> 2. 1 step + 2 steps
> 3. 2 steps + 1 step
```
public int climbStairs(int n) {
if (n <= 1) return 1;
dp[0] = 1;
dp[1] = 1;
for (int i = 2; i <= n; i++) {
dp[i] = dp[i - 1] + dp[i - 2];
}
return dp[n];
}
}
```
0단계에서는 0단계로 가는 방법이 1가지, 1단계에서는 1단계로 가는 방법이 1가지입니다.
```
for (int i = 2; i <= n; i++) {
dp[i] = dp[i - 1] + dp[i - 2];
}
```
2단계부터 n단계까지의 방법을 구하기 위해 …
=> [70]ClimbingStaris

hyeontaek/MergeSortedArray.java
You are given two integer arrays nums1 and nums2, sorted in non-decreasing order, and two integers m
and n, representing the number of elements in nums1 and nums2 respectively.
Merge nums1 and nums2 into a single array sorted in non-decreasing order.
The final sorted array should not be returned by the function, but instead be stored inside the
array nums1. To accommodate this, nums1 has a length of m + n, where the first m elements denote the
elements that should be merged, and the last n elements are set to 0 and should be ignored. nums2
has a length of n.
```
public void merge(int[] nums1, int m, int[] nums2, int n) {
int index = m + n - 1;
m--;
n--;
while (m >= 0 && n >= 0) {
if (nums1[m] > nums2[n]) {
nums1[index--] = nums1[m--];
} else {
nums1[index--] = nums2[n--];
}
}
while (n >= …
```
=> [88] Merge Sorted Array

dlek-user/[83] Remove_Duplicates_from_Sorted_List
Given the `head` of a sorted linked list, delete all duplicates such that each element appears only once. Return the linked list sorted as well.
> Input: head = [1,1,2]
> Output: [1,2]
> Input: head = [1,1,2,3,3]
> Output: [1,2,3]
```
public ListNode deleteDuplicates(ListNode head) {
if (head == null || head.next == null) {
return head;
}
ListNode current = head;
while (current != null && current.next != null) {
if (current.val == current.next.val) {
current.next = current.next.next;
} else {
}
}
return head;
}
}
```
```
if (head == null || head.next == null) {
return head;
}
```
연결 리스트가 비어 있거나 노드가 하나만 있는 경우, 중복된 노드가 없으므로 그대로 반환합니다.
```
while (current != null && current.next != null) {
```
반복문을 사용하여 연결 리스트를 순회합니다. 리스트의 끝에 도달하거나 current 포인터가 마지막 노드에 …
=> [83] Remove Duplicates from Sorted List

hyeontaek/BinaryTreeInorderTraversal.java
Given the root of a binary tree, return the inorder traversal of its nodes' values.
> Input: root = [1,null,2,3] \
Output: [1,3,2]
```
public List<Integer> inorderTraversal(TreeNode root) {
return result;
}
result.addAll(inorderTraversal(root.left));
result.add(root.val);
result.addAll(inorderTraversal(root.right));
return result;
}
```
`List<Integer> result = new ArrayList<>();`
탐색한 노드의 값을 저장할 `ArrayList` 타입의 `result` 리스트를 생성합니다.
`if (root == null) { return result; }`
`root`가 `null`인 경우, 즉 트리가 비어있거나 리프 노드의 자식을 탐색하려 할 때, 빈 리스트를 반환합니다.
`result.addAll(inorderTraversal(root.left));`
현재 노드의 왼쪽 자식 노드부터 중위 순회를 재귀적으로 수행하고, 그 결과를 `result` 리스트에 추가합니다.
`result.add(root.val);`
현재 노드의 값을 `result` 리스트에 추가합니다. …
=> [94] Binary Tree Inorder Traversal

dlek-user/[88] Merge_Sotred_Array
You are given two integer arrays `nums1` and `nums2`, sorted in non-decreasing order, and two integers `m` and `n`, representing the number of elements in `nums1` and `nums2` respectively.
Merge `nums1` and `nums2` into a single array sorted in non-decreasing order.
The final sorted array should not be returned by the function, but instead be stored inside the array `nums1`. To accommodate this, `nums1` has a length of `m + n`, where the first `m` elements denote the elements that should be merged, and the last `n` elements are set to `0` and should be ignored. `nums2` has a length of `n`.
> Input: nums1 = [1,2,3,0,0,0], m = 3, nums2 = [2,5,6], n = 3
> Output: [1,2,2,3,5,6]
> Explanation: The arrays we are merging are [1,2,3] and [2,5,6].
> The result of the merge is [1,2,2,3,5,6] with …
=> [88] Merge Sotred Array

hyeontaek/SameTree.java
Given the roots of two binary trees p and q, write a function to check if they are the same or not.
Two binary trees are considered the same if they are structurally identical, and the nodes have the
same value.
> Input: p = [1,2,3], q = [1,2,3] \
> Output: true
```
public boolean isSameTree(TreeNode p, TreeNode q) {
if (p == null && q == null) return true;
if (p == null || q == null) return false;
return p.val == q.val && isSameTree(p.left, q.left) && isSameTree(p.right, q.right);
}
```
`if (p == null && q == null) return true;`
두 노드 `p`와 `q`가 모두 `null`인 경우, 즉 두 트리의 해당 부분이 모두 비어있는 경우, 동일하다고 판단하여 `true`를 반환합니다.
`if (p == null || q == null) return false;`
두 노드 중 하나만 `null`인 경우, 즉 한 트리의 해당 부분이 비어있고 다른 트리는 그렇지 않은 경우, 두 트리는 구조적으로 다르므로 `false`를 반환합니다.
`return p.val == q.val && …
=>  [100] Same Tree

dlek-user/[94]Binary_Tree_Inorder_Traversal
Given the `root` of a binary tree, return the inorder traversal of its nodes' values.
> Input: root = [1,null,2,3]
> Output: [1,3,2]
> Output: []
> Output: [1]
```
public List<Integer> inorderTraversal(TreeNode root) {
inorder(root, result);
return result;
}
private void inorder(TreeNode node, List<Integer> result) {
if (node == null) return;
inorder(node.left, result);
result.add(node.val);
inorder(node.right, result);
}
}
```
```
```
중위 순회 결과를 저장할 리스트인 result를 생성합니다.
```
inorder(root, result);
```
inorderTraversal 메서드에서는 중위 순회를 수행하기 위해 inorder 메서드를 호출합니다. 이 메서드는 현재 노드에서부터 중위 순회를 시작하고, 결과를 result 리스트에 저장합니다.
```
private void inorder(TreeNode node, …
```
=> [94]Binary Tree Inorder Traversal

hyeontaek/SymmetricTree.java
Given the root of a binary tree, check whether it is a mirror of itself (i.e., symmetric around its
center).
> Input: root = [1,2,2,3,4,4,3] \
> Output: true
```
public boolean isSymmetric(TreeNode left, TreeNode right) {
if (left == null && right == null) return true;
if (left == null || right == null) return false;
return left.val == right.val && isSymmetric(left.left, right.right) && isSymmetric(left.right, right.left);
}
public boolean isSymmetric(TreeNode root) {
if (root == null) return true;
return isSymmetric(root.left, root.right);
}
```
`isSymmetric(TreeNode left, TreeNode right)`
두 노드가 모두 `null`인 경우, 대칭적이므로 `true`를 반환합니다.
둘 중 하나만 `null`인 경우, 대칭적일 수 없으므로 `false`를 반환합니다.
두 노드의 값이 같은지 확인합니다 `(left.val == right.val).`
`left`의 왼쪽 자식과 `right`의 오른쪽 자식이 대칭적인지, 그리고 `left`의 오른쪽 자식과 …
=> [101] Symmetric Tree

hyeontaek/MaximumDepthOfBinaryTree.java
Given the root of a binary tree, return its maximum depth.
A binary tree's maximum depth is the number of nodes along the longest path from the root node down
to the farthest leaf node.
```
public int maxDepth(TreeNode root) {
return 0;
}
return 1 + Math.max(maxDepth(root.left), maxDepth(root.right));
}
```
`if (root == null) { return 0; }`
이 조건은 현재 노드가 `null`인 경우를 확인합니다. `null` 노드는 트리의 끝을 나타내므로, 깊이에 기여하지 않습니다. 따라서, `0`을 반환합니다.
`return 1 + Math.max(maxDepth(root.left), maxDepth(root.right));`
현재 노드가 `null`이 아니면, 현재 노드의 깊이를 `1`로 계산하고, 왼쪽 자식 노드와 오른쪽 자식 노드에 대해 `maxDepth` 메소드를 재귀적으로 호출합니다. 이 호출은 각각의
서브트리의 최대 깊이를 계산합니다.
`Math.max` 함수를 사용하여 왼쪽과 오른쪽 서브트리 중 더 깊은 깊이를 가진 것을 찾고, `현재 노드의 깊이(1)`를 더해 반환합니다. 이는 현재 노드를 포함하여 더 깊은
서브트리의 전체 깊이를 계산하기 위함입니다.
=> [104] Maximum Depth Of Binary Tree

hyeontaek/ConvertSortedArrayToBinarySearchTree.java
Given an integer array nums where the elements are sorted in ascending order, convert it to a
height-balanced binary search tree.
> ### height-balanced
> A height-balanced binary tree is a binary tree in which the depth of the two subtrees of every node never differs by more than one.
>Input: nums = [-10,-3,0,5,9] \
Output: [0,-3,9,-10,null,5] \
Explanation: [0,-10,5,null,-3,null,9] is also accepted:
```
public TreeNode sortedArrayToBST(int[] nums) {
if (nums.length == 0) return null;
return sort(nums, 0, nums.length - 1);
}
public TreeNode sort(int[] nums, int start, int end) {
if (start > end) return null;
int mid = start + (end - start) / 2;
TreeNode node = new TreeNode(nums[mid]);
node.left = sort(nums, start, mid - 1);
node.right = sort(nums, mid + 1, end);
return node;
}
``` …
=> [108] Convert Sorted Array to BST

hyeontaek/BalancedBinaryTree.java
Given a binary tree, determine if it is height-balanced.
>Input: root = [3,9,20,null,null,15,7] \
Output: true
```
public boolean isBalanced(TreeNode root) {
if (root == null) return true;
return Math.abs(height(root.left) - height(root.right)) <= 1 && isBalanced(root.left) && isBalanced(root.right);
}
public int height(TreeNode root) {
if (root == null) return 0;
return Math.max(height(root.left), height(root.right)) + 1;
}
```
`if (root == null) return true;`
트리가 비어있는 경우, 즉 `root`가 `null`인 경우, 균형 이진 트리로 간주하고 `true`를 반환합니다.
`return Math.abs(height(root.left) - height(root.right)) <= 1 && isBalanced(root.left) && isBalanced(root.right);` \
현재 노드의 왼쪽 부트리와 오른쪽 부트리의 높이 차이가 1 이하인지 확인합니다. 또한, 현재 노드의 왼쪽과 오른쪽 자식 노드에 대해서도 재귀적으로 균형 조건을 검사합니다. 모든 조건이 만족되면 트리는 균형 이진 트리로 간주됩니다.
`if (root == null) …
=>  [110] Balanced Binary Tree

hyeontaek/MinimumDepthOfBinaryTree.java
Given a binary tree, find its minimum depth.
The minimum depth is the number of nodes along the shortest path from the root node down to the nearest leaf node.
Note: A leaf is a node with no children.
>Input: root = [3,9,20,null,null,15,7] \
Output: 2
```
public int minDepth(TreeNode root) {
if (root == null) return 0;
if (root.left == null) return minDepth(root.right) + 1;
if (root.right == null) return minDepth(root.left) + 1;
return Math.min(minDepth(root.left), minDepth(root.right)) + 1;
}
```
`if (root == null) return 0;`
이 조건은 현재 노드가 null인 경우를 검사합니다. 이 경우 트리가 존재하지 않으므로, 최소 깊이는 0입니다.
`if (root.left == null) return minDepth(root.right) + 1;`
현재 노드의 왼쪽 자식이 없고 오른쪽 자식만 있는 경우, 최소 깊이는 오른쪽 서브트리의 최소 깊이에 1을 더한 값입니다. 여기서 1은 현재 노드를 포함하기 위해 더하는 값입니다.
`if (root.right == null) return …
=> [111] Minimum Depth Of Binary Tree

hyeontaek/PascalTriangle.java
Given an integer numRows, return the first numRows of Pascal's triangle.
In Pascal's triangle, each number is the sum of the two numbers directly above it as shown:
> Input: numRows = 5 \
Output: [[1],[1,1],[1,2,1],[1,3,3,1],[1,4,6,4,1]]
```
public List<List<Integer>> generate(int numRows) {
List<List<Integer>> list = new ArrayList<>();
for (int i = 0; i < numRows; i++) {
List<Integer> list2 = new ArrayList<>();
for (int j = 0; j <= i; j++) {
if (j == 0 || j == i) {
list2.add(1);
}
else {
list2.add(list.get(i - 1).get(j - 1) + list.get(i - 1).get(j));
}
}
list.add(list2);
}
return list;
}
```
`List<List<Integer>> list = new ArrayList<>();`
를 사용하여 최종적으로 반환될 리스트를 초기화합니다. 이 리스트는 각각의 행을 `List<Integer>`로 가지게 됩니다.
`외부 루프 (i 루프)`: `numRows`만큼 반복하며, 파스칼 삼각형의 각 행을 생성합니다. `i`는 현재 행을 나타냅니다.
`내부 루프 …
=>  [118] Pascal's Triangle

hyeontaek/PascalTriangle2.java
Given an integer rowIndex, return the rowIndexth (0-indexed) row of the Pascal's triangle.
In Pascal's triangle, each number is the sum of the two numbers directly above it as shown:
>Input: rowIndex = 3 \
Output: [1,3,3,1]
```java
public List<Integer> getRow(int rowIndex) {
List<Integer> list = new ArrayList<>();
for(int i = 0; i <= rowIndex; i++){
list.add(1);
for(int j = i - 1; j > 0; j--){
list.set(j, list.get(j) + list.get(j - 1));
}
}
return list;
}
```
```java
for(int i = 0; i <= rowIndex; i++){
list.add(1);
for(int j = i - 1; j > 0; j--){
list.set(j, list.get(j) + list.get(j - 1));
}
}
```
바깥쪽 for 루프 `(변수 i 사용)`는 0부터 `rowIndex`까지 반복하며 파스칼의 삼각형에서 요구된 행까지를 생성합니다. 각 반복마다 `list`의 마지막에 `1`을 추가하여, 각 행의 맨 처음과 끝이 `1`이 됨을 보장합니다.
안쪽 for 루프 `(변수 j 사용)`는 뒤에서부터 앞으로 이동하며 `(j는 i - 1부터 1까지)`, 각 …
=> [119] Pascal's Triangle2

dlek-user/[104]Maximum_Depth_of_Binary_Tree
Given the root of a binary tree, return its maximum depth.
A binary tree's maximum depth is the number of nodes along the longest path from the root node down to the farthest leaf node.
> Output: 3
> Input: root = [1,null,2]
> Output: 2
```
public int maxDepth(TreeNode root) {
// 빈 트리일 경우 깊이는 0입니다.
return 0;
}
// 왼쪽 서브트리의 최대 깊이와 오른쪽 서브트리의 최대 깊이 중 큰 값을 선택하고 1을 더합니다.
return Math.max(maxDepth(root.left), maxDepth(root.right)) + 1;
}
}
```
빈 트리인 경우에는 깊이를 0으로 간주하여 0을 반환합니다.
그렇지 않은 경우에는 왼쪽 서브트리의 최대 깊이와 오른쪽 서브트리의 최대 깊이 중 큰 값을 선택하고, 1을 더하여 현재 노드를 포함한 깊이를 반환합니다.
=> [104]Maximum_Depth_of_Binary_Tree

itpark1018/TowSum.java
Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.
You may assume that each input would have exactly one solution, and you may not use the same element twice.
You can return the answer in any order.
```
public class TowSum {
public int[] twoSum(int[] nums, int target) {
int answer[] = new int[2];
for (int i = 0 ; i < nums.length ; i++) {
for (int j = i + 1 ; j < nums.length ; j ++ ) {
if (nums[i] + nums[j] == target) {
answer[0] = i;
answer[1] = j;
}
}
}
return answer;
}
}
```
이중 반복문을 사용해서 모든 가능한 조합을 검사했습니다.
=> [1]-Tow Sum

hyeontaek/BestTimeToBuyAndSellStock.java
You are given an array prices where prices[i] is the price of a given stock on the ith day.
You want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock.
Return the maximum profit you can achieve from this transaction. If you cannot achieve any profit, return 0.
> Input: prices = [7,1,5,3,6,4] \
Output: 5 \
Explanation: Buy on day 2 (price = 1) and sell on day 5 (price = 6), profit = 6-1 = 5. \
Note that buying on day 2 and selling on day 1 is not allowed because you must buy before you sell.
```java
public int maxProfit(int[] prices) {
int maxProfit = 0;
int min = Integer.MAX_VALUE;
for (int price : prices) {
min = Math.min(min, price);
maxProfit = Math.max(maxProfit, price - min);
}
return maxProfit;
}
```
`int …
=> [121] Best Time To Buy And Sell Stock

dlek-user/[110]Balanced_Binary_Tree
Given a binary tree, determine if it is 
**height-balanced**
.
> Output: true
> Input: root = [1,2,2,3,3,null,null,4,4]
> Output: true
```
public boolean isBalanced(TreeNode root) {
return getHeight(root) != -1;
}
private int getHeight(TreeNode root) {
return 0;
}
int leftHeight = getHeight(root.left);
if (leftHeight == -1) {
return -1;
}
int rightHeight = getHeight(root.right);
if (rightHeight == -1) {
return -1;
}
if (Math.abs(leftHeight - rightHeight) > 1) {
return -1;
}
return Math.max(leftHeight, rightHeight) + 1;
}
}
```
재귀적으로 각 노드의 왼쪽 서브트리와 오른쪽 서브트리의 높이를 계산합니다.
```
int leftHeight = getHeight(root.left);
if (leftHeight == -1) {
return -1;
}
int rightHeight = …
```
=> [110]Balanced Binary Tree

dlek-user/[108]Convert_Sorted_Array_to_Binary_Search_Tree
Given an integer array `nums` where the elements are sorted in **ascending order**, convert _it to a height-balanced binary search tree_.
> Input: nums = [-10,-3,0,5,9]
> Output: [0,-3,9,-10,null,5]
> Explanation: [0,-10,5,null,-3,null,9] is also accepted:
> Input: nums = [1,3]
> Output: [3,1]
> Explanation: [1,null,3] and [3,1] are both height-balanced BSTs.
```
public TreeNode sortedArrayToBST(int[] nums) {
return sortedArrayToBST(nums, 0, nums.length - 1);
}
private TreeNode sortedArrayToBST(int[] nums, int left, int right) {
if (left > right) {
return null;
}
int mid = left + (right - left) / 2;
TreeNode root = new TreeNode(nums[mid]);
root.left = sortedArrayToBST(nums, left, mid - 1);
root.right = sortedArrayToBST(nums, mid + 1, right);
return root;
}
}
```
```
int …
```
=> [108]Convert Sorted Array to Binary Search Tree

hyeontaek/ValidPalindrome.java
A phrase is a palindrome if, after converting all uppercase letters into lowercase letters and removing all non-alphanumeric characters, it reads the same forward and backward. Alphanumeric characters include letters and numbers.
Given a string s, return true if it is a palindrome, or false otherwise.
> Input: s = "A man, a plan, a canal: Panama" \
Output: true \
Explanation: "amanaplanacanalpanama" is a palindrome.
```java
public boolean isPalindrome(String s) {
String str = s.replaceAll("[^A-Za-z0-9]", "").toLowerCase();
int start = 0;
int end = str.length() - 1;
while (start < end) {
if (str.charAt(start) != str.charAt(end)) {
return false;
}
start++;
end--;
}
return true;
}
```
`replaceAll("[^A-Za-z0-9]", "")`
주어진 문자열 s에서 알파벳과 숫자를 제외한 모든 문자를 제거합니다.
`toLowerCase()`
그 결과로 얻은 문자열을 모두 …
=> [125] Valid Palindrome

dlek-user/[111]Minimum_Depth_of_Binary
Given a binary tree, find its minimum depth.
The minimum depth is the number of nodes along the shortest path from the root node down to the nearest leaf node.
**Note**: A leaf is a node with no children.
> Output: 2
> Input: root = [2,null,3,null,4,null,5,null,6]
> Output: 5
```
public int minDepth(TreeNode root) {
return 0;
}
int leftDepth = minDepth(root.left);
int rightDepth = minDepth(root.right);
if (leftDepth == 0 || rightDepth == 0) {
return Math.max(leftDepth, rightDepth) + 1;
}
return Math.min(leftDepth, rightDepth) + 1;
}
}
```
#
```
int leftDepth = minDepth(root.left);
int rightDepth = minDepth(root.right);
```
왼쪽 서브트리와 오른쪽 서브트리의 최소 깊이를 재귀적으로 구합니다.
```
if (leftDepth == 0 || rightDepth == 0) {
return …
```
=> [111]Minimum Depth of Binary

hyeontaek/SingleNumber.java
Given a non-empty array of integers nums, every element appears twice except for one. Find that single one.
You must implement a solution with a linear runtime complexity and use only constant extra space.
> Input: nums = [2,2,1] \
Output: 1
```java
public int singleNumber(int[] nums) {
int result = 0;
result ^= num;
}
return result;
}
```
배열 `nums`를 순회하면서 각 숫자에 대해 `result`와 `XOR` `연산(^=)`을 수행합니다.
`XOR` 연산의 특성상, 어떤 숫자와 자기 자신을 XOR 연산하면 결과는 0이 되고, 어떤 숫자와 `0`을 `XOR` 연산하면 그 숫자가 그대로 나옵니다.
따라서, 배열 내에서 동일한 숫자가 두 번 나타나면 그 숫자들의 XOR 연산 결과는 0이 됩니다. 그리고 `0`과 단 한 번만 나타나는 숫자의 `XOR` 연산 결과는 그 숫자 자체가 됩니다.
결과적으로, 모든 숫자에 대해 `XOR` 연산을 수행하면, 단 한 번만 나타나는 숫자만이 `result`에 남게 됩니다.
=> [136] Single Number

hyeontaek/LinkedListCycle.java
Given head, the head of a linked list, determine if the linked list has a cycle in it.
There is a cycle in a linked list if there is some node in the list that can be reached again by continuously following the next pointer. Internally, pos is used to denote the index of the node that tail's next pointer is connected to. Note that pos is not passed as a parameter.
Return true if there is a cycle in the linked list. Otherwise, return false.
> Input: head = [3,2,0,-4], pos = 1 \
Output: true \
Explanation: There is a cycle in the linked list, where the tail connects to the 1st node (0-indexed).
```java
public boolean hasCycle(ListNode head) {
if (head == null) return false;
ListNode slow = head;
ListNode fast = head.next;
while (fast != null && fast.next != null) {
if (slow == fast) return …
```
=>  [141] Linked List Cycle

hyeontaek/BinaryTreePreorderTraversal.java
Given the root of a binary tree, return the preorder traversal of its nodes' values.
> Input: root = [1,null,2,3] \
Output: [1,2,3]
```java
public List<Integer> preorderTraversal(TreeNode root) {
List<Integer> list = new ArrayList<>();
if (root == null) return list;
list.add(root.val);
list.addAll(preorderTraversal(root.left));
list.addAll(preorderTraversal(root.right));
return list;
}
```
`ArrayList<Integer>` 
타입의 list를 생성하여 순회하는 동안 방문한 노드의 값을 저장합니다.
`if (root == null) return list;`
를 통해 기저 조건을 처리합니다. 만약 현재 노드(root)가 `null`이면 빈 리스트를 반환합니다. 이는 더 이상 순회할 노드가 없음을 의미합니다.
`list.add(root.val);`
를 사용하여 현재 노드의 값을 리스트에 추가합니다. 전위 순회에서는 루트 노드를 먼저 처리하기 때문입니다.
`list.addAll(preorderTraversal(root.left));`
재귀 호출을 통해 왼쪽 서브트리를 전위 순회하고, 그 결과를 현재 리스트에 추가합니다
`list.addAll(preorderTraversal(root.right));` …
=> [144] Binary Tree Preorder Traversal

dlek-user/[118] Pascal's_Triangle
Given an integer `numRows`, return the first numRows of **Pascal's triangle**.
In **Pascal's triangle**, each number is the sum of the two numbers directly above it as shown:
> Input: numRows = 5
> Output: [[1],[1,1],[1,2,1],[1,3,3,1],[1,4,6,4,1]]
> Input: numRows = 1
```
public List<List<Integer>> generate(int numRows) {
List<List<Integer>> triangle = new ArrayList<>();
if (numRows <= 0) {
return triangle;
}
triangle.add(new ArrayList<>());
triangle.get(0).add(1);
for (int rowNum = 1; rowNum < numRows; rowNum++) {
List<Integer> row = new ArrayList<>();
row.add(1);
List<Integer> prevRow = triangle.get(rowNum - 1);
for (int j = 1; j < rowNum; j++) {
row.add(prevRow.get(j - 1) + prevRow.get(j));
}
row.add(1);
triangle.add(row);
}
return triangle;
}
}
```
# …
=> [118] Pascal's Triangle

hyeontaek/BinaryTreePostorderTraversal.java
Given the root of a binary tree, return the postorder traversal of its nodes' values.
> Input: root = [1,null,2,3] \
> Output: [3,2,1]
```java
public class BinaryTreePostorderTraversal {
public List<Integer> postorderTraversal(TreeNode root) {
return result;
}
postorderTraversal(root.left);
postorderTraversal(root.right);
result.add(root.val);
return result;
}
}
```
`BinaryTreePostorderTraversal` 클래스는 후위 순회 결과를 저장하기 위한 멤버 변수 `result`를 가지고 있으며, 이는 `List<Integer>` 타입입니다.
`postorderTraversal` 메소드는 트리의 루트 노드를 인자로 받아 후위 순회를 시작합니다. 루트 노드가 `null`인 경우, 즉 트리가 비어있는 경우 현재의 `result`
리스트를 반환합니다.
루트 노드가 `null`이 아닌 경우, `postorderTraversal` 메소드는 재귀적으로 루트 노드의 왼쪽 자식과 오른쪽 자식에 대하여 후위 순회를 수행합니다.
왼쪽 서브트리와 오른쪽 서브트리의 후위 순회가 완료된 후, 현재 루트 노드의 값을 …
=> [145] Binary Tree Postorder Traversal

hyeontaek/IntersectionOfTwoLinkedLists.java
Given the heads of two singly linked-lists headA and headB, return the node at which the two lists intersect. If the two linked lists have no intersection at all, return null.
For example, the following two linked lists begin to intersect at node 
c1:
The test cases are generated such that there are no cycles anywhere in the entire linked structure.
Note that the linked lists must retain their original structure after the function returns.
Custom Judge:
The inputs to the judge are given as follows (your program is not given these inputs):
- `intersectVal` - The value of the node where the intersection occurs. This is 0 if there is no intersected node.
- `listA` - The first linked list.
- `listB` - The second linked list.
- `skipA` - The number of nodes to skip ahead in `listA` (starting …
=> [160] Intersection Of Two Linked Lists

hyeontaek/ExcelSheetColumnTitle.java
Given an integer columnNumber, return its corresponding column title as it appears in an Excel sheet.
> ### For example
> A -> 1\
B -> 2\
C -> 3\
...\
Z -> 26\
AA -> 27\
AB -> 28\
...
> Input: columnNumber = 1 \
> Output: "A" 
```java
public String convertToTitle(int n) {
StringBuilder sb = new StringBuilder();
while (n > 0) {
n--;
sb.append((char) ('A' + n % 26));
n /= 26;
}
return sb.reverse().toString();
}
```
`StringBuilder` 인스턴스 `sb`를 생성합니다. 이는 최종 문자열을 구성하기 위해 사용됩니다.
입력된 숫자 `n`이 `0`보다 클 동안 반복합니다. `n > 0`이 거짓이 될 때까지 이 과정을 반복합니다.
`n--`을 수행하여 n을 1 감소시킵니다. 엑셀의 열 번호는 1부터 시작하지만, 배열 인덱스는 0부터 시작하기 때문에 이 조정이 필요합니다.
`n % 26`을 계산하여 현재 숫자를 26으로 나눈 나머지를 구하고, 이를 이용해 해당하는 알파벳 문자를 찾습니다. `'A' + n % 26`은 `n % 26`에 해당하는 알파벳 문자를 구하기 위해 `ASCII` 코드 값을 사용합니다. 그리고 이 문자를 `StringBuilder`에 추가합니다.
`n /= 26`을 …
=>  [168] Excel Sheet Column Title

dlek-user/[121] Best Time to Buy Sell Stock
You are given an array `prices` where `prices[i]` is the price of a given stock on the `ith` day.
You want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock.
Return the maximum profit you can achieve from this transaction. If you cannot achieve any profit, return `0`.
> Input: prices = [7,1,5,3,6,4]
> Output: 5
> Explanation: Buy on day 2 (price = 1) and sell on day 5 (price = 6), profit = 6-1 = 5.
> Note that buying on day 2 and selling on day 1 is not allowed because you must buy before you sell.
> Input: prices = [7,6,4,3,1]
> Output: 0
> Explanation: In this case, no transactions are done and the max profit = 0.
```
public int maxProfit(int[] prices) {
int minPrice = Integer.MAX_VALUE;
int …
```
=> [121] Best Time to Buy Sell Stock

hyeontaek/MajorityElement.java
Given an array nums of size n, return the majority element.
The majority element is the element that appears more than ⌊n / 2⌋ times. You may assume that the majority element always exists in the array.
> Input: nums = [3,2,3] \
Output: 3
```java
public int majorityElement(int[] nums) {
int count = 0;
int candidate = 0;
if (count == 0) {
candidate = num;
}
count += (num == candidate) ? 1 : -1;
}
return candidate;
}
```
`count`를 `0`으로, `candidate`를 `0`으로 초기화합니다. 
여기서 `count`는 현재 후보의 투표 수를 나타내고, `candidate`는 현재 다수 요소 후보를 나타냅니다.
주어진 배열 `nums`의 모든 요소에 대해 순회합니다. 각 요소를 `num`이라고 할 때,
만약 `count`가 `0`이면, 현재 요소 `num`을 새로운 다수 요소 후보로 선정합니다`(candidate = num).`
현재 요소 `num`이 현재 후보 `candidate`와 같다면 `count`를 `1` 증가시키고, 그렇지 않다면 `count`를 `1` 감소시킵니다
`(count += (num == candidate) ? 1 : …
=> [169] Majority Element

dlek-user/[125] Vaild Palindrome
A phrase is a **palindrome** if, after converting all uppercase letters into lowercase letters and removing all non-alphanumeric characters, it reads the same forward and backward. Alphanumeric characters include letters and numbers.
Given a string `s`, return `true` if it is a **palindrome**, or `false` otherwise.
> Input: s = "A man, a plan, a canal: Panama"
> Output: true
> Explanation: "amanaplanacanalpanama" is a palindrome.
> Input: s = "race a car"
> Explanation: "raceacar" is not a palindrome.
> Input: s = " "
> Output: true
> Explanation: s is an empty string "" after removing non-alphanumeric characters.
> Since an empty string reads the same forward and backward, it is a palindrome.
```
public boolean isPalindrome(String s) {
int start = 0, end …
```
=> [125] Vaild Palindrome

hyeontaek/ExcelSheetColumnNumber.java
Given a string columnTitle that represents the column title as appears in an Excel sheet, return its corresponding column number.
> A -> 1 \
B -> 2 \
C -> 3 \
... \
Z -> 26 \
AA -> 27 \
AB -> 28 \
... 
> Input: columnTitle = "A" \
Output: 1
```java
public int titleToNumber(String s) {
int result = 0;
result = result * 26 + (c - 'A' + 1);
}
return result;
}
```
초기화: `result`를 `0`으로 초기화합니다. `result`는 최종적으로 계산되어 반환될 숫자입니다.
문자열 순회: 입력된 문자열 s의 모든 문자에 대해 순회합니다. 이를 위해 `s.toCharArray()`를 사용하여 문자열을 문자 배열로 변환하고, 각 문자를 `c`라고 합니다.
계산: 각 문자 `c`에 대해, `result`를 `26`배 하고 현재 문자 `c`가 나타내는 숫자를 더합니다. 여기서 (c - 'A' + 1)은 현재 문자 c의 알파벳 순서를 구하는 계산입니다. 예를 들어, `A`의 경우 `1`, `B`의 경우 `2`가 됩니다. 이는 엑셀 열 제목이 `1`부터 시작하는 `26`진법 숫자로 해석될 수 있음을 의미합니다.
결과 반환: 모든 문자에 대한 계산이 완료되면, `result`에 최종 …
=> [171] Excel Sheet Column Number

dlek-user/[141] Linked List Cycle
Given `head`, the head of a linked list, determine if the linked list has a cycle in it.
There is a cycle in a linked list if there is some node in the list that can be reached again by continuously following the `next` pointer. Internally, `pos` is used to denote the index of the node that tail's `next` pointer is connected to. **Note that** `pos` **is not passed as a parameter**.
Return `true` _if there is a cycle in the linked list_. Otherwise, return `false`.
> Input: head = [3,2,0,-4], pos = 1
> Output: true
> Explanation: There is a cycle in the linked list, where the tail connects to the 1st node (0-indexed).
> Input: head = [1,2], pos = 0
> Output: true
> Explanation: There is a cycle in the linked list, where the tail connects to the 0th node.
> Input: head = [1], pos = -1
> …
=> [141] Linked List Cycle

hyeontaek/ReverseBits.java
Reverse bits of a given 32 bits unsigned integer.
Note:
- Note that in some languages, such as Java, there is no unsigned integer type. In this case, both input and output will be given as a signed integer type. They should not affect your implementation, as the integer's internal binary representation is the same, whether it is signed or unsigned.
- In Java, the compiler represents the signed integers using 2's complement notation. Therefore, in Example 2 above, the input represents the signed integer -3 and the output represents the signed integer -1073741825.
> Input: n = 00000010100101000001111010011100 \
Output:    964176192 (00111001011110000010100101000000) \
Explanation: The input binary string 00000010100101000001111010011100 represents the unsigned integer 43261596, so return …
=> [190] Reverse Bits

hyeontaek/NumberOf1Bits.java
Write a function that takes the binary representation of a positive integer and returns the number
of
set bits
it has (also known as the Hamming weight).
> Input: n = 11
>
>Output: 3
>
>Explanation:
>
>The input binary string 1011 has a total of three set bits.
```java
public int hammingWeight(int n) {
int count = 0;
while (n != 0) {
count += n & 1;
n >>>= 1;
}
return count;
}
```
카운트 변수 초기화: `int count = 0;` 라인에서, 1로 설정된 비트의 수를 세기 위한 변수 `count`를 0으로 초기화합니다.
루프를 통한 비트 카운트: `while (n != 0)` 루프에서는 `n`이 `0`이 아닐 때까지 반복합니다. 이는 `n`의 모든 비트를 확인할 때까지 반복한다는 의미입니다.
비트 AND 연산: `count += n & 1;`에서, `n`의 가장 오른쪽 비트가 1인지 확인합니다. `&`는 비트 단위 `AND` 연산자입니다. `n & 1`의 결과가 `1`
이면, 가장 오른쪽 비트가 1이고, `count`를 `1` 증가시킵니다. 결과가 0이면, 가장 오른쪽 비트가 0이므로 `count`는 변하지 않습니다.
비트 오른쪽 시프트 연산: `n >>>= 1;`에서, `n`을 오른쪽으로 1비트 시프트합니다. …
=> [191] Number Of 1 Bits

hyeontaek/HappyNumber.java
Write an algorithm to determine if a number n is happy.
A happy number is a number defined by the following process:
- Starting with any positive integer, replace the number by the sum of the squares of its digits.
- Repeat the process until the number equals 1 (where it will stay), or it loops endlessly in a cycle
which does not include 1.
Those numbers for which this process ends in 1 are happy.
Return true if n is a happy number, and false if not.
>Input: n = 19 \
Output: true \
Explanation: \
12 + 92 = 82 \
82 + 22 = 68 \
62 + 82 = 100 \
12 + 02 + 02 = 1
```java
public boolean isHappy(int n) {
int sum = 0;
while (n > 0) {
sum += (int) Math.pow(n % 10, 2);
n /= 10;
}
if (sum == 1) {
return true;
}
if (sum == 4) {
return false;
}
return isHappy(sum);
}
```
합계 변수 초기화: `int sum = 0;`에서, …
=>  [202] Happy Number

dlek-user/[169] Magority Element
Given an array `nums` of size `n`, return the majority element.
The majority element is the element that appears more than `⌊n / 2⌋` times. You may assume that the majority element always exists in the array.
> Input: nums = [3,2,3]
> Output: 3
> Input: nums = [2,2,1,1,1,2,2]
> Output: 2
> 
```
public int majorityElement(int[] nums) {
int candidate = nums[0];
int count = 0;
if (count == 0) {
candidate = num;
}
count += (num == candidate) ? 1 : -1;
}
return candidate;
}
}
```
#
```
int candidate = nums[0];
int count = 0;
```
candidate는 현재 다수 요소의 후보입니다.
count는 현재 후보의 카운터로, 후보가 배열에서 얼마나 자주 나타나는지를 추적합니다.
```
for (int num : nums) { ```}
```
배열을 순회하며 후보를 찾습니다.
```
if (count == 0) {
candidate = num;
}
```
count가 0이면 현재 요소를 새로운 후보로 설정하고, 카운터를 1로 초기화합니다.
``` …
=> [169] Magority Element

hyeontaek/IsomorphicString.java
Given two strings s and t, determine if they are isomorphic.
Two strings s and t are isomorphic if the characters in s can be replaced to get t.
All occurrences of a character must be replaced with another character while preserving the order of
characters. No two characters may map to the same character, but a character may map to itself.
> Input: s = "egg", t = "add" \
> Output: true
```java
public boolean isIsomorphic(String s, String t) {
if (s.length() != t.length()) {
return false;
}
if (s.indexOf(s.charAt(i)) != t.indexOf(t.charAt(i))) {
return false;
}
}
return true;
}
```
```java
if (s.length() != t.length()) {
return false;
}
```
두 문자열의 길이가 다르면, 그들은 동형일 수 없기 때문에 바로 `false`를 반환합니다.
```java
if …
```
=> [205] Isomorcphic Strings

hyeontaek/ReverseLinkedList.java
Given the head of a singly linked list, reverse the list, and return the reversed list.
> Input: head = [1,2,3,4,5] \
> Output: [5,4,3,2,1]
```java
public ListNode reverseList(ListNode head) {
ListNode prev = null;
ListNode curr = head;
while (curr != null) {
ListNode nextTemp = curr.next;
curr.next = prev;
prev = curr;
curr = nextTemp;
}
return prev;
}
```
반복문을 통한 리스트 순회:
`while (curr != null) { ... }`
현재 노드가 `null`이 아닐 때까지 반복합니다. `null`이면 리스트의 끝에 도달한 것입니다.
리스트 역순 만들기:
반복문 내에서 다음과 같은 단계를 거칩니다:
`ListNode nextTemp = curr.next;`
현재 노드의 다음 노드를 임시 변수 nextTemp에 저장합니다. 이는 현재 노드의 `next` 포인터를 변경한 후에도 다음
노드로 이동할 수 있게 합니다.
`curr.next = prev;`
현재 노드의 `next` 포인터를 이전 노드 `prev`로 변경합니다. 이는 리스트의 역순을 만드는 핵심 단계입니다.
`prev = curr;`
이전 노드를 현재 노드로 업데이트합니다.
`curr = nextTemp;` 
현재 노드를 다음 노드(역순 만들기 전의 다음 노드)로 …
=> [206] Reverse Linked List

hyeontaek/ContainsDuplicate.java
Given an integer array nums, return true if any value appears at least twice in the array, and return false if every element is distinct.
> Input: nums = [1,2,3,1]
Output: true
```java
public boolean containsDuplicate(int[] nums) {
Set<Integer> result = new HashSet<>();
if (result.contains(num)) {
return true;
}
result.add(num);
}
return false;
}
```
배열 순회 및 중복 검사:
`for (int num : nums) { ... }`
배열 `nums`의 각 요소를 순회합니다.
`if (result.contains(num)) { return true; }`
현재 요소 `num`이 이미 `HashSet`에 포함되어 있는지 검사합니다. 만약 포함되어 있으면, 중복된 요소가 존재한다는 의미이므로 `true`를 반환합니다.
`result.add(num);`
현재 요소 `num`을 `HashSet`에 추가합니다. 중복된 요소가 없는 경우에만 추가됩니다.
중복 없음 반환:
`return false;`
배열의 모든 요소를 검사한 후에도 중복된 요소가 발견되지 않으면 `false`를 반환합니다.
=> [217] Contains Duplicate

dlek-user/[202] Happy Number
Write an algorithm to determine if a number `n` is happy.
A happy number is a number defined by the following process:
- Starting with any positive integer, replace the number by the sum of the squares of its digits.
- Repeat the process until the number equals 1 (where it will stay), or it **loops endlessly in a cycle** which does not include 1.
- Those numbers for which this process **ends in 1** are happy.
Return `true` if `n` is a happy number, and `false` if not.
> Input: n = 19
> Output: true
> Explanation:
> 12 + 92 = 82
> 82 + 22 = 68
> 62 + 82 = 100
> 12 + 02 + 02 = 1
> Input: n = 2
```
public boolean isHappy(int n) {
int slow = n;
int fast = getNext(n);
while (fast != 1 && slow != fast) {
slow = getNext(slow);
fast = getNext(getNext(fast));
} …
```
=> [202] Happy Number

hyeontaek/ContainsDuplicate2.java
Given an integer array nums and an integer k, return true if there are two distinct indices i and j
in the array such that `nums[i] == nums[j] and abs(i - j) <= k.`
> Input: nums = [1,2,3,1], k = 3 \
Output: true
```java
public boolean containsNearbyDuplicate(int[] nums, int k) {
Set<Integer> set = new HashSet<>();
if (i > k) {
set.remove(nums[i - k - 1]);
}
if (!set.add(nums[i])) {
return true;
}
}
return false;
}
```
배열 순회 및 중복 검사
`for (int i = 0; i < nums.length; i++) { ... }`
배열 `nums`의 각 요소를 순회합니다.
`if (i > k) { set.remove(nums[i - k - 1]); }`
인덱스 `i`가 `k`보다 클 경우, `set`에서 `k` 거리 이상 떨어진 요소를 제거합니다. 이는 `k` 이내의
거리에 있는 요소만 `set`에 유지하기 위함입니다.
`if (!set.add(nums[i])) { return true; }`
현재 요소 `nums[i]`를 `set`에 추가하려고 시도합니다. `add` 메소드가 `false`를 반환하면, 이는 …
=> [219] Contains Duplicate 2

hyeontaek/CountCompleteTreesNode.java
Given the root of a complete binary tree, return the number of the nodes in the tree.
According to Wikipedia, every level, except possibly the last, is completely filled in a complete
binary tree, and all nodes in the last level are as far left as possible. It can have between 1 and
2h nodes inclusive at the last level h.
Design an algorithm that runs in less than O(n) time complexity.
> Input: root = [1,2,3,4,5,6] \
> Output: 6
```java
public int countNodes(TreeNode root) {
return 0;
}
return 1 + countNodes(root.left) + countNodes(root.right);
}
```
`if (root == null) { return 0; }`
재귀의 기본 조건입니다. 현재 노드가 `null`일 경우, 더 이상 세어야 할 노드가 없으므로 0을 반환합니다.
`return 1 + countNodes(root.left) + countNodes(root.right);`
현재 노드가 `null`이 아니면, 현재 노드를 포함하여(1을 더하여) 왼쪽
서브트리의 노드 수와 오른쪽 서브트리의 …
=> [222] Count Complete Tree Nodes

dlek-user/[205] Isomorphic Strings
Given two strings `s` and `t`, determine if they are isomorphic.
Two strings `s` and `t` are isomorphic if the characters in `s` can be replaced to get `t`.
All occurrences of a character must be replaced with another character while preserving the order of characters. No two characters may map to the same character, but a character may map to itself.
> Input: s = "egg", t = "add"
> Output: true
> Input: s = "foo", t = "bar"
> Input: s = "paper", t = "title"
> Output: true
```
public boolean isIsomorphic(String s, String t) {
if (s.length() != t.length()) {
return false;
}
int[] mapS = new int[256];
int[] mapT = new int[256];
char charS = s.charAt(i);
char charT = t.charAt(i);
if (mapS[charS] != mapT[charT]) {
return …
```
=> [205] Isomorphic Strings

hyeontaek/ImplementStackUsingQueues.java
Implement a last-in-first-out (LIFO) stack using only two queues. The implemented stack should
support all the functions of a normal stack (push, top, pop, and empty).
Implement the MyStack class:
- void push(int x) Pushes element x to the top of the stack.
- int pop() Removes the element on the top of the stack and returns it.
- int top() Returns the element on the top of the stack.
- boolean empty() Returns true if the stack is empty, false otherwise.
- Notes:
- You must use only standard operations of a queue, which means that only push to back, peek/pop
from
front, size and is empty operations are valid.
- Depending on your language, the queue may not be supported natively. You may simulate a queue
using
a list or deque (double-ended queue) as long as you use only a queue's standard …
=>  [225] Implement Stack Using Queues

hyeontaek/InvertBinaryTree.java
Given the root of a binary tree, invert the tree, and return its root.
> Input: root = [4,2,7,1,3,6,9] \
> Output: [4,7,2,9,6,3,1]
```java
public TreeNode invertTree(TreeNode root) {
return null;
}
TreeNode temp = root.left;
root.left = root.right;
root.right = temp;
invertTree(root.left);
invertTree(root.right);
return root;
}
```
`if (root == null) { return null; }`
현재 노드가 null이면, 더 이상 작업할 필요가 없으므로 null을 반환합니다. 이는 재귀 호출의 종료
조건입니다.
`TreeNode temp = root.left;`
왼쪽 자식 노드를 임시 변수 temp에 저장합니다.
`root.left = root.right;`
오른쪽 자식 노드를 왼쪽 자식 노드 위치로 이동시킵니다.
`root.right = temp;`
임시 변수에 저장된 원래 왼쪽 자식 노드를 오른쪽 자식 노드 위치로 이동시킵니다.
`invertTree(root.left);`
왼쪽 자식 노드에 대해 재귀적으로 invertTree 함수를 호출하여, 서브트리를 반전시킵니다.
`invertTree(root.right);`
오른쪽 자식 노드에 대해서도 마찬가지로 재귀적으로 invertTree 함수를 호출하여, 서브트리를 …
=> [226] Invert Binary Tree

hyeontaek/SummaryRanges.java
You are given a sorted unique integer array nums.
A range `[a,b]` is the set of all integers from a to b (inclusive).
Return the smallest sorted list of ranges that cover all the numbers in the array exactly. That is,
each element of nums is covered by exactly one of the ranges, and there is no integer x such that x
is in one of the ranges but not in nums.
Each range `[a,b]` in the list should be output as:
`"a->b"` if `a != b`
`"a"` if `a == b`
> Input: nums = [0,1,2,4,5,7] \
> Output: ["0->2","4->5","7"] \
> Explanation: The ranges are: \
[0,2] --> "0->2" \
[4,5] --> "4->5" \
[7,7] --> "7"
```java
public List<String> summaryRanges(int[] nums) {
int start = 0;
int end = 0;
if (i == nums.length - 1 || nums[i] …
```
=> [228] Summary Ranges

hyeontaek/PowerOfTwo.java
Given an integer n, return true if it is a power of two. Otherwise, return false.
An integer n is a power of two, if there exists an integer x such that n == 2x.
> Input: n = 1 \
> Output: true \
> Explanation: 20 = 1
```java
public boolean isPowerOfTwo(int n) {
if (n == 0) {
return false;
}
if (n == 1) {
return true;
}
if (n % 2 != 0) {
return false;
}
return isPowerOfTwo(n / 2);
}
public boolean isPowerOfTwo2(int n) {
return n > 0 && (n & (n - 1)) == 0;
}
public boolean isPowerOfTwo3(int n) {
for (int i = 0; i < 32; i++) {
if (n == Math.pow(2, i)) {
return true;
}
}
return false;
}
```
`if (n == 0) { return false; }`
n이 0이면 2의 거듭제곱이 아니므로 false를 반환합니다.
`if (n == 1) { return true; }`
n이 1이면 2^0이므로 true를 반환합니다.
`if (n % 2 != 0) { return false; }`
n이 홀수이면 2의 거듭제곱이 아니므로 false를 반환합니다.
`return …
=> [231] Power Of Two

dlek-user/[225] Implement Stack using Queues
Implement a last-in-first-out (LIFO) stack using only two queues. The implemented stack should support all the functions of a normal stack (`push`, `top`, `pop`, and `empty`).
Implement the `MyStack` class:
- `void push(int x)` Pushes element x to the top of the stack.
- `int pop()` Removes the element on the top of the stack and returns it.
- `int top()` Returns the element on the top of the stack.
- `boolean empty()` Returns `true` if the stack is empty, `false` otherwise.
**Notes**:
- You must use only standard operations of a queue, which means that only `push to back`, `peek/pop from front`, `size` and `is empty` operations are valid.
- Depending on your language, the queue may not be supported natively. You may simulate a queue using a list or deque (double-ended queue) as long as …
=> [225] Implement Stack using Queues

hyeontaek/ImplementQueueUsingStack.java
mplement a first in first out (FIFO) queue using only two stacks. The implemented queue should
support all the functions of a normal queue (push, peek, pop, and empty).
Implement the MyQueue class:
- void push(int x) Pushes element x to the back of the queue.
- int pop() Removes the element from the front of the queue and returns it.
- int peek() Returns the element at the front of the queue.
- boolean empty() Returns true if the queue is empty, false otherwise.
- You must use only standard operations of a stack, which means only push to top, peek/pop from top,
size, and is empty operations are valid.
- Depending on your language, the stack may not be supported natively. You may simulate a stack
using
a list or deque (double-ended queue) as long as you use only a stack's standard …
=> [232] Implement Queue Using Stacks

hyeontaek/PalindromeLinkedList.java
Given the head of a singly linked list, return true if it is a
palindrome or false otherwise.
> Input: head = [1,2,2,1] \
> Output: true
```java
public boolean isPalindrome(ListNode head) {
if (head == null) {
return true;
}
ListNode slow = head;
ListNode fast = head;
while (fast != null && fast.next != null) {
slow = slow.next;
fast = fast.next.next;
}
ListNode prev = null;
while (slow != null) {
ListNode next = slow.next;
slow.next = prev;
prev = slow;
slow = next;
}
while (prev != null) {
if (head.val != prev.val) {
return false;
}
head = head.next;
prev = prev.next;
}
return true;
}
```
두 포인터를 이용한 접근 방식입니다. 빠른 포인터(fast)와 느린 포인터(slow)를 사용하여 리스트의 중간 지점을 찾습니다. fast 포인터는 한 번에 두 칸씩, slow
포인터는 한 번에 한 칸씩 이동합니다. 이렇게 하면 fast가 끝에 도달했을 때, slow는 정확히 중간에 위치하게 됩니다.
중간에서 시작하여 리스트의 뒷부분을 역순으로 만듭니다. …
=> [234] Palindrome Linked List

hyeontaek/ValidAnagram.java
Given two strings s and t, return true if t is an anagram of s, and false otherwise.
An Anagram is a word or phrase formed by rearranging the letters of a different word or phrase,
typically using all the original letters exactly once.
> Input: s = "anagram", t = "nagaram" \
> Output: true
```java
public boolean isAnagram(String s, String t) {
Map<Character, Integer> map = new HashMap<>();
map.put(c, map.getOrDefault(c, 0) + 1);
}
for (char c : t.toCharArray()) {
if (!map.containsKey(c)) {
return false;
}
map.put(c, map.get(c) - 1);
if (map.get(c) == 0) {
map.remove(c);
}
}
return map.isEmpty();
}
public boolean isAnagram2(String s, String t) {
char[] sChars = s.toCharArray();
char[] tChars = t.toCharArray();
Arrays.sort(sChars);
Arrays.sort(tChars); …
```
=> [242] Valid Anagram

hyeontaek/AddDigits.java
Given an integer num, repeatedly add all its digits until the result has only one digit, and return
it.
> Input: num = 38 \
> Output: 2 \
> Explanation: The process is \
> 38 --> 3 + 8 --> 11 \
> 11 --> 1 + 1 --> 2 \
> Since 2 has only one digit, return it.
```java
public int addDigits(int num) {
int sum = 0;
while (num > 0) {
sum += num % 10;
num /= 10;
}
if (sum < 10) {
return sum;
}
return addDigits(sum);
}
```
`while (num > 0)`
루프는 `num`이 `0`보다 클 때까지 반복됩니다.
`num % 10`을 통해 `num`의 가장 오른쪽 자리 숫자를 추출하고, 이를 `sum`에 더합니다.
`num /= 10`은 `num`을 `10`으로 나누어 가장 오른쪽 자리 숫자를 제거합니다.
`sum`이 `10`보다 작은 경우, 즉 한 자리 숫자인 경우 `sum`을 반환합니다.
`sum`이 여전히 두 자리 이상의 숫자인 경우, `addDigits(sum)`을 재귀적으로 호출하여 한 자리 숫자가 나올 때까지 과정을 반복합니다.
=> [258] Add Digits

dlek-user/[257] Binary Tree Paths
Given the `root` of a binary tree, return _all root-to-leaf paths in **any order**._
A **leaf** is a node with no children.
> Input: root = [1,2,3,null,5]
> Output: ["1->2->5","1->3"]
> Output: ["1"]
```
```
#
```
return paths;
}
```
루트 노드가 null이면 빈 경로 리스트를 반환합니다. 이는 트리가 비어 있는 경우를 처리합니다.
```
dfs(root, "", paths);
```
dfs 메서드를 호출하여 트리를 탐색합니다. 초기 경로는 빈 문자열입니다.
```
return paths;
```
모든 경로를 저장한 리스트를 반환합니다.
```
path += Integer.toString(node.val);
```
현재 노드의 값을 문자열로 변환하여 경로에 추가합니다.
```
if (node.left == null && node.right == null) {```}
```
현재 노드가 리프 노드인지 확인합니다. (즉, 왼쪽 자식과 오른쪽 자식이 모두 null인 경우)
```
paths.add(path);
```
리프 노드인 경우: 현재 경로를 결과 리스트에 추가합니다.
```
path += "->";
dfs(node.left, path, paths);
dfs(node.right, path, paths);
```
리프 노드가 아닌 경우: 경로에 "->"를 …
```
=> [257] Binary Tree Paths

hyeontaek/MissingNumber.java
Given an array nums containing n distinct numbers in the range [0, n], return the only number in the
range that is missing from the array.
> Input: nums = [3,0,1] \
> Output: 2 \
> Explanation: n = 3 since there are 3 numbers, so all numbers are in the range [0,3]. 2 is the
> missing number in the range since it does not appear in nums.
```java
public int missingNumber(int[] nums) {
int sum = n * (n + 1) / 2;
int actualSum = 0;
actualSum += num;
}
return sum - actualSum;
}
```
`int n = nums.length;`
배열의 길이를 n에 저장합니다. 배열 nums는 0부터 n까지의 숫자 중 하나가 빠졌기 때문에 길이는 n이 됩니다.
`int sum = n * (n + 1) / 2;`
가우스의 합 공식을 사용하여 0부터 n까지의 합을 계산합니다. 예를 들어, n이 4라면 0 + 1 + 2 + 3 + 4 = 10이
됩니다.
`int actualSum = 0;`
배열의 실제 합을 저장할 변수를 초기화합니다.
`for (int num : nums) { …
=> [268] Missing Number

dlek-user/[263] Ugly Number
An **ugly number** is a positive integer whose prime factors are limited to `2`, `3`, and `5`.
Given an integer `n`, return `true` _if `n` is an **ugly number**_.
> Input: n = 6
> Output: true
> Explanation: 6 = 2 × 3
> Input: n = 1
> Output: true
> Explanation: 1 has no prime factors, therefore all of its prime factors are limited to 2, 3, and 5.
> Input: n = 14
> Explanation: 14 is not ugly since it includes the prime factor 7.
```
public boolean isUgly(int n) {
if (n <= 0) {
return false;
}
int[] primes = {2, 3, 5};
for (int prime : primes) {
while (n % prime == 0) {
n /= prime;
}
}
return n == 1;
}
}
```
#
```
if (n <= 0) {
return false;
}
```
n이 0 이하인 경우 false를 반환합니다. 이는 0 이하의 수는 못생긴 수가 아니기 때문입니다.
```
int[] primes = {2, 3, 5};
```
primes 배열에 2, 3, 5를 …
=> [263] Ugly Number

hyeontaek/FirstBadVersion.java
You are a product manager and currently leading a team to develop a new product. Unfortunately, the
latest version of your product fails the quality check. Since each version is developed based on the
previous version, all the versions after a bad version are also bad.
Suppose you have n versions [1, 2, ..., n] and you want to find out the first bad one, which causes
all the following ones to be bad.
You are given an API bool isBadVersion(version) which returns whether version is bad. Implement a
function to find the first bad version. You should minimize the number of calls to the API.
> Input: n = 5, bad = 4 \
> Output: 4 \
> Explanation: \
> call isBadVersion(3) -> false \
> call isBadVersion(5) -> true \
> call isBadVersion(4) -> true \
> Then 4 is the first bad version.
```java …
```
=> [278] First Bad Version

hyeontaek/MoveZeroes.java
Given an integer array nums, move all 0's to the end of it while maintaining the relative order of
the non-zero elements.
Note that you must do this in-place without making a copy of the array.
> Input: nums = [0,1,0,3,12] \
> Output: [1,3,12,0,0]
```java
public void moveZeroes(int[] nums) {
int idx = 0;
if (nums[i] != 0) {
nums[idx++] = nums[i];
}
}
for (int i = idx; i < nums.length; i++) {
nums[i] = 0;
}
}
```
`int idx = 0;`
이 변수는 배열에서 다음으로 삽입될 위치를 추적합니다.
`for (int i = 0; i < nums.length; i++)`
이 첫 번째 루프는 배열 nums의 모든 요소를 반복합니다.
`if (nums[i] != 0)`
이 조건은 현재 요소가 0이 아닌지 확인합니다.
`nums[idx++] = nums[i];`
위 조건이 참이면, 현재 요소 nums[i]가 nums[idx]에 복사되고, idx 변수가 증가합니다. 이를 통해 0이 아닌 요소가
배열의 앞부분에 유지됩니다.
`for (int i = idx; i < nums.length; i++)`
두 번째 루프는 idx부터 배열 …
=> [283] Move Zeroes

hyeontaek/WordPattern.java
Given a pattern and a string s, find if s follows the same pattern.
Here follow means a full match, such that there is a bijection between a letter in pattern and a
non-empty word in s.
>Input: pattern = "abba", s = "dog cat cat dog" \
Output: true
```java
public boolean wordPattern(String pattern, String s) {
String[] words = s.split(" ");
if (words.length != pattern.length()) {
return false;
}
Map<Character, String> map = new HashMap<>();
for (int i = 0; i < pattern.length(); i++) {
char c = pattern.charAt(i);
if (map.containsKey(c)) {
if (!map.get(c).equals(words[i])) {
return false;
}
} else {
if (map.containsValue(words[i])) {
return false;
}
map.put(c, words[i]);
}
}
return true;
}
```
`String[] words = s.split(" ");`
입력 문자열 s를 공백 문자를 기준으로 분할하여 단어 배열을 생성합니다.
`if (words.length != …
=> [290] Word Pattern

dlek-user/[292] Nim Game
You are playing the following Nim Game with your friend:
- Initially, there is a heap of stones on the table.
- You and your friend will alternate taking turns, and you go first.
- On each turn, the person whose turn it is will remove 1 to 3 stones from the heap.
- The one who removes the last stone is the winner.
Given `n`, the number of stones in the heap, return `true` _if you can win the game assuming both you and your friend play optimally, otherwise return_ `false`.
> Input: n = 4
> Explanation: These are the possible outcomes:
> 1. You remove 1 stone. Your friend removes 3 stones, including the last stone. Your friend wins.
> 2. You remove 2 stones. Your friend removes 2 stones, including the last stone. Your friend wins.
> 3. You remove 3 stones. Your friend …
=> [292] Nim Game

hyeontaek/RangeSumQueryImmutable.java
Given an integer array nums, handle multiple queries of the following type:
Calculate the sum of the elements of nums between indices left and right inclusive where left <=
right.
Implement the NumArray class:
NumArray(int[] nums) Initializes the object with the integer array nums.
int sumRange(int left, int right) Returns the sum of the elements of nums between indices left and
right inclusive (i.e. nums[left] + nums[left + 1] + ... + nums[right]).
>Input
["NumArray", "sumRange", "sumRange", "sumRange"] \
[[[-2, 0, 3, -5, 2, -1]], [0, 2], [2, 5], [0, 5]] \
Output \
[null, 1, -1, -3] \
\
Explanation \
NumArray numArray = new NumArray([-2, 0, 3, -5, 2, -1]); \
numArray.sumRange(0, 2); // return (-2) + 0 + 3 = 1 \
numArray.sumRange(2, 5); // return 3 + (-5) + 2 + (-1) = -1 \ …
=> [303] Range Sum Query - Immutable

hyeontaek/PowerOfThree.java
Given an integer n, return true if it is a power of three. Otherwise, return false.
An integer n is a power of three, if there exists an integer x such that n == 3x.
> Input: n = 27 \
> Output: true \
> Explanation: 27 = 33
```java
public boolean isPowerOfThree(int n) {
if (n == 0) {
return false;
}
if (n == 1) {
return true;
}
if (n % 3 != 0) {
return false;
}
return isPowerOfThree(n / 3);
}
```
`if (n == 0) { return false; }`
먼저 입력 n이 0인 경우 false를 반환합니다. 0은 3의 거듭제곱이 아니기 때문입니다.
`if (n == 1) { return true; }`
다음으로 입력 n이 1인 경우 true를 반환합니다. 1은 3의 0제곱이기 때문입니다.
`if (n % 3 != 0) { return false; }`
입력 n이 3의 배수가 아닌 경우 false를 반환합니다. 3의 거듭제곱은 반드시 3의 배수이기 때문입니다.
`return isPowerOfThree(n / 3);`
마지막으로 입력 n을 3으로 나눈 결과에 대해 재귀적으로 isPowerOfThree 메서드를 호출합니다.
=> [326] Power Of Three

hyeontaek/CountingBits.java
Given an integer n, return an array ans of length n + 1 such that for each i (0 <= i <= n), ans[i] is the number of 1's in the binary representation of i.
> Input: n = 2 \
Output: [0,1,1] \
Explanation: \
0 --> 0 \
1 --> 1 \
2 --> 10
```java
public static int[] countBits(int n) {
int[] ans = new int[n + 1];
for (int i = 0; i <= n; ++i) {
ans[i] = Integer.bitCount(i);
}
return ans;
}
```
`int[] ans = new int[n + 1];`
결과 배열 ans를 생성합니다. 이 배열의 크기는 n + 1로, 0부터 n까지의 모든 정수를 담을 수 있습니다.
`for (int i = 0; i <= n; ++i) { ans[i] = Integer.bitCount(i); }`
`Integer.bitCount(i)`
정수 i의 이진수 표현에서 1의 개수를 계산합니다.
`ans[i] = Integer.bitCount(i);`
계산된 1의 개수를 결과 배열 ans의 해당 인덱스에 저장합니다.
`return ans;`
계산된 결과 배열 ans를 반환합니다.
=> [338] Counting Bits

hyeontaek/PowerOfFour.java
Given an integer n, return true if it is a power of four. Otherwise, return false.
An integer n is a power of four, if there exists an integer x such that n == 4x.
> Input: n = 16 \
> Output: true
```java
public boolean isPowerOfFour(int n) {
if (n == 1) {
return true;
}
if (n % 4 != 0 || n == 0) {
return false;
}
return isPowerOfFour(n / 4);
}
```
`if (n == 1) { return true; }`
먼저 입력 n이 1인 경우 true를 반환합니다. 1은 4의 0제곱이기 때문입니다.
`if (n % 4 != 0 || n == 0) { return false; }`
다음으로 입력 n이 4의 배수가 아니거나 0인 경우 false를 반환합니다. 4의 거듭제곱은 반드시 4의 배수이기 때문입니다.
`return isPowerOfFour(n / 4);`
마지막으로 입력 n을 4로 나눈 결과에 대해 재귀적으로 isPowerOfFour 메서드를 호출합니다.
=>  [342] Power Of Four

dlek-user/[342] Power of Four
Given an integer `n`, return `true` _if it is a power of four. Otherwise, return `false`_.
An integer `n` is a power of four, if there exists an integer `x` such that `n == 4x`.
> Input: n = 16
> Output: true
> Input: n = 5
> Input: n = 1
> Output: true
```
public boolean isPowerOfFour(int n) {
return n > 0 && (n & (n - 1)) == 0 && (n & 0xAAAAAAAA) == 0;
}
}
```
#
```
return n > 0 && (n & (n - 1)) == 0 && (n & 0xAAAAAAAA) == 0;
```
입력값 n이 양수인지 확인합니다.
(n & (n - 1)) == 0: n이 2의 거듭제곱인지 확인합니다.
(n & 0xAAAAAAAA) == 0: n이 홀수 비트에만 1이 있는지 확인합니다. 여기서 0xAAAAAAAA는 짝수 비트가 1인 마스크입니다.
=> [342] Power of Four

hyeontaek/ReverseString.java
Write a function that reverses a string. The input string is given as an array of characters s.
You must do this by modifying the input array in-place with O(1) extra memory.
> Input: s = ["h","e","l","l","o"]
Output: ["o","l","l","e","h"]
```java
public void reverseString(char[] s) {
int left = 0;
int right = s.length - 1;
char temp = s[left];
s[left] = s[right];
s[right] = temp;
left++;
right--;
}
}
```
`int left = 0;`
문자열의 시작 인덱스를 나타내는 left 변수를 0으로 초기화합니다.
`int right = s.length - 1;`
문자열의 마지막 인덱스를 나타내는 right 변수를 문자열의 길이 s.length - 1로 초기화합니다.
`while (left < right) { ... }`
left가 right보다 작은 동안 다음 작업을 반복합니다:
`char temp = s[left];`
left 인덱스의 문자를 임시 변수 temp에 저장합니다.
`s[left] = s[right];`
right 인덱스의 문자를 left 인덱스에 복사합니다.
`s[right] = temp;`
임시 변수 temp에 저장된 left 인덱스의 문자를 …
=> [344] Reverse String

dlek-user/[345] Reverse Vowels of a String
Given a string `s`, reverse only all the vowels in the string and return it.
The vowels are `'a'`, `'e'`, `'i'`, `'o'`, and `'u'`, and they can appear in both lower and upper cases, more than once.
> Input: s = "hello"
> Output: "holle"
> Input: s = "leetcode"
> Output: "leotcede"
```
public String reverseVowels(String s) {
char[] chars = s.toCharArray();
int left = 0;
int right = chars.length - 1;
String vowels = "aeiouAEIOU";
while (left < right && vowels.indexOf(chars[left]) == -1) {
left++;
}
while (left < right && vowels.indexOf(chars[right]) == -1) {
right--;
}
if (left < right) {
char temp = chars[left];
chars[left] = chars[right];
chars[right] = temp;
left++;
right--;
}
}
return new String(chars);
}
}
```
#
```
while (left < right && …
```
=> [345] Reverse Vowels of a String

dlek-user/[349] Intersection of Two Arrays
Given two integer arrays `nums1` and `nums2`, return _an array of their 
intersection_. Each element in the result must be **unique** and you may return the result in **any order**.
> Input: nums1 = [1,2,2,1], nums2 = [2,2]
> Output: [2]
> Input: nums1 = [4,9,5], nums2 = [9,4,9,8,4]
> Output: [9,4]
> Explanation: [4,9] is also accepted.
```
public int[] intersection(int[] nums1, int[] nums2) {
Set<Integer> set1 = new HashSet<>();
for (int num : nums1) {
set1.add(num);
}
Set<Integer> intersection = new HashSet<>();
for (int num : nums2) {
if (set1.contains(num)) {
intersection.add(num);
}
}
int[] result = new int[intersection.size()];
int i = 0;
for (int num : intersection) {
result[i++] = num;
}
return result;
}
}
```
#
```
Set<Integer> set1 = new HashSet<>();
for (int …
```
=> [349] Intersection of Two Arrays

dlek-user/[350] Intersection of Two Arrays 2
Given two integer arrays `nums1` and `nums2`, return _an array of their intersection_. Each element in the result must appear as many times as it shows in both arrays and you may return the result in **any order**.
> Input: nums1 = [1,2,2,1], nums2 = [2,2]
> Output: [2,2]
> Input: nums1 = [4,9,5], nums2 = [9,4,9,8,4]
> Output: [4,9]
> Explanation: [9,4] is also accepted.
```
public int[] intersect(int[] nums1, int[] nums2) {
Arrays.sort(nums1);
Arrays.sort(nums2);
int i = 0, j = 0;
List<Integer> intersection = new ArrayList<>();
while (i < nums1.length && j < nums2.length) {
if (nums1[i] < nums2[j]) {
i++;
} else if (nums1[i] > nums2[j]) {
j++;
} else {
intersection.add(nums1[i]);
i++;
j++;
}
}
int[] result = new int[intersection.size()];
for (int k = 0; k < …
```
=> [350] Intersection of Two Arrays 2

dlek-user/[367] Valid Perfect Square
Given a positive integer num, return `true` _if_ `num` _is a perfect square or_ `false` _otherwise_.
A **perfect square** is an integer that is the square of an integer. In other words, it is the product of some integer with itself.
You must not use any built-in library function, such as `sqrt`.
> Input: num = 16
> Output: true
> Explanation: We return true because 4 * 4 = 16 and 4 is an integer.
> Input: num = 14
> Explanation: We return false because 3.742 * 3.742 = 14 and 3.742 is not an integer.
```
public boolean isPerfectSquare(int num) {
if (num < 1) {
return false;
}
long left = 1, right = num;
long mid = left + (right - left) / 2;
long square = mid * mid;
if (square == num) {
return true;
} else if (square < num) {
left = …
```
=> [367] Valid Perfect Square

dlek-user/[374] Guess Number Higher or Lower
We are playing the Guess Game. The game is as follows:
I pick a number from `1` to `n`. You have to guess which number I picked.
Every time you guess wrong, I will tell you whether the number I picked is higher or lower than your guess.
You call a pre-defined API `int guess(int num)`, which returns three possible results:
- `-1`: Your guess is higher than the number I picked (i.e. `num > pick`).
- `1`: Your guess is lower than the number I picked (i.e. `num < pick`).
- `0`: your guess is equal to the number I picked (i.e. `num == pick`).
Return the number that I picked.
> Input: n = 10, pick = 6
> Output: 6
> Input: n = 1, pick = 1
> Output: 1
> Input: n = 2, pick = 1
> Output: 1
```
public class Solution extends GuessGame {
public int guessNumber(int n) {
int left = 1, right = n;
while …
```
=> [374] Guess Number Higher or Lower

dlek-user/[383] Ransom Note
Given two strings `ransomNote` and `magazine`, return `true` _if_ `ransomNote` _can be constructed by using the letters from_ `magazine` _and_ `false` _otherwise_.
Each letter in `magazine` can only be used once in `ransomNote`.
> Input: ransomNote = "a", magazine = "b"
> Input: ransomNote = "aa", magazine = "ab"
> Input: ransomNote = "aa", magazine = "aab"
> Output: true
```
public boolean canConstruct(String ransomNote, String magazine) {
int[] charCount = new int[26];
for (char c : magazine.toCharArray()) {
charCount[c - 'a']++;
}
for (char c : ransomNote.toCharArray()) {
if (charCount[c - 'a'] == 0) {
return false;
}
charCount[c - 'a']--;
}
return true;
}
}
```
#
```
int[] charCount = new int[26];
for (char c : magazine.toCharArray()) { …
```
=> [383] Ransom Note

dlek-user/[387] First Unique Character in a String
Given a string `s`, _find the first non-repeating character in it and return its index_. If it does not exist, return `-1`.
> Input: s = "leetcode"
> Output: 0
> Input: s = "loveleetcode"
> Output: 2
> Input: s = "aabb"
> Output: -1
```
public int firstUniqChar(String s) {
int[] charCount = new int[26];
charCount[c - 'a']++;
}
if (charCount[s.charAt(i) - 'a'] == 1) {
return i;
}
}
return -1;
}
}
```
#
```
int[] charCount = new int[26];
```
알파벳 소문자의 빈도를 저장할 배열을 생성합니다.
```
charCount[c - 'a']++;
}
```
문자열 s를 순회하며 각 문자의 빈도를 배열에 저장합니다. 예를 들어, 'a'는 charCount[0], 'b'는 charCount[1]에 해당합니다.
```
if (charCount[s.charAt(i) - 'a'] == 1) { …
```
=> [387] First Unique Character in a String

dlek-user/[389] Find the Difference
You are given two strings `s` and `t`.
String `t` is generated by random shuffling string `s` and then add one more letter at a random position.
Return the letter that was added to `t`.
> Input: s = "abcd", t = "abcde"
> Output: "e"
> Explanation: 'e' is the letter that was added.
> Input: s = "", t = "y"
> Output: "y"
```
public char findTheDifference(String s, String t) {
int charCode = 0;
charCode ^= c;
}
for (char c : t.toCharArray()) {
charCode ^= c;
}
return (char) charCode;
}
}
```
#
```
int charCode = 0;
```
charCode 변수를 초기화합니다. 이 변수는 XOR 연산 결과를 저장합니다.
```
charCode ^= c;
}
```
s의 모든 문자를 순회하며 charCode에 XOR 연산을 수행합니다.
```
for (char c : t.toCharArray()) {
charCode ^= c;
}
```
t의 모든 문자를 순회하며 charCode에 …
=> [389] Find the Difference

dlek-user/[401] Binary Watch
A binary watch has 4 LEDs on the top to represent the hours (0-11), and 6 LEDs on the bottom to represent the minutes (0-59). Each LED represents a zero or one, with the least significant bit on the right.
- For example, the below binary watch reads `"4:51"`.
Given an integer `turnedOn` which represents the number of LEDs that are currently on (ignoring the PM), return all possible times the watch could represent. You may return the answer in **any order**.
The hour must not contain a leading zero.
- For example, `"01:00"` is not valid. It should be `"1:00"`.
The minute must consist of two digits and may contain a leading zero.
- For example, `"10:2"` is not valid. It should be `"10:02"`.
> Input: turnedOn = 1
> Output: ["0:01","0:02","0:04","0:08","0:16","0:32","1:00","2:00","4:00","8:00" …
=> [401] Binary Watch

dlek-user/[404] Sum of Left Leaves
Given the `root` of a binary tree, return _the sum of all left leaves_.
A leaf is a node with no children. A **left leaf** is a leaf that is the left child of another node.
> Output: 24
> Explanation: There are two left leaves in the binary tree, with values 9 and 15 respectively.
> Output: 0
```
public int sumOfLeftLeaves(TreeNode root) {
if (root == null) return 0;
int sum = 0;
if (root.left != null) {
if (root.left.left == null && root.left.right == null) {
sum += root.left.val;
} else {
sum += sumOfLeftLeaves(root.left);
}
}
sum += sumOfLeftLeaves(root.right);
return sum;
}
}
```
#
```
if (root == null) return 0;
```
현재 노드가 null이면 0을 반환하여 더 이상 탐색하지 않습니다.
```
if (root.left != null) {
if (root.left.left == null …
```
=> [404] Sum of Left Leaves

dlek-user/[405] Convert a Number to Hexadecimal
Given an integer `num`, return _a string representing its hexadecimal representation_. For negative integers, [two’s complement method is used.
All the letters in the answer string should be lowercase characters, and there should not be any leading zeros in the answer except for the zero itself.
**Note**: You are not allowed to use any built-in library method to directly solve this problem.
> Input: num = 26
> Output: "1a"
> Input: num = -1
> Output: "ffffffff"
```
public String toHex(int num) {
if (num == 0) {
return "0";
}
char[] hexChars = "0123456789abcdef".toCharArray();
StringBuilder hexString = new StringBuilder();
while (num != 0) {
int hexDigit = num & 15;
hexString.append(hexChars[hexDigit]);
num >>>= 4;
}
return hexString.reverse().toString();
}
}
```
#
```
if …
```
=> [405] Convert a Number to Hexadecimal

dlek-user/[409] Longest Palindrome
Given a string `s` which consists of lowercase or uppercase letters, return the length of the **longest palindrome**
that can be built with those letters.
Letters are **case sensitive**, for example, `"Aa"` is not considered a palindrome.
> Input: s = "abccccdd"
> Output: 7
> Explanation: One longest palindrome that can be built is "dccaccd", whose length is 7.
> Input: s = "a"
> Output: 1
> Explanation: The longest palindrome that can be built is "a", whose length is 1.
```
public int longestPalindrome(String s) {
if (s == null || s.length() == 0) {
return 0;
}
int[] charCounts = new int[128];
charCounts[c]++;
}
int length = 0;
boolean hasOddFrequency = false;
for (int count : charCounts) {
if (count % 2 == 0) {
length += count;
} else { …
```
=> [409] Longest Palindrome

dlek-user/[412] Fizz Buzz
Given an integer `n`, return a string array `answer` (1-indexed) where:
- `answer[i] == "FizzBuzz"` if `i` is divisible by `3` and `5`.
- `answer[i] == "Fizz"` if `i` is divisible by `3`.
- `answer[i] == "Buzz"` if `i` is divisible by `5`.
- `answer[i] == i` (as a string) if none of the above conditions are true.
> Input: n = 3
> Output: ["1","2","Fizz"]
> Input: n = 5
> Output: ["1","2","Fizz","4","Buzz"]
> Input: n = 15
> Output: ["1","2","Fizz","4","Buzz","Fizz","7","8","Fizz","Buzz","11","Fizz","13","14","FizzBuzz"]
```
public List<String> fizzBuzz(int n) {
List<String> answer = new ArrayList<>();
for (int i = 1; i <= n; i++) {
if (i % 3 == 0 && i % 5 == 0) {
answer.add("FizzBuzz");
} else if (i % 3 == 0) {
answer.add("Fizz");
} else if (i % 5 == 0) { …
```
=> [412] Fizz Buzz

dlek-user/[414] Third Maximum Number
Given an integer array `nums`, return _the **third distinct maximum** number in this array. If the third **maximum** does not exist, return the maximum number_.
> Input: nums = [3,2,1]
> Output: 1
> Explanation:
> The first distinct maximum is 3.
> The second distinct maximum is 2.
> The third distinct maximum is 1.
> Input: nums = [1,2]
> Output: 2
> Explanation:
> The first distinct maximum is 2.
> The second distinct maximum is 1.
> The third distinct maximum does not exist, so the maximum (2) is returned instead.
> Input: nums = [2,2,3,1]
> Output: 1
> Explanation:
> The first distinct maximum is 3.
> The second distinct maximum is 2 (both 2's are counted together since they have the same value).
> The third distinct maximum is 1.
> 
```
public int thirdMax(int[] …
```
=> [414] Third Maximum Number

dlek-user/[415] Add Strings
Given two non-negative integers, `num1` and `num2` represented as string, return the sum of `num1` and `num2` as a string.
You must solve the problem without using any built-in library for handling large integers (such as `BigInteger`). You must also not convert the inputs to integers directly.
> Input: num1 = "11", num2 = "123"
> Output: "134"
> Input: num1 = "456", num2 = "77"
> Output: "533"
> Input: num1 = "0", num2 = "0"
> Output: "0"
```
public String addStrings(String num1, String num2) {
StringBuilder result = new StringBuilder();
int carry = 0;
int p1 = num1.length() - 1;
int p2 = num2.length() - 1;
while (p1 >= 0 || p2 >= 0) {
int x1 = p1 >= 0 ? num1.charAt(p1) - '0' : 0;
int x2 = p2 >= 0 ? num2.charAt(p2) - '0' : 0;
int sum = x1 + x2 + carry;
carry = sum / 10; …
```
=> [415] Add Strings

dlek-user/[434] Number of Segments in a String
Given a string `s`, return _the number of segments in the string_.
A **segment** is defined to be a contiguous sequence of **non-space characters**.
> Input: s = "Hello, my name is John"
> Output: 5
> Explanation: The five segments are ["Hello,", "my", "name", "is", "John"]
> Input: s = "Hello"
> Output: 1
```
public int countSegments(String s) {
if (s == null || s.length() == 0) {
return 0;
}
int segmentCount = 0;
boolean inSegment = false;
if (s.charAt(i) != ' ') {
if (!inSegment) {
segmentCount++;
inSegment = true;
}
} else {
inSegment = false;
}
}
return segmentCount;
}
}
```
#
```
if (s == null || s.length() == 0)
```
문자열이 null이거나 빈 문자열일 경우 세그먼트가 없으므로 0을 반환합니다.
```
int segmentCount = 0;
```
세그먼트의 개수를 저장하는 변수입니다.
```
boolean …
```
=> [434] Number of Segments in a String

dlek-user/[441] Arranging Coins
You have `n` coins and you want to build a staircase with these coins. The staircase consists of `k` rows where the `ith` row has exactly `i` coins. The last row of the staircase **may be** incomplete.
Given the integer `n`, return _the number of complete rows of the staircase you will build_.
> Input: n = 5
> Output: 2
> Explanation: Because the 3rd row is incomplete, we return 2.
> Input: n = 8
> Output: 3
> Explanation: Because the 4th row is incomplete, we return 3.
```
public int arrangeCoins(int n) {
long left = 0;
long right = n;
long mid = left + (right - left) / 2;
long kCoins = mid * (mid + 1) / 2;
if (kCoins == n) {
return (int)mid;
} else if (kCoins < n) {
left = mid + 1;
} else {
right = mid - 1;
}
}
return (int)right;
}
}
```
#
``` …
```
=> [441] Arranging Coins

dlek-user[448] Find All Number Disappeared in an Array
Given an array `nums` of `n` integers where `nums[i]` is in the range `[1, n]`, return _an array of all the integers in the range_ `[1, n]` _that do not appear in_ `nums`.
> Input: nums = [4,3,2,7,8,2,3,1]
> Output: [5,6]
> Input: nums = [1,1]
> Output: [2]
```
public List<Integer> findDisappearedNumbers(int[] nums) {
int index = Math.abs(nums[i]) - 1;
if (nums[index] > 0) {
nums[index] = -nums[index];
}
}
if (nums[i] > 0) {
result.add(i + 1);
}
}
return result;
}
}
```
#
```
```
누락된 숫자를 저장할 리스트를 초기화합니다.
```
int index = Math.abs(nums[i]) - 1;
if (nums[index] > 0) { …
```
=> [448] Find All Number Disappeared in an Array

dlek-user/[455] Assign Cookies
Assume you are an awesome parent and want to give your children some cookies. But, you should give each child at most one cookie.
Each child `i` has a greed factor `g[i]`, which is the minimum size of a cookie that the child will be content with; and each cookie `j` has a size `s[j]`. If `s[j] >= g[i]`, we can assign the cookie `j` to the child `i`, and the child `i` will be content. Your goal is to maximize the number of your content children and output the maximum number.
> Input: g = [1,2,3], s = [1,1]
> Output: 1
> Explanation: You have 3 children and 2 cookies. The greed factors of 3 children are 1, 2, 3. 
> And even though you have 2 cookies, since their size is both 1, you could only make the child whose greed factor is 1 content.
> You need to output 1.
> Input: g = [1,2], s = …
=> [455] Assign Cookies

dlek-user/[459] Repeated Substring Pattern
Given a string `s`, check if it can be constructed by taking a substring of it and appending multiple copies of the substring together.
> Input: s = "abab"
> Output: true
> Explanation: It is the substring "ab" twice.
> Input: s = "aba"
> Input: s = "abcabcabcabc"
> Output: true
> Explanation: It is the substring "abc" four times or the substring "abcabc" twice.
> 
```
public boolean repeatedSubstringPattern(String s) {
String t = s + s;
return t.substring(1, t.length() - 1).contains(s);
}
}
```
#
```
String t = s + s;
```
주어진 문자열 s를 두 번 이어붙여서 새로운 문자열 t를 만듭니다.
```
return t.substring(1, t.length() - 1).contains(s);
```
t에서 첫 번째와 마지막 문자를 제외한 부분 문자열을 추출하여 s가 포함되는지 확인합니다.
만약 포함된다면, 이는 s가 어떤 부분 문자열을 반복하여 구성된 것임을 의미합니다.
=> [459] Repeated Substring Pattern

dlek-user/[461] Hamming Distance
The Hamming distance between two integers is the number of positions at which the corresponding bits are different.
Given two integers `x` and `y`, return _the **Hamming distance** between them_.
> Input: x = 1, y = 4
> Output: 2
> Explanation:
> 1   (0 0 0 1)
> 4   (0 1 0 0)
>        ↑   ↑
> The above arrows point to positions where the corresponding bits are different.
> Input: x = 3, y = 1
> Output: 1
```
public int hammingDistance(int x, int y) {
int xor = x ^ y;
int distance = 0;
while (xor != 0) {
distance += xor & 1;
xor >>= 1;
}
return distance;
}
}
```
#
```
int xor = x ^ y;
```
주어진 두 정수 x와 y의 XOR 연산을 수행하여 xor 결과를 계산합니다.
```
int distance = 0;
while (xor != 0) {
distance += xor & 1;
xor >>= 1;
}
```
xor의 결과에서 1의 개수를 세어 Hamming 거리를 계산합니다.
xor & 1은 xor의 가장 오른쪽 비트가 …
=> [461] Hamming Distance

dlek-user/[476] Nubmer Complement
The **complement** of an integer is the integer you get when you flip all the `0`'s to `1`'s and all the `1`'s to `0`'s in its binary representation.
For example, The integer `5` is `"101"` in binary and its **complement** is `"010"` which is the integer `2`.
Given an integer `num`, return its complement.
> Input: num = 5
> Output: 2
> Explanation: The binary representation of 5 is 101 (no leading zero bits), and its complement is 010. So you need to output 2.
> Input: num = 1
> Output: 0
> Explanation: The binary representation of 1 is 1 (no leading zero bits), and its complement is 0. So you need to output 0.
```
public int findComplement(int num) {
int n = num;
int mask = 0;
while (n != 0) {
n >>= 1;
mask = (mask << 1) | 1;
}
return num ^ mask;
}
}
```
#
```
int n = …
```
=> [476] Nubmer Complement

dlek-user/[482] License Key Formatting
You are given a license key represented as a string `s` that consists of only alphanumeric characters and dashes. The string is separated into `n + 1` groups by `n` dashes. You are also given an integer `k`.
We want to reformat the string `s` such that each group contains exactly `k` characters, except for the first group, which could be shorter than `k` but still must contain at least one character. Furthermore, there must be a dash inserted between two groups, and you should convert all lowercase letters to uppercase.
Return _the reformatted license key_.
> Input: s = "5F3Z-2e-9-w", k = 4
> Output: "5F3Z-2E9W"
> Explanation: The string s has been split into two parts, each part has 4 characters.
> Note that the two extra dashes are not needed and can be removed.
> Input: s = "2-5g-3-J", …
=> [482] License Key Formatting

dlek-user/[485] Max Consecutive Ones
Given a binary array `nums`, return _the maximum number of consecutive `1`'s in the array_.
> Input: nums = [1,1,0,1,1,1]
> Output: 3
> Explanation: The first two digits or the last three digits are consecutive 1s. The maximum number of consecutive 1s is 3.
> Input: nums = [1,0,1,1,0,1]
> Output: 2
```
public int findMaxConsecutiveOnes(int[] nums) {
int maxCount = 0;
int currentCount = 0;
if (num == 1) {
currentCount++;
if (currentCount > maxCount) {
maxCount = currentCount;
}
} else {
currentCount = 0;
}
}
return maxCount;
}
}
```
#
```
int maxCount = 0;
```
maxCount는 현재까지 찾은 최대 연속된 1의 개수를 저장합니다.
```
int currentCount = 0;
```
currentCount는 현재 연속된 1의 개수를 저장합니다.
```
```
배열 nums의 각 요소 num을 순회합니다.
```
if (num == 1) { …
```
=> [485] Max Consecutive Ones

dlek-user/[492] Construct the Rectangle
A web developer needs to know how to design a web page's size. So, given a specific rectangular web page’s area, your job by now is to design a rectangular web page, whose length L and width W satisfy the following requirements:
1. The area of the rectangular web page you designed must equal to the given target area.
2. The width `W` should not be larger than the length `L`, which means `L >= W`.
3. The difference between length `L` and width `W` should be as small as possible.
Return 
> an array `[L, W]` where `L` and `W` are the length and width of the web page you designed in sequence
.
> Input: area = 4
> Output: [2,2]
> Explanation: The target area is 4, and all the possible ways to construct it are [1,4], [2,2], [4,1]. 
> But according to requirement 2, [1,4] is illegal; according …
=> [492] Construct the Rectangle

dlek-user/[495] Teemo Attacking
Our hero Teemo is attacking an enemy Ashe with poison attacks! When Teemo attacks Ashe, Ashe gets poisoned for a exactly `duration` seconds. More formally, an attack at second `t` will mean Ashe is poisoned during the inclusive time interval `[t, t + duration - 1]`. If Teemo attacks again before the poison effect ends, the timer for it is reset, and the poison effect will end `duration` seconds after the new attack.
You are given a non-decreasing integer array `timeSeries`, where `timeSeries[i]` denotes that Teemo attacks Ashe at second `timeSeries[i]`, and an integer `duration`.
Return _the **total** number of seconds that Ashe is poisoned_.
> Input: timeSeries = [1,4], duration = 2
> Output: 4
> Explanation: Teemo's attacks on Ashe go as follows:
> - At second 1, Teemo attacks, and Ashe …
=> [495] Teemo Attacking

dlek-user/[496] Next Greater Element 1
The **next greater element** of some element `x` in an array is the **first greater** element that is **to the right** of `x` in the same array.
You are given two **distinct 0-indexed** integer arrays `nums1` and `nums2`, where `nums1` is a subset of `nums2`.
For each `0 <= i < nums1.length`, find the index `j` such that `nums1[i] == nums2[j]` and determine the **next greater element** of `nums2[j]` in `nums2`. If there is no next greater element, then the answer for this query is `-1`.
Return _an array `ans` of length `nums1.length` such that `ans[i]` is the **next greater element** as described above_.
> Input: nums1 = [4,1,2], nums2 = [1,3,4,2]
> Output: [-1,3,-1]
> Explanation: The next greater element for each value of nums1 is as follows:
> - 4 is underlined in nums2 = [1,3,4,2]. …
=> [496] Next Greater Element 1

dlek-user/[500] Keyboard Row
Given an array of strings `words`, return _the words that can be typed using letters of the alphabet on only one row of American keyboard like the image below_.
In the **American keyboard**:
- the first row consists of the characters `"qwertyuiop"`,
- the second row consists of the characters `"asdfghjkl"`, and
- the third row consists of the characters `"zxcvbnm"`.
> Input: words = ["Hello","Alaska","Dad","Peace"]
> Output: ["Alaska","Dad"]
> Input: words = ["omk"]
> Output: []
> Input: words = ["adsdf","sfd"]
> Output: ["adsdf","sfd"]
```
public String[] findWords(String[] words) {
String row1 = "qwertyuiop";
String row2 = "asdfghjkl";
String row3 = "zxcvbnm";
Map<Character, Integer> charToRowMap = new HashMap<>();
for (char c : row1.toCharArray()) {
charToRowMap.put(c, …
```
=> [500] Keyboard Row

dlek-user/[501] Find Mode in Binary Search Tree
Given the `root` of a binary search tree (BST) with duplicates, return _all the [mode(s)](https://en.wikipedia.org/wiki/Mode_(statistics)) (i.e., the most frequently occurred element) in it_.
If the tree has more than one mode, return them in **any order**.
Assume a BST is defined as follows:
- The left subtree of a node contains only nodes with keys **less than or equal to** the node's key.
- The right subtree of a node contains only nodes with keys **greater than or equal to** the node's key.
- Both the left and right subtrees must also be binary search trees.
> Input: root = [1,null,2,2]
> Output: [2]
> Input: root = [0]
> Output: [0]
```
class TreeNode {
int val;
TreeNode left;
TreeNode right;
TreeNode(int x) { val = x; }
}
int maxStreak = 0;
int currStreak = 0;
int …
```
=> [501] Find Mode in Binary Search Tree

dlek-user/[504] Base 7
Given an integer `num`, return _a string of its **base 7** representation_.
> Input: num = 100
> Output: "202"
> Input: num = -7
> Output: "-10"
```
public String convertToBase7(int num) {
if (num == 0) {
return "0";
}
boolean isNegative = num < 0;
num = Math.abs(num);
StringBuilder base7 = new StringBuilder();
while (num > 0) {
base7.append(num % 7);
num /= 7;
}
if (isNegative) {
base7.append("-");
}
return base7.reverse().toString();
}
}
```
#
```
boolean isNegative = num < 0;
num = Math.abs(num);
StringBuilder base7 = new StringBuilder();
```
isNegative 변수를 사용하여 주어진 정수가 음수인지를 확인합니다. 음수인 경우 절대값으로 변환합니다.
```
if (num == 0) {
return "0";
}
```
주어진 정수가 0이면 바로 "0"을 반환합니다.
```
while (num > 0) {
base7.append(num % 7);
num /= 7;
}
```
정수를 7로 나눈 나머지를 StringBuilder에 추가합니다.
정수를 7로 …
=> [504] Base 7

dlek-user/[506] Relative Ranks
ou are given an integer array `score` of size `n`, where `score[i]` is the score of the `ith` athlete in a competition. All the scores are guaranteed to be **unique**.
The athletes are **placed** based on their scores, where the `1st` place athlete has the highest score, the `2nd` place athlete has the `2nd` highest score, and so on. The placement of each athlete determines their rank:
- The `1st` place athlete's rank is `"Gold Medal"`.
- The `2nd` place athlete's rank is `"Silver Medal"`.
- The `3rd` place athlete's rank is `"Bronze Medal"`.
- For the `4th` place to the `nth` place athlete, their rank is their placement number (i.e., the `xth` place athlete's rank is `"x"`).
Return an array `answer` of size `n` where `answer[i]` is the rank of the `ith` athlete.
> Input: score = …
=> [506] Relative Ranks

dlek-user/[507] Perfect Number
A [perfect number](https://en.wikipedia.org/wiki/Perfect_number) is a **positive integer** that is equal to the sum of its **positive divisors**, excluding the number itself. A **divisor** of an integer `x` is an integer that can divide `x` evenly.
Given an integer `n`, return `true` _if_ `n` _is a perfect number, otherwise return_ `false`.
> Input: num = 28
> Output: true
> Explanation: 28 = 1 + 2 + 4 + 7 + 14
> 1, 2, 4, 7, and 14 are all divisors of 28.
> Input: num = 7
```
public boolean checkPerfectNumber(int num) {
if (num <= 1) {
return false;
}
int sum = 1;
int sqrt = (int) Math.sqrt(num);
for (int i = 2; i <= sqrt; i++) {
if (num % i == 0) {
sum += i;
if (i != num / i) {
sum += num / i;
}
}
}
return sum == num;
}
}
```
#
```
if (num <= 1) {
return …
```
=> [507] Perfect Number

dlek-user/[509] Fibonacci Number
The **Fibonacci numbers**, commonly denoted `F(n)` form a sequence, called the Fibonacci sequence, such that each number is the sum of the two preceding ones, starting from `0` and `1`. That is,
> F(0) = 0, F(1) = 1
> F(n) = F(n - 1) + F(n - 2), for n > 1.
Given `n`, calculate `F(n)`.
> Input: n = 2
> Output: 1
> Explanation: F(2) = F(1) + F(0) = 1 + 0 = 1.
> Input: n = 3
> Output: 2
> Explanation: F(3) = F(2) + F(1) = 1 + 1 = 2.
> Input: n = 4
> Output: 3
> Explanation: F(4) = F(3) + F(2) = 2 + 1 = 3.
```
public int fib(int n) {
if (n <= 1) {
return n;
}
dp[0] = 0;
dp[1] = 1;
for (int i = 2; i <= n; i++) {
dp[i] = dp[i - 1] + dp[i - 2];
}
return dp[n];
}
}
```
#
```
if (n <= 1) {
return n;
}
```
if (n <= 1) 조건문은 기저 조건(base case)을 정의합니다. 피보나치 …
=> [509] Fibonacci Number

dlek-user/[520] Detect Capital
We define the usage of capitals in a word to be right when one of the following cases holds:
- All letters in this word are capitals, like `"USA"`.
- All letters in this word are not capitals, like `"leetcode"`.
- Only the first letter in this word is capital, like `"Google"`.
Given a string `word`, return `true` if the usage of capitals in it is right.
> Input: word = "USA"
> Output: true
> Input: word = "FlaG"
```
public boolean detectCapitalUse(String word) {
int n = word.length();
int capitalCount = 0;
if (Character.isUpperCase(word.charAt(i))) {
capitalCount++;
}
}
if (capitalCount == n || capitalCount == 0 || (capitalCount == 1 && Character.isUpperCase(word.charAt(0)))) {
return true;
}
return false;
}
}
```
#
```
int n …
```
=> dlek-user-102

dlek-user/[521] Longest Uncommon Subsequence 1
Given two strings `a` and `b`, return _the length of the **longest uncommon subsequence** between_ `a` _and_ `b`. _If no such uncommon subsequence exists, return_ `-1`.
An **uncommon subsequence** between two strings is a string that is a subsequence **of exactly one of them**.
> Input: a = "aba", b = "cdc"
> Output: 3
> Explanation: One longest uncommon subsequence is "aba" because "aba" is a subsequence of "aba" but not "cdc".
> Note that "cdc" is also a longest uncommon subsequence.
> Input: a = "aaa", b = "bbb"
> Output: 3
> Explanation: The longest uncommon subsequences are "aaa" and "bbb".
> Input: a = "aaa", b = "aaa"
> Output: -1
> Explanation: Every subsequence of string a is also a subsequence of string b. Similarly, every subsequence of string b is also a subsequence of string …
=> [521] Longest Uncommon Subsequence 1

dlek-user/[530] Minimum Absolute Difference in BST
Given the `root` of a Binary Search Tree (BST), return _the minimum absolute difference between the values of any two different nodes in the tree_.
> Input: root = [4,2,6,1,3]
> Output: 1
> Input: root = [1,0,48,null,null,12,49]
> Output: 1
```
class TreeNode {
int val;
TreeNode left;
TreeNode right;
TreeNode(int x) { val = x; }
}
private Integer prev;
private int minDiff;
public int getMinimumDifference(TreeNode root) {
prev = null;
minDiff = Integer.MAX_VALUE;
inorder(root);
return minDiff;
}
private void inorder(TreeNode node) {
return;
}
inorder(node.left);
if (prev != null) {
minDiff = Math.min(minDiff, node.val - prev);
}
prev = node.val;
inorder(node.right);
}
}
```
#
```
class TreeNode {
int val;
TreeNode left;
TreeNode right;
TreeNode(int x) { …
```
=> [530] Minimum Absolute Difference in BST

dlek-user/[541] Reverse String 2
Given a string `s` and an integer `k`, reverse the first `k` characters for every `2k` characters counting from the start of the string.
If there are fewer than `k` characters left, reverse all of them. If there are less than `2k` but greater than or equal to `k` characters, then reverse the first `k` characters and leave the other as original.
> Input: s = "abcdefg", k = 2
> Output: "bacdfeg"
> Input: s = "abcd", k = 2
> Output: "bacd"
```
public String reverseStr(String s, int k) {
char[] arr = s.toCharArray();
for (int i = 0; i < arr.length; i += 2 * k) {
int left = i;
int right = Math.min(i + k - 1, arr.length - 1);
char temp = arr[left];
arr[left] = arr[right];
arr[right] = temp;
left++;
right--;
}
}
return new String(arr);
}
}
```
#
```
char[] …
```
=> [541] Reverse String 2

dlek-user/[543] Diameter of Binary Tree
Given the `root` of a binary tree, return the length of the **diameter** of the tree.
The **diameter** of a binary tree is the **length** of the longest path between any two nodes in a tree. This path may or may not pass through the `root`.
The **length** of a path between two nodes is represented by the number of edges between them.
> Input: root = [1,2,3,4,5]
> Output: 3
> Explanation: 3 is the length of the path [4,2,1,3] or [5,2,1,3].
> Input: root = [1,2]
> Output: 1
```
private int maxDiameter = 0;
public int diameterOfBinaryTree(TreeNode root) {
calculateDepth(root);
return maxDiameter;
}
private int calculateDepth(TreeNode node) {
return 0;
}
int leftDepth = calculateDepth(node.left);
int rightDepth = calculateDepth(node.right);
int …
```
=> [543] Diameter of Binary Tree

dlek-user/[551] Student Attendance Record
You are given a string `s` representing an attendance record for a student where each character signifies whether the student was absent, late, or present on that day. The record only contains the following three characters:
- `'A'`: Absent.
- `'L'`: Late.
- `'P'`: Present.
The student is eligible for an attendance award if they meet **both** of the following criteria:
- The student was absent (`'A'`) for **strictly** fewer than 2 days **total**.
- The student was never late (`'L'`) for 3 or more **consecutive** days.
Return `true` _if the student is eligible for an attendance award, or_ `false` _otherwise_.
> Input: s = "PPALLP"
> Output: true
> Explanation: The student has fewer than 2 absences and was never late 3 or more consecutive days.
> Input: s = "PPALLL"
> …
=> [551] Student Attendance Record

dlek-user/[557] Reverse Words in a String 3
Given a string `s`, reverse the order of characters in each word within a sentence while still preserving whitespace and initial word order.
> Input: s = "Let's take LeetCode contest"
> Output: "s'teL ekat edoCteeL tsetnoc"
> Input: s = "Mr Ding"
> Output: "rM gniD"
```
public String reverseWords(String s) {
String[] words = s.split(" ");
StringBuilder result = new StringBuilder();
for (String word : words) {
StringBuilder reversedWord = new StringBuilder(word);
result.append(reversedWord.reverse().toString()).append(" ");
}
return result.toString().trim();
}
}
```
#
```
String[] words = s.split(" ");
```
문자열 s를 공백 " "을 기준으로 단어 배열로 분리합니다.
```
StringBuilder result = new StringBuilder();
for (String word : words) {
StringBuilder reversedWord = new StringBuilder(word); …
```
=> [557] Reverse Words in a String 3

dlek-user/[559] Maximum Depth of N-ary Tree
Given a n-ary tree, find its maximum depth.
The maximum depth is the number of nodes along the longest path from the root node down to the farthest leaf node.
_Nary-Tree input serialization is represented in their level order traversal, each group of children is separated by the null value (See examples)._
> Input: root = [1,null,3,2,4,null,5,6]
> Output: 3
> Input: root = [1,null,2,3,4,5,null,null,6,7,null,8,null,9,10,null,null,11,null,12,null,13,null,null,14]
> Output: 5
```
public int maxDepth(Node root) {
return 0;
}
int maxDepth = 0;
for (Node child : root.children) {
maxDepth = Math.max(maxDepth, maxDepth(child));
}
return maxDepth + 1;
}
}
```
#
```
return 0;
}
```
루트 노드가 null인 경우 0을 반환합니다.
```
int maxDepth = 0;
for (Node …
```
=> [559] Maximum Depth of N-ary Tree

dlek-user/[561] Array Partition
Given an integer array `nums` of `2n` integers, group these integers into `n` pairs `(a1, b1), (a2, b2), ..., (an, bn)` such that the sum of `min(ai, bi)` for all `i` is maximized. Return the maximized sum.
> Input: nums = [1,4,3,2]
> Output: 4
> Explanation: All possible pairings (ignoring the ordering of elements) are:
> 1. (1, 4), (2, 3) -> min(1, 4) + min(2, 3) = 1 + 2 = 3
> 2. (1, 3), (2, 4) -> min(1, 3) + min(2, 4) = 1 + 2 = 3
> 3. (1, 2), (3, 4) -> min(1, 2) + min(3, 4) = 1 + 3 = 4
> So the maximum possible sum is 4.
> Input: nums = [6,2,6,5,1,2]
> Output: 9
> Explanation: The optimal pairing is (2, 1), (2, 5), (6, 6). min(2, 1) + min(2, 5) + min(6, 6) = 1 + 2 + 6 = 9.
```
public int arrayPairSum(int[] nums) {
Arrays.sort(nums);
int maxSum = 0;
for (int i = 0; i < …
```
=> [561] Array Partition

dlek-user/[563] Binary Tree Tilt
Given the `root` of a binary tree, return _the sum of every tree node's **tilt**_.
The **tilt** of a tree node is the **absolute difference** between the sum of all left subtree node **values** and all right subtree node **values**. If a node does not have a left child, then the sum of the left subtree node **values** is treated as `0`. The rule is similar if the node does not have a right child.
> Input: root = [1,2,3]
> Output: 1
> Tilt of node 2 : |0-0| = 0 (no children)
> Tilt of node 3 : |0-0| = 0 (no children)
> Tilt of node 1 : |2-3| = 1 (left subtree is just left child, so sum is 2; right subtree is just right child, so sum is 3)
> Sum of every tilt : 0 + 0 + 1 = 1
> Input: root = [4,2,9,3,5,null,7]
> Output: 15
> Tilt of node 3 : |0-0| = 0 (no …
=> [563] Binary Tree Tilt

dlek-user/[566] Reshape the Matrix
In MATLAB, there is a handy function called `reshape` which can reshape an `m x n` matrix into a new one with a different size `r x c` keeping its original data.
You are given an `m x n` matrix `mat` and two integers `r` and `c` representing the number of rows and the number of columns of the wanted reshaped matrix.
The reshaped matrix should be filled with all the elements of the original matrix in the same row-traversing order as they were.
If the `reshape` operation with given parameters is possible and legal, output the new reshaped matrix; Otherwise, output the original matrix.
> Input: mat = [[1,2],[3,4]], r = 1, c = 4
> Output: [[1,2,3,4]]
> Input: mat = [[1,2],[3,4]], r = 2, c = 4
> Output: [[1,2],[3,4]]
```
public int[][] matrixReshape(int[][] mat, int r, int c) …
```
=> [566] Reshape the Matrix

dlek-user/[572] Subtree of Another Tree
Given the roots of two binary trees `root` and `subRoot`, return `true` if there is a subtree of `root` with the same structure and node values of `subRoot` and `false` otherwise.
A subtree of a binary tree `tree` is a tree that consists of a node in `tree` and all of this node's descendants. The tree `tree` could also be considered as a subtree of itself.
> Input: root = [3,4,5,1,2], subRoot = [4,1,2]
> Output: true
> Input: root = [3,4,5,1,2,null,null,null,null,0], subRoot = [4,1,2]
```
public boolean isSubtree(TreeNode root, TreeNode subRoot) {
return false;
}
return isSameTree(root, subRoot) || isSubtree(root.left, subRoot) || isSubtree(root.right, subRoot);
}
private boolean isSameTree(TreeNode s, TreeNode t) {
if (s == null && t …
```
=> [572] Subtree of Another Tree

dlek-user/[575] Distribute Candies
Alice has `n` candies, where the `ith` candy is of type `candyType[i]`. Alice noticed that she started to gain weight, so she visited a doctor.
The doctor advised Alice to only eat `n / 2` of the candies she has (`n` is always even). Alice likes her candies very much, and she wants to eat the maximum number of different types of candies while still following the doctor's advice.
Given the integer array `candyType` of length `n`, return _the **maximum** number of different types of candies she can eat if she only eats_ `n / 2` _of them_.
> Input: candyType = [1,1,2,2,3,3]
> Output: 3
> Explanation: Alice can only eat 6 / 2 = 3 candies. Since there are only 3 types, she can eat one of each type.
> Input: candyType = [1,1,2,3]
> Output: 2
> Explanation: Alice can only eat 4 / 2 = 2 candies. …
=> [575] Distribute Candies

dlek-user/[589] N-ary Tree Preorder Traversal
Given the `root` of an n-ary tree, return _the preorder traversal of its nodes' values_.
Nary-Tree input serialization is represented in their level order traversal. Each group of children is separated by the null value (See examples)
> Input: root = [1,null,3,2,4,null,5,6]
> Output: [1,3,5,6,2,4]
> Input: root = [1,null,2,3,4,5,null,null,6,7,null,8,null,9,10,null,null,11,null,12,null,13,null,null,14]
> Output: [1,2,3,6,7,11,14,4,8,12,5,9,13,10]
```
public List<Integer> preorder(Node root) {
preorderHelper(root, result);
return result;
}
private void preorderHelper(Node node, List<Integer> result) {
return;
}
result.add(node.val);
for (Node child : node.children) {
preorderHelper(child, result);
}
}
}
```
#
``` …
```
=> [589] N-ary Tree Preorder Traversal

dlek-user/[590] N-ary Tree Postorder Traversal
Given the `root` of an n-ary tree, return _the postorder traversal of its nodes' values_.
Nary-Tree input serialization is represented in their level order traversal. Each group of children is separated by the null value (See examples)
> Input: root = [1,null,3,2,4,null,5,6]
> Output: [5,6,3,2,4,1]
> Input: root = [1,null,2,3,4,5,null,null,6,7,null,8,null,9,10,null,null,11,null,12,null,13,null,null,14]
> Output: [2,6,14,11,7,3,12,8,4,13,9,10,5,1]
```
public List<Integer> postorder(Node root) {
postorderHelper(root, result);
return result;
}
private void postorderHelper(Node node, List<Integer> result) {
return;
}
for (Node child : node.children) {
postorderHelper(child, result);
}
result.add(node.val);
}
}
``` …
=> [590] N-ary Tree Postorder Traversal

dlek-user/[594] Longest Harmonious Subsequence
We define a harmonious array as an array where the difference between its maximum value and its minimum value is **exactly** `1`.
Given an integer array `nums`, return _the length of its longest harmonious subsequence among all its possible subsequences_.
A **subsequence** of array is a sequence that can be derived from the array by deleting some or no elements without changing the order of the remaining elements.
> Input: nums = [1,3,2,2,5,2,3,7]
> Output: 5
> Explanation: The longest harmonious subsequence is [3,2,2,2,3].
> Output: 2
> Input: nums = [1,1,1,1]
> Output: 0
```
public int findLHS(int[] nums) {
// Step 1: Count frequencies of each number
Map<Integer, Integer> frequencyMap = new HashMap<>(); …
```
=> [594] Longest Harmonious Subsequence

dlek-user/[598] Range Addtion 2
You are given an `m x n` matrix `M` initialized with all `0`'s and an array of operations `ops`, where `ops[i] = [ai, bi]` means `M[x][y]` should be incremented by one for all `0 <= x < ai` and `0 <= y < bi`.
Count and return _the number of maximum integers in the matrix after performing all the operations_.
> Input: m = 3, n = 3, ops = [[2,2],[3,3]]
> Output: 4
> Explanation: The maximum integer in M is 2, and there are four of it in M. So return 4.
> Input: m = 3, n = 3, ops = [[2,2],[3,3],[3,3],[3,3],[2,2],[3,3],[3,3],[3,3],[2,2],[3,3],[3,3],[3,3]]
> Output: 4
> Input: m = 3, n = 3, ops = []
> Output: 9
```
public int maxCount(int m, int n, int[][] ops) {
int minRow = m;
int minCol = n;
for (int[] op : ops) {
minRow = Math.min(minRow, op[0]);
minCol = Math.min(minCol, …
```
=> [598] Range Addtion 2

dlek-user/[599] Minimum Index Sum of Two Lists
Given two arrays of strings `list1` and `list2`, find the **common strings with the least index sum**.
A **common string** is a string that appeared in both `list1` and `list2`.
A **common string with the least index sum** is a common string such that if it appeared at `list1[i]` and `list2[j]` then `i + j` should be the minimum value among all the other **common strings**.
Return _all the **common strings with the least index sum**_. Return the answer in **any order**.
> Input: list1 = ["Shogun","Tapioca Express","Burger King","KFC"], list2 = ["Piatti","The Grill at Torrey Pines","Hungry Hunter Steakhouse","Shogun"]
> Output: ["Shogun"]
> Explanation: The only common string is "Shogun".
> Input: list1 = ["Shogun","Tapioca Express","Burger King","KFC"], list2 = ["KFC","Shogun","Burger …
=> [599] Minimum Index Sum of Two Lists

dlek-user/[605] Can Place Flowers
You have a long flowerbed in which some of the plots are planted, and some are not. However, flowers cannot be planted in **adjacent** plots.
Given an integer array `flowerbed` containing `0`'s and `1`'s, where `0` means empty and `1` means not empty, and an integer `n`, return `true` if `n` _new flowers can be planted in the_ `flowerbed` _without violating the no-adjacent-flowers rule and_ `false` _otherwise_.
> Input: flowerbed = [1,0,0,0,1], n = 1
> Output: true
> Input: flowerbed = [1,0,0,0,1], n = 2
```
public boolean canPlaceFlowers(int[] flowerbed, int n) {
int length = flowerbed.length;
for (int i = 0; i < length && n > 0; i++) {
if (flowerbed[i] == 0) {
boolean emptyPrev = (i == 0) || (flowerbed[i - 1] == 0);
boolean emptyNext = (i == length - 1) …
```
=> [605] Can Place Flowers

dlek-user/[617] Merge Two Binary Trees
You are given two binary trees `root1` and `root2`.
Imagine that when you put one of them to cover the other, some nodes of the two trees are overlapped while the others are not. You need to merge the two trees into a new binary tree. The merge rule is that if two nodes overlap, then sum node values up as the new value of the merged node. Otherwise, the NOT null node will be used as the node of the new tree.
Return _the merged tree_.
**Note**: The merging process must start from the root nodes of both trees.
> Input: root1 = [1,3,2,5], root2 = [2,1,3,null,4,null,7]
> Output: [3,4,5,5,4,null,7]
> Input: root1 = [1], root2 = [1,2]
> Output: [2,2]
> 
```
public TreeNode mergeTrees(TreeNode root1, TreeNode root2) {
if (root1 == null && root2 == null) {
return null;
}
if …
```
=> [617] Merge Two Binary Trees

dlek-user/[628] Maximum Product of Three Numbers
Given an integer array `nums`, _find three numbers whose product is maximum and return the maximum product_.
> Output: 6
> Output: 24
> Input: nums = [-1,-2,-3]
> Output: -6
```
public int maximumProduct(int[] nums) {
Arrays.sort(nums);
int max1 = nums[n - 1] * nums[n - 2] * nums[n - 3];
int max2 = nums[0] * nums[1] * nums[n - 1];
return Math.max(max1, max2);
}
}
```
#
```
Arrays.sort(nums);
```
Arrays.sort(nums)로 배열을 오름차순으로 정렬합니다.
```
int max1 = nums[n - 1] * nums[n - 2] * nums[n - 3];
```
nums[n - 1] * nums[n - 2] * nums[n - 3]는 배열에서 가장 큰 세 수의 곱입니다.
```
int max2 = nums[0] * nums[1] * nums[n - 1];
```
nums[0] * nums[1] * nums[n - 1]는 배열에서 가장 작은 두 수(음수일 가능성이 큼)와 가장 큰 수의 곱입니다.
``` …
```
=> [628] Maximum Product of Three Numbers

dlek-user/[637] Average of Levels in Binary Tree
Given the `root` of a binary tree, return _the average value of the nodes on each level in the form of an array_. Answers within `10-5` of the actual answer will be accepted.
> Output: [3.00000,14.50000,11.00000]
> Explanation: The average value of nodes on level 0 is 3, on level 1 is 14.5, and on level 2 is 11.
> Hence return [3, 14.5, 11].
> Input: root = [3,9,20,15,7]
> Output: [3.00000,14.50000,11.00000]
```
public class Solution {
public List<Double> averageOfLevels(TreeNode root) {
List<Double> result = new ArrayList<>();
if (root == null) return result;
queue.offer(root);
int levelSize = queue.size();
double sum = 0.0;
for (int i = 0; i < levelSize; i++) {
TreeNode node = …
```
=> [637] Average of Levels in Binary Tree

dlek-user/[643] Maximum Average Subarray 1
You are given an integer array nums consisting of `n` elements, and an integer `k`.
Find a contiguous subarray whose **length is equal to** `k` that has the maximum average value and return this value. Any answer with a calculation error less than `10-5` will be accepted.
> Input: nums = [1,12,-5,-6,50,3], k = 4
> Output: 12.75000
> Explanation: Maximum average is (12 - 5 - 6 + 50) / 4 = 51 / 4 = 12.75
> Input: nums = [5], k = 1
> Output: 5.00000
```
public double findMaxAverage(int[] nums, int k) {
int sum = 0;
for (int i = 0; i < k; i++) {
sum += nums[i];
}
int max_sum = sum;
for (int i = k; i < nums.length; i++) {
sum = sum - nums[i - k] + nums[i];
max_sum = Math.max(max_sum, sum);
}
return (double) max_sum / k;
}
}
```
#
```
int sum = 0;
for (int i = 0; i < k; i++) { …
```
=> [643] Maximum Average Subarray 1

dlek-user/[645] Set Mismatch
You have a set of integers `s`, which originally contains all the numbers from `1` to `n`. Unfortunately, due to some error, one of the numbers in `s` got duplicated to another number in the set, which results in **repetition of one** number and **loss of another** number.
You are given an integer array `nums` representing the data status of this set after the error.
Find the number that occurs twice and the number that is missing and return _them in the form of an array_.
> Input: nums = [1,2,2,4]
> Output: [2,3]
> Input: nums = [1,1]
> Output: [1,2]
```
public int[] findErrorNums(int[] nums) {
int[] count = new int[n + 1];
count[num]++;
}
int duplicate = -1, missing = -1;
for (int i = 1; i <= n; i++) {
if (count[i] == 2) { …
```
=> [645] Set Mismatch

dlek-user/[653] Two Sum 5 - Input is a BST
Given the `root` of a binary search tree and an integer `k`, return `true` _if there exist two elements in the BST such that their sum is equal to_ `k`, _or_ `false` _otherwise_.
> Input: root = [5,3,6,2,4,null,7], k = 9
> Output: true
> Input: root = [5,3,6,2,4,null,7], k = 28
```
public boolean findTarget(TreeNode root, int k) {
List<Integer> nums = new ArrayList<>();
inorder(root, nums);
int left = 0, right = nums.size() - 1;
int sum = nums.get(left) + nums.get(right);
if (sum == k) {
return true;
} else if (sum < k) {
left++;
} else {
right--;
}
}
return false;
}
private void inorder(TreeNode root, List<Integer> nums) {
if (root == null) return;
inorder(root.left, nums);
nums.add(root.val);
inorder(root.right, nums);
}
}
```
# …
=> [653] Two Sum 5 - Input is a BST

dlek-user/[657] Robot Return to Origin
There is a robot starting at the position `(0, 0)`, the origin, on a 2D plane. Given a sequence of its moves, judge if this robot ends up at `(0, 0)` after it completes its moves.
You are given a string `moves` that represents the move sequence of the robot where `moves[i]` represents its `ith` move. Valid moves are `'R'` (right), `'L'` (left), `'U'` (up), and `'D'` (down).
Return `true` _if the robot returns to the origin after it finishes all of its moves, or_ `false` _otherwise_.
**Note**: The way that the robot is "facing" is irrelevant. `'R'` will always make the robot move to the right once, `'L'` will always make it move left, etc. Also, assume that the magnitude of the robot's movement is the same for each move.
> Input: moves = "UD"
> Output: true
> Explanation: The robot moves …
=> [657] Robot Return to Origin

dlek-user/[671] Second Minimum Node In a Binary Tree
Given a non-empty special binary tree consisting of nodes with the non-negative value, where each node in this tree has exactly `two` or `zero` sub-node. If the node has two sub-nodes, then this node's value is the smaller value among its two sub-nodes. More formally, the property `root.val = min(root.left.val, root.right.val)` always holds.
Given such a binary tree, you need to output the **second minimum** value in the set made of all the nodes' value in the whole tree.
If no such second minimum value exists, output -1 instead.
> Input: root = [2,2,5,null,null,5,7]
> Output: 5
> Explanation: The smallest value is 2, the second smallest value is 5.
> Input: root = [2,2,2]
> Output: -1
> Explanation: The smallest value is 2, but there isn't any second smallest value.
``` …
```
=> [671] Second Minimum Node In a Binary Tree

dlek-user/[680] Valid Palindrome 2
Given a string `s`, return `true` _if the_ `s` _can be palindrome after deleting **at most one** character from it._
> Input: s = "aba"
> Output: true
> Input: s = "abca"
> Output: true
> Explanation: You could delete the character 'c'.
> Input: s = "abc"
```
def validPalindrome(self, s):
"""
:type s: str
:rtype: bool
"""
def isPalindromeRange(left, right):
while left < right:
if s[left] != s[right]:
return False
left += 1
right -= 1
return True
left, right = 0, len(s) - 1
while left < right:
if s[left] != s[right]:
return isPalindromeRange(left + 1, right) or isPalindromeRange(left, right - 1)
left += 1
right -= 1
return True
```
#
```
def isPalindromeRange(left, right):
while left < right:
if s[left] != s[right]:
return False
left += 1
right -= 1 …
```
=>  [680] Valid Palindrome 2

dlek-user/[682] Baseball Game
You are keeping the scores for a baseball game with strange rules. At the beginning of the game, you start with an empty record.
You are given a list of strings `operations`, where `operations[i]` is the `ith` operation you must apply to the record and is one of the following:
- An integer `x`.
- Record a new score of `x`.
- '+'.
- Record a new score that is the sum of the previous two scores.
- 'D'.
- Record a new score that is the double of the previous score.
- 'C'.
- Invalidate the previous score, removing it from the record.
Return _the sum of all the scores on the record after applying all the operations_.
The test cases are generated such that the answer and all intermediate calculations fit in a **32-bit** integer and that all operations are valid.
> Input: ops = …
=> [682] Baseball Game

dlek-user/[693] Binary Number with Alternating Bits
Given a positive integer, check whether it has alternating bits: namely, if two adjacent bits will always have different values.
> Input: n = 5
> Output: true
> Explanation: The binary representation of 5 is: 101
> Input: n = 7
> Explanation: The binary representation of 7 is: 111.
> Input: n = 11
> Explanation: The binary representation of 11 is: 1011.
```
def hasAlternatingBits(self, n):
"""
:type n: int
:rtype: bool
"""
xor = n ^ (n >> 1)
return (xor & (xor + 1)) == 0
```
#
```
xor = n ^ (n >> 1)
```
n과 n >> 1을 XOR 연산하면 인접한 비트가 다를 경우 1, 같을 경우 0이 됩니다.
예를 들어, 5 (101 in binary)와 5 >> 1 (010 in binary)를 XOR 연산하면 111이 됩니다. 이는 모든 인접한 비트가 다름을 나타냅니다.
```
return (xor & (xor + 1)) == 0
```
XOR 결과에 1을 더하면 모든 비트가 0이 되는지 확인합니다. 만약 XOR 결과가 …
=> [693] Binary Number with Alternating Bits

dlek-user/[697] Degree of an Array
Given a non-empty array of non-negative integers `nums`, the **degree** of this array is defined as the maximum frequency of any one of its elements.
Your task is to find the smallest possible length of a (contiguous) subarray of `nums`, that has the same degree as `nums`.
> Input: nums = [1,2,2,3,1]
> Output: 2
> The input array has a degree of 2 because both elements 1 and 2 appear twice.
> Of the subarrays that have the same degree:
> [1, 2, 2, 3, 1], [1, 2, 2, 3], [2, 2, 3, 1], [1, 2, 2], [2, 2, 3], [2, 2]
> The shortest length is 2. So return 2.
> Input: nums = [1,2,2,3,1,4,2]
> Output: 6
> The degree is 3 because the element 2 is repeated 3 times.
> So [2,2,3,1,4,2] is the shortest subarray, therefore returning 6.
```
def …
```
=> [697] Degree of an Array

dlek-user/[700] Search in a Binary Search Tree
You are given the `root` of a binary search tree (BST) and an integer `val`.
Find the node in the BST that the node's value equals `val` and return the subtree rooted with that node. If such a node does not exist, return `null`.
> Input: root = [4,2,7,1,3], val = 2
> Output: [2,1,3]
> Input: root = [4,2,7,1,3], val = 5
> Output: []
```
def searchBST(self, root, val):
current = root
while current is not None:
if current.val == val:
return current
elif val < current.val:
current = current.left
else:
current = current.right
return None
```
#
```
if current.val == val:
return current
```
현재 노드의 값이 찾는 값과 같으면 현재 노드를 반환
```
elif val < current.val:
current = current.left
```
찾는 값이 현재 노드의 값보다 작으면 왼쪽 서브트리로 이동
```
else:
current = current.right
```
찾는 값이 현재 노드의 값보다 크면 오른쪽 …
=> [700] Search in a Binary Search Tree

dlek-user/[703] Kth Largest Element in a Stream
You are part of a university admissions office and need to keep track of the `kth` highest test score from applicants in real-time. This helps to determine cut-off marks for interviews and admissions dynamically as new applicants submit their scores.
You are tasked to implement a class which, for a given integer `k`, maintains a stream of test scores and continuously returns the `k`th highest test score **after** a new score has been submitted. More specifically, we are looking for the `k`th highest score in the sorted list of all scores.
Implement the `KthLargest` class:
- `KthLargest(int k, int[] nums)` Initializes the object with the integer `k` and the stream of test scores `nums`.
- `int add(int val)` Adds a new test score `val` to the stream and returns the element representing the …
=> [703] Kth Largest Element in a Stream

dlek-user/[704] Binary Search
Given an array of integers `nums` which is sorted in ascending order, and an integer `target`, write a function to search `target` in `nums`. If `target` exists, then return its index. Otherwise, return `-1`.
You must write an algorithm with `O(log n)` runtime complexity.
> Input: nums = [-1,0,3,5,9,12], target = 9
> Output: 4
> Explanation: 9 exists in nums and its index is 4
> Input: nums = [-1,0,3,5,9,12], target = 2
> Output: -1
> Explanation: 2 does not exist in nums so return -1
```
def search(self, nums, target):
left, right = 0, len(nums) - 1
while left <= right:
mid = left + (right - left) // 2
if nums[mid] == target:
return mid
elif nums[mid] > target:
right = mid - 1
else:
left = mid + 1
return -1
```
#
```
left, right = 0, len(nums) - 1
```
left와 right …
=> [704] Binary Search

dlek-user/[706] Design HashMap
Design a HashMap without using any built-in hash table libraries.
Implement the `MyHashMap` class:
- `MyHashMap()` initializes the object with an empty map.
- `void put(int key, int value)` inserts a `(key, value)` pair into the HashMap. If the `key` already exists in the map, update the corresponding `value`.
- `int get(int key)` returns the `value` to which the specified `key` is mapped, or `-1` if this map contains no mapping for the `key`.
- `void remove(key)` removes the `key` and its corresponding `value` if the map contains the mapping for the `key`.
-  
> Input
> ["MyHashMap", "put", "put", "get", "get", "put", "get", "remove", "get"]
> [[], [1, 1], [2, 2], [1], [3], [2, 1], [2], [2], [2]]
> Output
> [null, null, null, 1, -1, null, 1, null, -1]
> 
> Explanation
> MyHashMap …
=> [706] Design HashMap

dlek-user/[709] To Lower Case
Given a string `s`, return _the string after replacing every uppercase letter with the same lowercase letter._
> Input: s = "Hello"
> Output: "hello"
> Input: s = "here"
> Output: "here"
> Input: s = "LOVELY"
> Output: "lovely"
```
public String toLowerCase(String s) {
return s.toLowerCase();
}
}
```
#
```
return s.toLowerCase();
```
자바에서 문자열의 대문자를 소문자로 변환하는 기본 메서드입니다. 이 메서드는 새로운 문자열을 반환하며, 원본 문자열은 변경되지 않습니다.
입력으로 받은 문자열 s에서 대문자가 있으면, 그 대문자를 소문자로 변환합니다. 만약 소문자이거나 숫자, 특수 문자가 포함되어 있으면 그대로 유지됩니다.
=> [709] To Lower Case

dlek-user/[717] 1-bit and 2-bit Characters
We have two special characters:
- The first character can be represented by one bit `0`.
- The second character can be represented by two bits (`10` or `11`).
Given a binary array `bits` that ends with `0`, return `true` if the last character must be a one-bit character.
> Input: bits = [1,0,0]
> Output: true
> Explanation: The only way to decode it is two-bit character and one-bit character.
> So the last character is one-bit character.
> Input: bits = [1,1,1,0]
> Explanation: The only way to decode it is two-bit character and two-bit character.
> So the last character is not one-bit character.
```
public boolean isOneBitCharacter(int[] bits) {
int i = 0;
while (i < bits.length - 1) {
if (bits[i] == 1) {
i += 2;
} 
else {
i += 1;
}
}
return i == …
```
=> [717] 1-bit and 2-bit Characters

dlek-user/[728] Self Dividing Numbers
A **self-dividing number** is a number that is divisible by every digit it contains.
- For example, `128` is **a self-dividing number** because `128 % 1 == 0`, `128 % 2 == 0`, and `128 % 8 == 0`.
A **self-dividing number** is not allowed to contain the digit zero.
Given two integers `left` and `right`, return a list of all the _**self-dividing numbers** in the range_ `[left, right]` (both **inclusive**).
> 
> Input: left = 1, right = 22
> Output: [1,2,3,4,5,6,7,8,9,11,12,15,22]
> Input: left = 47, right = 85
> Output: [48,55,66,77]
```
public List<Integer> selfDividingNumbers(int left, int right) {
for (int i = left; i <= right; i++) {
if (isSelfDividing(i)) {
result.add(i);
}
}
return result;
}
public boolean isSelfDividing(int …
```
=> [728] Self Dividing Numbers

dlek-user/[733] Flood Fill
You are given an image represented by an `m x n` grid of integers `image`, where `image[i][j]` represents the pixel value of the image. You are also given three integers `sr`, `sc`, and `color`. Your task is to perform a **flood fill** on the image starting from the pixel `image[sr][sc]`.
To perform a **flood fill**:
1. Begin with the starting pixel and change its color to `color`.
2. Perform the same process for each pixel that is **directly adjacent** (pixels that share a side with the original pixel, either horizontally or vertically) and shares the **same color** as the starting pixel.
3. Keep **repeating** this process by checking neighboring pixels of the _updated_ pixels and modifying their color if it matches the original color of the starting pixel.
4. The process **stops** when …
=> [733] Flood Fill

dlek-user/[744] Find Smallest Letter Greater Than Target
You are given an array of characters `letters` that is sorted in **non-decreasing order**, and a character `target`. There are **at least two different** characters in `letters`.
Return _the smallest character in_ `letters` _that is lexicographically greater than_ `target`. If such a character does not exist, return the first character in `letters`.
> Input: letters = ["c","f","j"], target = "a"
> Output: "c"
> Explanation: The smallest character that is lexicographically greater than 'a' in letters is 'c'.
> Input: letters = ["c","f","j"], target = "c"
> Output: "f"
> Explanation: The smallest character that is lexicographically greater than 'c' in letters is 'f'.
> Input: letters = ["x","x","y","y"], target = "z"
> Output: "x"
> Explanation: There are no characters in letters that is …
=> [744] Find Smallest Letter Greater Than Target

dlek-user/[746] Min Cost Climbing Stairs
You are given an integer array `cost` where `cost[i]` is the cost of `ith` step on a staircase. Once you pay the cost, you can either climb one or two steps.
You can either start from the step with index `0`, or the step with index `1`.
Return _the minimum cost to reach the top of the floor_.
> Input: cost = [10,15,20]
> Output: 15
> Explanation: You will start at index 1.
> - Pay 15 and climb two steps to reach the top.
> The total cost is 15.
> Input: cost = [1,100,1,1,1,100,1,1,100,1]
> Output: 6
> Explanation: You will start at index 0.
> - Pay 1 and climb two steps to reach index 2.
> - Pay 1 and climb two steps to reach index 4.
> - Pay 1 and climb two steps to reach index 6.
> - Pay 1 and climb one step to reach index 7.
> - Pay 1 and climb two steps to reach index 9.
> - Pay 1 and …
=> [746] Min Cost Climbing Stairs

dlek-user/[747] Largest Number At Least Twice of Others
You are given an integer array `nums` where the largest integer is **unique**.
Determine whether the largest element in the array is **at least twice** as much as every other number in the array. If it is, return _the_ **index** _of the largest element, or return_ `-1` _otherwise_.
> Input: nums = [3,6,1,0]
> Output: 1
> Explanation: 6 is the largest integer.
> For every other number in the array x, 6 is at least twice as big as x.
> The index of value 6 is 1, so we return 1.
> Output: -1
> Explanation: 4 is less than twice the value of 3, so we return -1.
```
public int dominantIndex(int[] nums) {
if (nums.length == 0) return -1;
int max = nums[0];
int maxIndex = 0;
for (int i = 1; i < nums.length; i++) {
if (nums[i] > max) {
max = nums[i]; …
```
=> [747] Largest Number At Least Twice of Others

dlek-user/[748] Shortest Completing Word
Given a string `licensePlate` and an array of strings `words`, find the **shortest completing** word in `words`.
A **completing** word is a word that **contains all the letters** in `licensePlate`. **Ignore numbers and spaces** in `licensePlate`, and treat letters as **case insensitive**. If a letter appears more than once in `licensePlate`, then it must appear in the word the same number of times or more.
For example, if `licensePlate`` = "aBc 12c"`, then it contains letters `'a'`, `'b'` (ignoring case), and `'c'` twice. Possible **completing** words are `"abccdef"`, `"caaacab"`, and `"cbca"`.
Return _the shortest **completing** word in_ `words`. It is guaranteed an answer exists. If there are multiple shortest **completing** words, return the **first** one that occurs in `words`.
> …
=> [748] Shortest Completing Word

dlek-user/[766] Toeplitz Matrix
Given an `m x n` `matrix`, return `true` _if the matrix is Toeplitz. Otherwise, return `false`._
A matrix is **Toeplitz** if every diagonal from top-left to bottom-right has the same elements.
> Input: matrix = [[1,2,3,4],[5,1,2,3],[9,5,1,2]]
> Output: true
> Explanation:
> In the above grid, the diagonals are:
> "[9]", "[5, 5]", "[1, 1, 1]", "[2, 2, 2]", "[3, 3]", "[4]".
> In each diagonal all elements are the same, so the answer is True.
> Input: matrix = [[1,2],[2,2]]
> Explanation:
> The diagonal "[1, 2]" has different elements.
```
public boolean isToeplitzMatrix(int[][] matrix) {
int rows = matrix.length;
int cols = matrix[0].length;
for (int i = 0; i < rows - 1; i++) {
for (int j = 0; j < cols - 1; j++) {
if (matrix[i][j] != matrix[i+1][j+1]) { …
```
=> [766] Toeplitz Matrix

dlek-user/[771] Jewels and Stones
You're given strings `jewels` representing the types of stones that are jewels, and `stones` representing the `stones` you have. Each character in stones is a type of stone you have. You want to know how many of the stones you have are also jewels.
Letters are case sensitive, so `"a"` is considered a different type of stone from `"A"`.
> Input: jewels = "aA", stones = "aAAbbbb"
> Output: 3
> Input: jewels = "z", stones = "ZZ"
> Output: 0
```
public int numJewelsInStones(String jewels, String stones) {
Set<Character> jewelSet = new HashSet<>();
for (char jewel : jewels.toCharArray()) {
jewelSet.add(jewel);
}
int count = 0;
for (char stone : stones.toCharArray()) {
if (jewelSet.contains(stone)) {
count++;
}
}
return count;
}
}
```
#
```
Set<Character> jewelSet = new …
```
=> [771] Jewels and Stones

dlek-user/[783] Minimum Distance Between BST Nodes
Given the `root` of a Binary Search Tree (BST), return _the minimum difference between the values of any two different nodes in the tree._
> Input: root = [4,2,6,1,3]
> Output: 1
> Input: root = [1,0,48,null,null,12,49]
> Output: 1
```
private int minDiff = Integer.MAX_VALUE;
private TreeNode prevNode = null;
public int minDiffInBST(TreeNode root) {
inOrderTraversal(root);
return minDiff;
}
private void inOrderTraversal(TreeNode node) {
if (node == null) return;
inOrderTraversal(node.left);
if (prevNode != null) {
int diff = node.val - prevNode.val;
minDiff = Math.min(minDiff, diff);
}
prevNode = node;
inOrderTraversal(node.right);
}
}
```
#
```
private int minDiff = Integer.MAX_VALUE;
```
두 노드 간의 최소 차이를 저장하는 변수입니다. 초기값을 Integer.MAX_VALUE로 설정하여 첫 번째 계산 시 최소 차이가 정상적으로 …
=> [783] Minimum Distance Between BST Nodes

dlek-user/[796] Rotate String
Given two strings `s` and `goal`, return `true` _if and only if_ `s` _can become_ `goal` _after some number of **shifts** on_ `s`.
A **shift** on `s` consists of moving the leftmost character of `s` to the rightmost position.
- For example, if `s = "abcde"`, then it will be `"bcdea"` after one shift.
> Input: s = "abcde", goal = "cdeab"
> Output: true
> Input: s = "abcde", goal = "abced"
```
public boolean rotateString(String s, String goal) {
if (s.length() != goal.length()) {
return false;
}
String doubledS = s + s;
return doubledS.contains(goal);
}
}
```
#
```
if (s.length() != goal.length()) {
return false;
}
```
만약 s와 goal의 길이가 다르다면, 아무리 "shift"를 해도 동일한 문자열이 될 수 없습니다. 따라서 이 경우 바로 false를 반환합니다.
```
String doubledS = s + s;
```
문자열 s를 두 번 연결합니다. 예를 들어, …
=> [796] Rotate String

dlek-user/[804] Unique Morse Code Words
International Morse Code defines a standard encoding where each letter is mapped to a series of dots and dashes, as follows:
- `'a'` maps to `".-"`,
- `'b'` maps to `"-..."`,
- `'c'` maps to `"-.-."`, and so on.
For convenience, the full table for the `26` letters of the English alphabet is given below:
[".-","-...","-.-.","-..",".","..-.","--.","....","..",".---","-.-",".-..","--","-.","---",".--.","--.-",".-.","...","-","..-","...-",".--","-..-","-.--","--.."]
Given an array of strings `words` where each word can be written as a concatenation of the Morse code of each letter.
For example, `"cab"` can be written as `"-.-..--..."`, which is the concatenation of `"-.-."`, `".-"`, and `"-..."`. We will call such a concatenation the transformation of a word.
Return _the number of different …
=> [804] Unique Morse Code Words

dlek-user/[806] Number of Lines To Write String
You are given a string `s` of lowercase English letters and an array `widths` denoting **how many pixels wide** each lowercase English letter is. Specifically, `widths[0]` is the width of `'a'`, `widths[1]` is the width of `'b'`, and so on.
You are trying to write `s` across several lines, where **each line is no longer than** `100` **pixels**. Starting at the beginning of `s`, write as many letters on the first line such that the total width does not exceed `100` pixels. Then, from where you stopped in `s`, continue writing as many letters as you can on the second line. Continue this process until you have written all of `s`.
_Return an array_ `result` _of length 2 where_:
- `result[0]` _is the total number of lines._
- `result[1]` _is the width of the last line in pixels._
> Input: …
=> [806] Number of Lines To Write String

dlek-user/[812] Largest Triangle Area
Given an array of points on the **X-Y** plane `points` where `points[i] = [xi, yi]`, return _the area of the largest triangle that can be formed by any three different points. Answers within_ `10-5` _of the actual answer will be accepted._
> Input: points = [[0,0],[0,1],[1,0],[0,2],[2,0]]
> Output: 2.00000
> Explanation: The five points are shown in the above figure. The red triangle is the largest.
> Input: points = [[1,0],[0,0],[0,1]]
> Output: 0.50000
```
public double largestTriangleArea(int[][] points) {
double maxArea = 0;
for (int i = 0; i < points.length; i++) {
for (int j = i + 1; j < points.length; j++) {
for (int k = j + 1; k < points.length; k++) {
double area = calculateArea(points[i], points[j], points[k]);
maxArea = Math.max(maxArea, area);
}
}
}
return …
```
=> [812] Largest Triangle Area

dlek-user/[819] Most Common Word
Given a string `paragraph` and a string array of the banned words `banned`, return _the most frequent word that is not banned_. It is **guaranteed** there is **at least one word** that is not banned, and that the answer is **unique**.
The words in `paragraph` are **case-insensitive** and the answer should be returned in **lowercase**.
> Input: paragraph = "Bob hit a ball, the hit BALL flew far after it was hit.", banned = ["hit"]
> Output: "ball"
> "hit" occurs 3 times, but it is a banned word.
> "ball" occurs twice (and no other word does), so it is the most frequent non-banned word in the paragraph. 
> Note that words in the paragraph are not case sensitive,
> that punctuation is ignored (even if adjacent to words, such as "ball,"), 
> and that "hit" isn't the answer …
=> [819] Most Common Word

dlek-user/[821] Shortest Distance to a Character
Given a string `s` and a character `c` that occurs in `s`, return _an array of integers_ `answer` _where_ `answer.length == s.length` _and_ `answer[i]` _is the **distance** from index_ `i` _to the **closest** occurrence of character_ `c` _in_ `s`.
The **distance** between two indices `i` and `j` is `abs(i - j)`, where `abs` is the absolute value function.
> Input: s = "loveleetcode", c = "e"
> Output: [3,2,1,0,1,0,0,1,2,2,1,0]
> Explanation: The character 'e' appears at indices 3, 5, 6, and 11 (0-indexed).
> The closest occurrence of 'e' for index 0 is at index 3, so the distance is abs(0 - 3) = 3.
> The closest occurrence of 'e' for index 1 is at index 3, so the distance is abs(1 - 3) = 2.
> For index 4, there is a tie between the 'e' at index 3 and the 'e' at index 5, but the distance …
=> [821] Shortest Distance to a Character

dlek-user/[824] Goat Latin
You are given a string `sentence` that consist of words separated by spaces. Each word consists of lowercase and uppercase letters only.
We would like to convert the sentence to "Goat Latin" (a made-up language similar to Pig Latin.) The rules of Goat Latin are as follows:
- If a word begins with a vowel (`'a'`, `'e'`, `'i'`, `'o'`, or `'u'`), append `"ma"` to the end of the word.
-  For example, the word `"apple"` becomes `"applema"`.
- If a word begins with a consonant (i.e., not a vowel), remove the first letter and append it to the end, then add `"ma"`.
- For example, the word `"goat"` becomes `"oatgma"`.
- Add one letter `'a'` to the end of each word per its word index in the sentence, starting with `1`.
- For example, the first word gets `"a"` added to the end, the second word gets …
=> [824] Goat Latin

dlek-user/[832] Flipping an Image
Given an `n x n` binary matrix `image`, flip the image **horizontally**, then invert it, and return _the resulting image._
To flip an image horizontally means that each row of the image is reversed.
- For example, flipping `[1,1,0]` horizontally results in `[0,1,1]`.
To invert an image means that each `0` is replaced by `1`, and each `1` is replaced by `0`.
- For example, inverting `[0,1,1]` results in `[1,0,0]`.
> Input: image = [[1,1,0],[1,0,1],[0,0,0]]
> Output: [[1,0,0],[0,1,0],[1,1,1]]
> Explanation: First reverse each row: [[0,1,1],[1,0,1],[0,0,0]].
> Then, invert the image: [[1,0,0],[0,1,0],[1,1,1]]
> Input: image = [[1,1,0,0],[1,0,0,1],[0,1,1,1],[1,0,1,0]]
> Output: [[1,1,0,0],[0,1,1,0],[0,0,0,1],[1,0,1,0]]
> Explanation: First reverse each row: …
=> [832] Flipping an Image

dlek-user/[844] Backspace String Compare
Given two strings `s` and `t`, return `true` _if they are equal when both are typed into empty text editors._ `'#'` means a backspace character.
Note that after backspacing an empty text, the text will continue empty.
> Input: s = "ab#c", t = "ad#c"
> Output: true
> Explanation: Both s and t become "ac".
> Input: s = "ab##", t = "c#d#"
> Output: true
> Explanation: Both s and t become "".
> Input: s = "a#c", t = "b"
> Explanation: s becomes "c" while t becomes "b".
```
private String buildFinalString(String str) {
Stack<Character> stack = new Stack<>();
for (char c : str.toCharArray()) {
if (c != '#') {
stack.push(c);
} else if (!stack.isEmpty()) {
stack.pop();
}
}
StringBuilder finalStr = new StringBuilder();
for (char c : stack) {
finalStr.append(c);
} …
```
=> [844] Backspace String Compare

dlek-user/[859] Buddy Strings
Given two strings `s` and `goal`, return `true` _if you can swap two letters in_ `s` _so the result is equal to_ `goal`, _otherwise, return_ `false`.
Swapping letters is defined as taking two indices `i` and `j` (0-indexed) such that `i != j` and swapping the characters at `s[i]` and `s[j]`.
- For example, swapping at indices `0` and `2` in `"abcd"` results in `"cbad"`.
> Input: s = "ab", goal = "ba"
> Output: true
> Explanation: You can swap s[0] = 'a' and s[1] = 'b' to get "ba", which is equal to goal.
> Input: s = "ab", goal = "ab"
> Explanation: The only letters you can swap are s[0] = 'a' and s[1] = 'b', which results in "ba" != goal.
> Input: s = "aa", goal = "aa"
> Output: true
> Explanation: You can swap s[0] = 'a' and s[1] = 'a' to get "aa", which is equal to …
=> [859] Buddy Strings

dlek-user/[860] Lemonade Change
At a lemonade stand, each lemonade costs `$5`. Customers are standing in a queue to buy from you and order one at a time (in the order specified by bills). Each customer will only buy one lemonade and pay with either a `$5`, `$10`, or `$20` bill. You must provide the correct change to each customer so that the net transaction is that the customer pays `$5`.
Note that you do not have any change in hand at first.
Given an integer array `bills` where `bills[i]` is the bill the `ith` customer pays, return `true` _if you can provide every customer with the correct change, or_ `false` _otherwise_.
> Input: bills = [5,5,5,10,20]
> Output: true
> From the first 3 customers, we collect three $5 bills in order.
> From the fourth customer, we collect a $10 bill and give back a $5.
> …
=> [860] Lemonade Change

dlek-user/[867] Transpose Matrix
Given a 2D integer array `matrix`, return _the transpose of_ `matrix`.
The **transpose** of a matrix is the matrix flipped over its main diagonal, switching the matrix's row and column indices.
> Input: matrix = [[1,2,3],[4,5,6],[7,8,9]]
> Output: [[1,4,7],[2,5,8],[3,6,9]]
> Input: matrix = [[1,2,3],[4,5,6]]
> Output: [[1,4],[2,5],[3,6]]
```
public int[][] transpose(int[][] matrix) {
int rows = matrix.length;
int cols = matrix[0].length;
int[][] transposed = new int[cols][rows];
for (int i = 0; i < rows; i++) {
for (int j = 0; j < cols; j++) {
transposed[j][i] = matrix[i][j];
}
}
return transposed;
}
}
```
#
```
int rows = matrix.length;
int cols = matrix[0].length;
```
matrix.length로 행의 개수, matrix[0].length로 열의 개수를 파악합니다.
```
int[][] transposed = new int[cols][rows];
``` …
=> [867] Transpose Matrix

dlek-user/[868] Binary Gap
Given a positive integer `n`, find and return _the **longest distance** between any two **adjacent**_ `1`_'s in the binary representation of_ `n`. _If there are no two adjacent_ `1`_'s, return_ `0`.
Two `1`'s are **adjacent** if there are only `0`'s separating them (possibly no `0`'s). The **distance** between two `1`'s is the absolute difference between their bit positions. For example, the two `1`'s in `"1001"` have a distance of 3.
> Input: n = 22
> Output: 2
> Explanation: 22 in binary is "10110".
> The first adjacent pair of 1's is "10110" with a distance of 2.
> The second adjacent pair of 1's is "10110" with a distance of 1.
> The answer is the largest of these two distances, which is 2.
> Note that "10110" is not a valid pair since there is a 1 separating the two 1's underlined.
> …
=> [868] Binary Gap

dlek-user/[872] Leaf-Similar Trees
Consider all the leaves of a binary tree, from left to right order, the values of those leaves form a **leaf value sequence**.
For example, in the given tree above, the leaf value sequence is `(6, 7, 4, 9, 8)`.
Two binary trees are considered leaf-similar if their leaf value sequence is the same.
Return `true` if and only if the two given trees with head nodes `root1` and `root2` are leaf-similar.
> Input: root1 = [3,5,1,6,2,9,8,null,null,7,4], root2 = [3,5,1,6,7,4,2,null,null,null,null,null,null,9,8]
> Output: true
> Input: root1 = [1,2,3], root2 = [1,3,2]
```
private void getLeafSequence(TreeNode node, List<Integer> leafSequence) {
return;
}
if (node.left == null && node.right == null) {
leafSequence.add(node.val);
} …
```
=> [872] Leaf-Similar Trees

dlek-user/[884] Uncommon Words from Two Sentences
A **sentence** is a string of single-space separated words where each word consists only of lowercase letters.
A word is **uncommon** if it appears exactly once in one of the sentences, and **does not appear** in the other sentence.
Given two **sentences** `s1` and `s2`, return _a list of all the **uncommon words**_. You may return the answer in **any order**.
> Input: s1 = "this apple is sweet", s2 = "this apple is sour"
> 
> Output: ["sweet","sour"]
> 
> Explanation:
> 
> The word "sweet" appears only in s1, while the word "sour" appears only in s2.
> Input: s1 = "apple apple", s2 = "banana"
> 
> Output: ["banana"]
```
public String[] uncommonFromSentences(String s1, String s2) {
String combined = s1 + " " + s2;
Map<String, Integer> wordCount = new HashMap<>();
for …
```
=> [884] Uncommon Words from Two Sentences

dlek-user/[888] Fair Candy Swap
Alice and Bob have a different total number of candies. You are given two integer arrays `aliceSizes` and `bobSizes` where `aliceSizes[i]` is the number of candies of the `ith` box of candy that Alice has and `bobSizes[j]` is the number of candies of the `jth` box of candy that Bob has.
Since they are friends, they would like to exchange one candy box each so that after the exchange, they both have the same total amount of candy. The total amount of candy a person has is the sum of the number of candies in each box they have.
Return _an integer array_ `answer` _where_ `answer[0]` _is the number of candies in the box that Alice must exchange, and_ `answer[1]` _is the number of candies in the box that Bob must exchange_. If there are multiple answers, you may **return any** one of them. It …
=> [888] Fair Candy Swap

dlek-user/[892] Monotonic Array
An array is **monotonic** if it is either monotone increasing or monotone decreasing.
An array `nums` is monotone increasing if for all `i <= j`, `nums[i] <= nums[j]`. An array nums is monotone decreasing if for all `i <= j`, `nums[i] >= nums[j]`.
Given an integer array `nums`, return `true` _if the given array is monotonic, or_ `false` _otherwise._
> Input: nums = [1,2,2,3]
> Output: true
> Input: nums = [6,5,4,4]
> Output: true
> Input: nums = [1,3,2]
```
public boolean isMonotonic(int[] nums) {
if (nums.length <= 2) {
return true;
}
boolean increasing = true; 
boolean decreasing = true;
for (int i = 1; i < nums.length; i++) {
if (nums[i] > nums[i - 1]) {
decreasing = false;
} else if (nums[i] < nums[i - 1]) {
increasing = false;
}
}
return increasing || …
```
=> [892] Monotonic Array

dlek-user/[897] Increasing Order Search Tree
Given the `root` of a binary search tree, rearrange the tree in **in-order** so that the leftmost node in the tree is now the root of the tree, and every node has no left child and only one right child.
> Input: root = [5,3,6,2,4,null,8,1,null,null,null,7,9]
> Output: [1,null,2,null,3,null,4,null,5,null,6,null,7,null,8,null,9]
> Input: root = [5,1,7]
> Output: [1,null,5,null,7]
```
public TreeNode increasingBST(TreeNode root) {
TreeNode dummy = new TreeNode(0);
TreeNode current = dummy;
inorderTraversal(root, current);
return dummy.right;
}
private TreeNode inorderTraversal(TreeNode node, TreeNode current) {
if (node == null) return current;
current = inorderTraversal(node.left, current);
node.left = null;
current.right = node;
current = node;
return …
```
=> [897] Increasing Order Search Tree

dlek-user/[905] Sort Array By Parity
Given an integer array `nums`, move all the even integers at the beginning of the array followed by all the odd integers.
Return _**any array** that satisfies this condition._
> Input: nums = [3,1,2,4]
> Output: [2,4,3,1]
> Explanation: The outputs [4,2,3,1], [2,4,1,3], and [4,2,1,3] would also be accepted.
> Input: nums = [0]
> Output: [0]
```
public int[] sortArrayByParity(int[] nums) {
int i = 0, j = nums.length - 1; 
while (i < j) {
if (nums[i] % 2 == 0) {
i++;
}
else if (nums[j] % 2 == 1) {
j--;
}
else {
int temp = nums[i];
nums[i] = nums[j];
nums[j] = temp;
i++;
j--;
}
}
return nums;
}
}
```
#
```
int i = 0, j = nums.length - 1;
```
i는 배열의 시작부터 시작하고, j는 배열의 끝에서 시작합니다.
```
if (nums[i] % 2 == 0) {
i++;
}
else if (nums[j] % 2 == 1) {
j--;
}
```
i 포인터가 짝수를 가리키면 i를 오른쪽으로 …
=> [905] Sort Array By Parity

dlek-user/[908] Smallest Range1
You are given an integer array `nums` and an integer `k`.
In one operation, you can choose any index `i` where `0 <= i < nums.length` and change `nums[i]` to `nums[i] + x` where `x` is an integer from the range `[-k, k]`. You can apply this operation **at most once** for each index `i`.
The **score** of `nums` is the difference between the maximum and minimum elements in `nums`.
Return _the minimum **score** of_ `nums` _after applying the mentioned operation at most once for each index in it._
> Input: nums = [1], k = 0
> Output: 0
> Explanation: The score is max(nums) - min(nums) = 1 - 1 = 0.
> Input: nums = [0,10], k = 2
> Output: 6
> Explanation: Change nums to be [2, 8]. The score is max(nums) - min(nums) = 8 - 2 = 6.
> Input: nums = [1,3,6], k = 3
> Output: 0
> Explanation: Change …
=> [908] Smallest Range1

dlek-user/[914] X of a Kind in a Deck of Cards
You are given an integer array `deck` where `deck[i]` represents the number written on the `ith` card.
Partition the cards into **one or more groups** such that:
- Each group has **exactly** `x` cards where `x > 1`, and
- All the cards in one group have the same integer written on them.
Return `true` _if such partition is possible, or_ `false` _otherwise_.
> Input: deck = [1,2,3,4,4,3,2,1]
> Output: true
> Explanation: Possible partition [1,1],[2,2],[3,3],[4,4].
> Input: deck = [1,1,1,2,2,2,3,3]
> Explanation: No possible partition.
```
public boolean hasGroupsSizeX(int[] deck) {
Map<Integer, Integer> countMap = new HashMap<>();
for (int card : deck) {
countMap.put(card, countMap.getOrDefault(card, 0) + 1);
}
int gcd = -1;
for (int count : …
```
=> [914] X of a Kind in a Deck of Cards

dlek-user/[917] Reverse Only Letters
Given a string `s`, reverse the string according to the following rules:
- All the characters that are not English letters remain in the same position.
- All the English letters (lowercase or uppercase) should be reversed.
Return `s` _after reversing it._
> Input: s = "ab-cd"
> Output: "dc-ba"
> Input: s = "a-bC-dEf-ghIj"
> Output: "j-Ih-gfE-dCba"
> Input: s = "Test1ng-Leet=code-Q!"
> Output: "Qedo1ct-eeLg=ntse-T!"
```
public String reverseOnlyLetters(String s) {
StringBuilder result = new StringBuilder();
int j = s.length() - 1;
char c = s.charAt(i);
if (Character.isLetter(c)) {
while (!Character.isLetter(s.charAt(j))) {
j--;
}
result.append(s.charAt(j));
j--;
} else {
result.append(c);
}
}
return result.toString();
}
}
```
#
``` …
```
=> [917] Reverse Only Letters

dlek-user/[922] Sort Array By parity 2
Given an array of integers `nums`, half of the integers in `nums` are **odd**, and the other half are **even**.
Sort the array so that whenever `nums[i]` is odd, `i` is **odd**, and whenever `nums[i]` is even, `i` is **even**.
Return _any answer array that satisfies this condition._
> Input: nums = [4,2,5,7]
> Output: [4,5,2,7]
> Explanation: [4,7,2,5], [2,5,4,7], [2,7,4,5] would also have been accepted.
> Input: nums = [2,3]
> Output: [2,3]
```
public int[] sortArrayByParityII(int[] nums) {
int evenIndex = 0;
int oddIndex = 1;
while (evenIndex < n && oddIndex < n) {
if (nums[evenIndex] % 2 != 0) {
while (nums[oddIndex] % 2 != 0) {
oddIndex += 2;
}
int temp = nums[evenIndex];
nums[evenIndex] = nums[oddIndex];
nums[oddIndex] = temp;
}
evenIndex += 2;
} …
```
=> [922] Sort Array By parity 2

dlek-user/[925] Long Pressed Name
Your friend is typing his `name` into a keyboard. Sometimes, when typing a character `c`, the key might get long pressed, and the character will be typed 1 or more times.
You examine the `typed` characters of the keyboard. Return `True` if it is possible that it was your friends name, with some characters (possibly none) being long pressed.
> Input: name = "alex", typed = "aaleex"
> Output: true
> Explanation: 'a' and 'e' in 'alex' were long pressed.
> Input: name = "saeed", typed = "ssaaedd"
> Explanation: 'e' must have been pressed twice, but it was not in the typed output.
```
public boolean isLongPressedName(String name, String typed) {
int i = 0, j = 0;
while (j < typed.length()) {
if (i < name.length() && name.charAt(i) == typed.charAt(j)) {
i++; …
```
=> [925] Long Pressed Name

dlek-user/[929] Unique Email Addresses
Every **valid email** consists of a **local name** and a **domain name**, separated by the `'@'` sign. Besides lowercase letters, the email may contain one or more `'.'` or `'+'`.
- For example, in `"alice@leetcode.com"`, `"alice" is the **local name**, and `"leetcode.com"` is the **domain name.**
If you add periods `'.'` between some characters in the **local name** part of an email address, mail sent there will be forwarded to the same address without dots in the local name. Note that this rule does not **apply** to **domain names**.
- For example, `"alice.z@leetcode.com"` and `"alicez@leetcode.com"` forward to the same email address.
If you add a plus `'+'` in the **local name**, everything after the first plus sign **will be ignored**. This allows certain emails to be filtered. Note …
=> [929] Unique Email Addresses

dlek-user/[933] Number of Recent Calls
You have a `RecentCounter` class which counts the number of recent requests within a certain time frame.
Implement the `RecentCounter` class:
- `RecentCounter()` Initializes the counter with zero recent requests.
- `int ping(int t)` Adds a new request at time `t`, where `t` represents some time in milliseconds, and returns the number of requests that has happened in the past `3000` milliseconds (including the new request). Specifically, return the number of requests that have happened in the inclusive range `[t - 3000, t]`.
It is guaranteed that every call to `ping` uses a strictly larger value of `t` than the previous call.
> Input
> ["RecentCounter", "ping", "ping", "ping", "ping"]
> [[], [1], [100], [3001], [3002]]
> Output
> [null, 1, 2, 3, 3]
> 
> Explanation
> RecentCounter …
=> [933] Number of Recent Calls

dlek-user/[941] Valid Mountain Array
Given an array of integers `arr`, return _`true` if and only if it is a valid mountain array._
Recall that arr is a mountain array if and only if:
- `arr.length >= 3`
- There exists some `i` with `0 < i < arr.length - 1` such that:
- `arr[0] < arr[1] < ... < arr[i - 1] < arr[i]` 
- `arr[i] > arr[i + 1] > ... > arr[arr.length - 1]`
> Input: arr = [2,1]
> Input: arr = [3,5,5]
> Input: arr = [0,3,2,1]
> Output: true
```
public boolean validMountainArray(int[] arr) {
if (n < 3) return false;
int i = 0;
while (i + 1 < n && arr[i] < arr[i + 1]) {
i++;
}
if (i == 0 || i == n - 1) {
return false;
}
while (i + 1 < n && arr[i] > arr[i + 1]) {
i++;
}
return i == n - 1;
}
}
```
#
```
if (n < 3) return false;
``` …
=> [941] Valid Mountain Array

dlek-user/[944] Delete Columns to Make Sorted
You are given an array of `n` strings `strs`, all of the same length.
The strings can be arranged such that there is one on each line, making a grid.
- For example, `strs = ["abc", "bce", "cae"]` can be arranged as follows:
> abc
> bce
> cae
You want to **delete** the columns that are **not sorted lexicographically**. In the above example (**0-indexed**), columns 0 (`'a'`, `'b'`, `'c'`) and 2 (`'c'`, `'e'`, `'e'`) are sorted, while column 1 (`'b'`, `'c'`, `'a'`) is not, so you would delete column 1.
Return _the number of columns that you will delete._
> Input: strs = ["cba","daf","ghi"]
> Output: 1
> Explanation: The grid looks as follows:
>   cba
>   daf
>   ghi
> Columns 0 and 2 are sorted, but column 1 is not, so you only need to delete 1 column.
> Input: strs = ["a","b"]
> Output: 0
> …
=> [944] Delete Columns to Make Sorted

dlek-user/[953] Verifying an Alien Dictionary
In an alien language, surprisingly, they also use English lowercase letters, but possibly in a different `order`. The `order` of the alphabet is some permutation of lowercase letters.
Given a sequence of `words` written in the alien language, and the `order` of the alphabet, return `true` if and only if the given `words` are sorted lexicographically in this alien language.
> Input: words = ["hello","leetcode"], order = "hlabcdefgijkmnopqrstuvwxyz"
> Output: true
> Explanation: As 'h' comes before 'l' in this language, then the sequence is sorted.
> Input: words = ["word","world","row"], order = "worldabcefghijkmnpqstuvxyz"
> Explanation: As 'd' comes after 'l' in this language, then words[0] > words[1], hence the sequence is unsorted.
> Input: words = ["apple","app"], …
=> [953] Verifying an Alien Dictionary

dlek-user/[961] N-Repeated Element in Size 2N Array
You are given an integer array `nums` with the following properties:
- `nums.length == 2 * n`.
- `nums` contains `n + 1` unique elements.
- Exactly one element of `nums` is repeated `n` times.
Return _the element that is repeated_ `n` _times_.
> Input: nums = [1,2,3,3]
> Output: 3
> Input: nums = [2,1,2,5,3,2]
> Output: 2
> Input: nums = [5,1,5,2,5,3,5,4]
> Output: 5
```
public int repeatedNTimes(int[] nums) {
for (int i = 0; i < nums.length - 2; i++) {
if (nums[i] == nums[i + 1] || nums[i] == nums[i + 2]) {
return nums[i];
}
}
return nums[nums.length - 1];
}
}
```
#
```
for (int i = 0; i < nums.length - 2; i++) {
if (nums[i] == nums[i + 1] || nums[i] == nums[i + 2]) {
return nums[i];
}
}
```
배열을 순회하면서 nums[i] == nums[i + 1] 또는 nums[i] == nums[i + 2]인 경우를 확인합니다. 이렇게 비교하면 …
=> [961] N-Repeated Element in Size 2N Array

dlek-user/[965] Univalued Binary Tree
A binary tree is **uni-valued** if every node in the tree has the same value.
Given the `root` of a binary tree, return `true` _if the given tree is **uni-valued**, or_ `false` _otherwise_.
> Input: root = [1,1,1,1,1,null,1]
> Output: true
> Input: root = [2,2,2,5,2]
```
public boolean isUnivalTree(TreeNode root) {
return dfs(root, root.val);
}
private boolean dfs(TreeNode node, int val) {
return true;
}
if (node.val != val) {
return false;
}
return dfs(node.left, val) && dfs(node.right, val);
}
}
```
#
```
return dfs(root, root.val);
```
isUnivalTree 메소드에서 dfs 메소드를 호출하며, 루트 노드와 그 값을 인자로 전달합니다.
```
return true;
}
```
node가 null이면 true를 반환하여, 리프 노드까지 탐색을 마쳤음을 의미합니다.
```
if (node.val != val) {
return false;
}
```
현재 …
=> [965] Univalued Binary Tree

dlek-user/[976] Largest Perimeter Triangle
Given an integer array `nums`, return _the largest perimeter of a triangle with a non-zero area, formed from three of these lengths. If it is impossible to form any triangle of a non-zero area, return_ `0`.
> Input: nums = [2,1,2]
> Output: 5
> Explanation: You can form a triangle with three side lengths: 1, 2, and 2.
> Input: nums = [1,2,1,10]
> Output: 0
> You cannot use the side lengths 1, 1, and 2 to form a triangle.
> You cannot use the side lengths 1, 1, and 10 to form a triangle.
> You cannot use the side lengths 1, 2, and 10 to form a triangle.
> As we cannot use any three side lengths to form a triangle of non-zero area, we return 0.
```
public int largestPerimeter(int[] nums) {
Arrays.sort(nums);
for (int i = nums.length - 3; i >= 0; i--) { 
if …
```
=> [976] Largest Perimeter Triangle

dlek-user/[977] Squares of a Sorted Array
Given an integer array `nums` sorted in **non-decreasing** order, return _an array of **the squares of each number** sorted in non-decreasing order._
> Input: nums = [-4,-1,0,3,10]
> Output: [0,1,9,16,100]
> Explanation: After squaring, the array becomes [16,1,0,9,100].
> After sorting, it becomes [0,1,9,16,100].
> Input: nums = [-7,-3,2,3,11]
> Output: [4,9,9,49,121]
```
public int[] sortedSquares(int[] nums) {
int[] result = new int[n];
int left = 0;
int right = n - 1;
int index = n - 1;
int leftSquare = nums[left] * nums[left];
int rightSquare = nums[right] * nums[right];
if (leftSquare > rightSquare) {
result[index] = leftSquare;
left++;
} else {
result[index] = rightSquare;
right--;
}
index--;
}
return result;
}
}
```
# …
=> [977] Squares of a Sorted Array

dlek-user/[989] Add to Array-Form of Integer
The **array-form** of an integer `num` is an array representing its digits in left to right order.
- For example, for `num = 1321`, the array form is `[1,3,2,1]`.
Given num, the **array-form** of an integer, and an integer `k`, return _the **array-form** of the integer_ `num + k`.
Example 1:
Input: num = [1,2,0,0], k = 34
Output: [1,2,3,4]
Explanation: 1200 + 34 = 1234
Example 2:
Input: num = [2,7,4], k = 181
Output: [4,5,5]
Explanation: 274 + 181 = 455
Example 3:
Input: num = [2,1,5], k = 806
Output: [1,0,2,1]
Explanation: 215 + 806 = 1021
```
public List<Integer> addToArrayForm(int[] num, int k) {
LinkedList<Integer> result = new LinkedList<>();
int n = num.length;
int i = n - 1;
while (i >= 0 || k > 0) {
if (i >= 0) {
k += num[i];
i--;
}
result.addFirst(k % 10);
k /= …
```
=> [989] Add to Array-Form of Integer

dlek-user/[993] Cousins in Binary Tree
Given the `root` of a binary tree with unique values and the values of two different nodes of the tree `x` and `y`, return `true` _if the nodes corresponding to the values_ `x` _and_ `y` _in the tree are **cousins**, or_ `false` _otherwise_.
Two nodes of a binary tree are cousins if they have the same depth with different parents.
Note that in a binary tree, the root node is at the depth `0`, and children of each depth `k` node are at the depth `k + 1`.
> Input: root = [1,2,3,4], x = 4, y = 3
> Input: root = [1,2,3,null,4,null,5], x = 5, y = 4
> Output: true
> Input: root = [1,2,3,null,4], x = 2, y = 3
```
private TreeNode xParent = null;
private TreeNode yParent = null;
private int xDepth = -1;
private int yDepth = -1;
public boolean …
```
=> [993] Cousins in Binary Tree

dlek-user/[997] Find the Town Judge
In a town, there are `n` people labeled from `1` to `n`. There is a rumor that one of these people is secretly the town judge.
If the town judge exists, then:
1. The town judge trusts nobody.
2. Everybody (except for the town judge) trusts the town judge.
3. There is exactly one person that satisfies properties 1 and 2.
You are given an array `trust` where `trust[i] = [ai, bi]` representing that the person labeled `ai` trusts the person labeled `bi`. If a trust relationship does not exist in `trust` array, then such a trust relationship does not exist.
Return _the label of the town judge if the town judge exists and can be identified, or return_ `-1` _otherwise_.
> Input: n = 2, trust = [[1,2]]
> Output: 2
> Input: n = 3, trust = [[1,3],[2,3]]
> Output: 3
> Input: n = 3, trust = …
=>  [997] Find the Town Judge

dlek-user/[999] Available Captures for Rook
You are given an `8 x 8` **matrix** representing a chessboard. There is **exactly one** white rook represented by `'R'`, some number of white bishops `'B'`, and some number of black pawns `'p'`. Empty squares are represented by `'.'`.
A rook can move any number of squares horizontally or vertically (up, down, left, right) until it reaches another piece or the edge of the board. A rook is **attacking** a pawn if it can move to the pawn's square in one move.
Note: A rook cannot move through other pieces, such as bishops or pawns. This means a rook cannot attack a pawn if there is another piece blocking the path.
Return the number of pawns the white rook is **attacking**.
> Input: board = [[".",".",".",".",".",".",".","."],[".",".",".","p",".",".",".","."],[".",".",".","R",".",".",".","p"],[" …
=> [999] Available Captures for Rook

dlek-user/[1002] Find Common Characters
Given a string array `words`, return _an array of all characters that show up in all strings within the_ `words` _(including duplicates)._ You may return the answer in **any order**.
> Input: words = ["bella","label","roller"]
> Output: ["e","l","l"]
> Input: words = ["cool","lock","cook"]
> Output: ["c","o"]
```
public List<String> commonChars(String[] words) {
int[] minFreq = new int[26];
Arrays.fill(minFreq, Integer.MAX_VALUE);
for (String word : words) {
int[] charFreq = new int[26];
for (char c : word.toCharArray()) {
charFreq[c - 'a']++;
}
for (int i = 0; i < 26; i++) {
minFreq[i] = Math.min(minFreq[i], charFreq[i]);
}
}
for (int i = 0; i < 26; i++) {
for (int j = 0; j < minFreq[i]; j++) {
result.add(String.valueOf((char) (i …
```
=> [1002] Find Common Characters

dlek-user/[1005] Maximize Sum Of Array After K Negations
Given an integer array `nums` and an integer `k`, modify the array in the following way:
- choose an index `i` and replace `nums[i]` with `-nums[i]`.
You should apply this process exactly `k` times. You may choose the same index `i` multiple times.
Return _the largest possible sum of the array after modifying it in this way._
> Input: nums = [4,2,3], k = 1
> Output: 5
> Explanation: Choose index 1 and nums becomes [4,-2,3].
> Input: nums = [3,-1,0,2], k = 3
> Output: 6
> Explanation: Choose indices (1, 2, 2) and nums becomes [3,1,0,2].
> Input: nums = [2,-3,-1,5,-4], k = 2
> Output: 13
> Explanation: Choose indices (1, 4) and nums becomes [2,3,-1,5,4].
```
public int largestSumAfterKNegations(int[] nums, int k) {
int[] numbers = new int[201];
int sum = 0;
int maxAbs = 0; …
```
=> [1005] Maximize Sum Of Array After K Negations

dlek-user/[1009] Complement of Base 10 Integer
The **complement** of an integer is the integer you get when you flip all the `0`'s to `1`'s and all the `1`'s to `0`'s in its binary representation.
- For example, The integer `5` is `"101"` in binary and its **complement** is `"010"` which is the integer `2`.
Given an integer `n`, return _its complement._
> Input: n = 5
> Output: 2
> Explanation: 5 is "101" in binary, with complement "010" in binary, which is 2 in base-10.
> Input: n = 7
> Output: 0
> Explanation: 7 is "111" in binary, with complement "000" in binary, which is 0 in base-10.
> Input: n = 10
> Output: 5
> Explanation: 10 is "1010" in binary, with complement "0101" in binary, which is 5 in base-10.
```
public int bitwiseComplement(int n) {
if (n == 0) {
return 1;
}
int mask = (Integer.highestOneBit(n) << …
```
=> [1009] Complement of Base 10 Integer

dlek-user/[1013] Partiton Array Into Three Parts With Equal Su
Given an array of integers `arr`, return `true` if we can partition the array into three **non-empty** parts with equal sums.
Formally, we can partition the array if we can find indexes `i + 1 < j with (arr[0] + arr[1] + ... + arr[i] == arr[i + 1] + arr[i + 2] + ... + arr[j - 1] == arr[j] + arr[j + 1] + ... + arr[arr.length - 1])`
> Input: arr = [0,2,1,-6,6,-7,9,1,2,0,1]
> Output: true
> Explanation: 0 + 2 + 1 = -6 + 6 - 7 + 9 + 1 = 2 + 0 + 1
> Input: arr = [0,2,1,-6,6,7,9,-1,2,0,1]
> Input: arr = [3,3,6,5,-2,2,5,1,-9,4]
> Output: true
> Explanation: 3 + 3 = 6 = 5 - 2 + 2 + 5 + 1 - 9 + 4
```
public boolean canThreePartsEqualSum(int[] arr) {
int totalSum = 0;
totalSum += num;
}
// 총합이 3으로 나누어떨어지지 않으면 불가능
if (totalSum % 3 != 0) {
return …
```
=> [1013] Partiton Array Into Three Parts With Equal Sum

dlek-user/[1021] Remove Outermost parentheses
A valid parentheses string is either empty `""`, `"(" + A + ")"`, or `A + B`, where `A` and `B` are valid parentheses strings, and `+` represents string concatenation.
- For example, `""`, `"()"`, `"(())()"`, and `"(()(()))"` are all valid parentheses strings.
A valid parentheses string `s` is primitive if it is nonempty, and there does not exist a way to split it into `s = A + B`, with `A` and `B` nonempty valid parentheses strings.
Given a valid parentheses string `s`, consider its primitive decomposition: `s = P1 + P2 + ... + Pk`, where `Pi` are primitive valid parentheses strings.
Return `s` _after removing the outermost parentheses of every primitive string in the primitive decomposition of_ `s`.
> Input: s = "(()())(())"
> Output: "()()()"
> The input string is …
=> [1021] Remove Outermost parentheses

dlek-user/[1022] Sum of Root To leaf Binary Numbers
You are given the `root` of a binary tree where each node has a value `0` or `1`. Each root-to-leaf path represents a binary number starting with the most significant bit.
- For example, if the path is `0 -> 1 -> 1 -> 0 -> 1`, then this could represent `01101` in binary, which is `13`.
For all leaves in the tree, consider the numbers represented by the path from the root to that leaf. Return _the sum of these numbers._
The test cases are generated so that the answer fits in a **32-bits** integer.
> Input: root = [1,0,1,0,1,0,1]
> Output: 22
> Explanation: (100) + (101) + (110) + (111) = 4 + 5 + 6 + 7 = 22
> Input: root = [0]
> Output: 0
```
public int sumRootToLeaf(TreeNode root) {
return dfs(root, 0);
}
private int dfs(TreeNode node, int current) { …
```
=> [1022] Sum of Root To leaf Binary Numbers

dlek-user/[1025] Divisor Game
Alice and Bob take turns playing a game, with Alice starting first.
Initially, there is a number `n` on the chalkboard. On each player's turn, that player makes a move consisting of:
- Choosing any `x` with `0 < x < n` and `n % x == 0`.
- Replacing the number `n` on the chalkboard with `n - x`.
Also, if a player cannot make a move, they lose the game.
Return `true` _if and only if Alice wins the game, assuming both players play optimally_.
> Input: n = 2
> Output: true
> Explanation: Alice chooses 1, and Bob has no more moves.
> Input: n = 3
> Explanation: Alice chooses 1, Bob chooses 1, and Alice has no more moves.
```
public boolean divisorGame(int n) {
return n % 2 == 0;
}
}
```
#
```
return n % 2 == 0;
```
n%2==0이면 Alice가 항상 이기므로 true를 반환한다.
그렇지 않으면 …
=> [1025] Divisor Game

dlek-user/[1046] Last Stone Weight
You are given an array of integers `stones` where `stones[i]` is the weight of the `ith` stone.
We are playing a game with the stones. On each turn, we choose the **heaviest two stones** and smash them together. Suppose the heaviest two stones have weights `x` and `y` with `x <= y`. The result of this smash is:
- If `x == y`, both stones are destroyed, and
- If `x != y`, the stone of weight `x` is destroyed, and the stone of weight `y` has new weight `y - x`.
At the end of the game, there is **at most one** stone left.
Return _the weight of the last remaining stone. If there are no stones left, return_ `0`.
> Input: stones = [2,7,4,1,8,1]
> Output: 1
> We combine 7 and 8 to get 1 so the array converts to [2,4,1,1,1] then,
> we combine 2 and 4 to get 2 so the array converts …
=> [1046] Last Stone Weight

dlek-user/[1051] Height Checker
A school is trying to take an annual photo of all the students. The students are asked to stand in a single file line in **non-decreasing order** by height. Let this ordering be represented by the integer array `expected` where `expected[i]` is the expected height of the `ith` student in line.
You are given an integer array `heights` representing the **current order** that the students are standing in. Each `heights[i]` is the height of the `ith` student in line (**0-indexed**).
Return _the **number of indices** where_ `heights[i] != expected[i]`.
> Input: heights = [1,1,4,2,1,3]
> Output: 3
> heights:  [1,1,4,2,1,3]
> expected: [1,1,1,2,3,4]
> Indices 2, 4, and 5 do not match.
> Input: heights = [5,1,2,3,4]
> Output: 5
> Explanation:
> heights:  [5,1,2,3,4]
> expected: …
=> [1051] Height Checker

dlek-user/[1071] Greatest Common Divisor of Strings
For two strings `s` and `t`, we say "`t` divides `s`" if and only if `s = t + t + t + ... + t + t` (i.e., `t` is concatenated with itself one or more times).
Given two strings `str1` and `str2`, return _the largest string_ `x` _such that_ `x` _divides both_ `str1` _and_ `str2`.
> Input: str1 = "ABCABC", str2 = "ABC"
> Output: "ABC"
> Input: str1 = "ABABAB", str2 = "ABAB"
> Output: "AB"
> Input: str1 = "LEET", str2 = "CODE"
> Output: ""
```
public String gcdOfStrings(String str1, String str2) {
if (!(str1 + str2).equals(str2 + str1)) {
return "";
}
int gcdLength = gcd(str1.length(), str2.length());
return str1.substring(0, gcdLength);
}
private int gcd(int a, int b) {
return b == 0 ? a : gcd(b, a % b);
}
}
```
#
```
if (!(str1 + str2).equals(str2 + str1)) {
return "";
} …
```
=> [1071] Greatest Common Divisor of Strings

dlek-user/[1078] Occurrences After Bigram
Given two strings `first` and `second`, consider occurrences in some text of the form `"first second third"`, where `second` comes immediately after `first`, and `third` comes immediately after `second`.
Return _an array of all the words_ `third` _for each occurrence of_ `"first second third"`.
> Input: text = "alice is a good girl she is a good student", first = "a", second = "good"
> Output: ["girl","student"]
> Input: text = "we will we will rock you", first = "we", second = "will"
> Output: ["we","rock"]
```
public String[] findOcurrences(String text, String first, String second) {
String[] words = text.split(" ");
for (int i = 0; i < words.length - 2; i++) {
if (words[i].equals(first) && words[i + 1].equals(second)) { …
```
=> [1078] Occurrences After Bigram

dlek-user/[1089] Duplicate Zeros
Given a fixed-length integer array `arr`, duplicate each occurrence of zero, shifting the remaining elements to the right.
**Note** that elements beyond the length of the original array are not written. Do the above modifications to the input array in place and do not return anything.
> Input: arr = [1,0,2,3,0,4,5,0]
> Output: [1,0,0,2,3,0,0,4]
> Explanation: After calling your function, the input array is modified to: [1,0,0,2,3,0,0,4]
> Input: arr = [1,2,3]
> Output: [1,2,3]
> Explanation: After calling your function, the input array is modified to: [1,2,3]
```
public void duplicateZeros(int[] arr) {
int zeros = 0;
if (num == 0) zeros++;
}
for (int i = n - 1; i >= 0; i--) {
if (i + zeros < n) {
arr[i + zeros] = arr[i];
}
if …
```
=> [1089] Duplicate Zeros

dlek-user/[1103] Distribute Candies to People
We distribute some number of `candies`, to a row of `**n = num_people**` people in the following way:
We then give 1 candy to the first person, 2 candies to the second person, and so on until we give n candies to the last person.
Then, we go back to the start of the row, giving `n + 1` candies to the first person, `n + 2` candies to the second person, and so on until we give `2 * n` candies to the last person.
This process repeats (with us giving one more candy each time, and moving to the start of the row after we reach the end) until we run out of candies.  The last person will receive all of our remaining candies (not necessarily one more than the previous gift).
Return an array (of length `num_people` and sum `candies`) that represents the final distribution of candies.
> Input: …
=> [1103] Distribute Candies to People

dlek-user/[1114] Print in Order
Suppose we have a class:
> public class Foo {
>   public void first() { print("first"); }
>   public void second() { print("second"); }
>   public void third() { print("third"); }
> }
The same instance of `Foo` will be passed to three different threads. Thread A will call `first()`, thread B will call `second()`, and thread C will call `third()`. Design a mechanism and modify the program to ensure that `second()` is executed after `first()`, and `third()` is executed after `second()`.
We do not know how the threads will be scheduled in the operating system, even though the numbers in the input seem to imply the ordering. The input format you see is mainly to ensure our tests' comprehensiveness.
> Output: "firstsecondthird"
> Explanation: There are three threads …
=> [1114] Print in Order

dlek-user/[1122] Relative Sort Array
Given two arrays `arr1` and `arr2`, the elements of `arr2` are distinct, and all elements in `arr2` are also in `arr1`.
Sort the elements of `arr1` such that the relative ordering of items in `arr1` are the same as in `arr2`. Elements that do not appear in `arr2` should be placed at the end of `arr1` in ascending order.
> Input: arr1 = [2,3,1,3,2,4,6,7,9,2,19], arr2 = [2,1,4,3,9,6]
> Output: [2,2,2,1,4,3,3,9,6,7,19]
> Input: arr1 = [28,6,22,8,44,17], arr2 = [22,28,8,6]
> Output: [22,28,8,6,17,44]
```
public int[] relativeSortArray(int[] arr1, int[] arr2) {
Map<Integer, Integer> rank = new HashMap<>();
for (int i = 0; i < arr2.length; i++) {
rank.put(arr2[i], i);
}
Integer[] arr1Integer = Arrays.stream(arr1).boxed().toArray(Integer[]::new);
Arrays.sort(arr1Integer, (a, b) …
```
=> [1122] Relative Sort Array

dlek-user/[1137] N-th Tribonacci Number
The Tribonacci sequence Tn is defined as follows: 
T0 = 0, T1 = 1, T2 = 1, and Tn+3 = Tn + Tn+1 + Tn+2 for n >= 0.
Given `n`, return the value of Tn.
> Input: n = 4
> Output: 4
> Explanation:
> T_3 = 0 + 1 + 1 = 2
> T_4 = 1 + 1 + 2 = 4
> Input: n = 25
> Output: 1389537
```
public int tribonacci(int n) {
if (n == 0) return 0;
if (n == 1 || n == 2) return 1;
int t0 = 0, t1 = 1, t2 = 1;
for (int i = 3; i <= n; i++) {
int next = t0 + t1 + t2;
t0 = t1;
t1 = t2;
t2 = next;
}
return t2;
}
}
```
#
```
if (n == 0) return 0;
if (n == 1 || n == 2) return 1;
```
n=0,1,2인 경우, 점화식 계산 없이 바로 반환합니다.
이는 초기 조건으로 정의된 값을 그대로 반환하기 때문입니다.
```
int t0 = 0, t1 = 1, t2 = 1;
```
이전 세 값을 저장할 변수 초기화합니다.
```
for (int i = 3; i <= n; i++) {
int next = t0 + t1 + t2;
t0 = t1;
t1 = t2;
t2 = next;
}
``` …
=> [1137] N-th Tribonacci Number

dlek-user/[1160] Find Words That Can Be Formed by Characters
You are given an array of strings `words` and a string `chars`.
A string is **good** if it can be formed by characters from `chars` (each character can only be used once).
Return _the sum of lengths of all good strings in words_.
> Input: words = ["cat","bt","hat","tree"], chars = "atach"
> Output: 6
> Explanation: The strings that can be formed are "cat" and "hat" so the answer is 3 + 3 = 6.
> Input: words = ["hello","world","leetcode"], chars = "welldonehoneyr"
> Output: 10
> Explanation: The strings that can be formed are "hello" and "world" so the answer is 5 + 5 = 10.
```
public int countCharacters(String[] words, String chars) {
int[] charCount = new int[26];
for (char c : chars.toCharArray()) {
charCount[c - 'a']++;
}
int result = 0;
for (String word : words) {
if …
```
=> [1160] Find Words That Can Be Formed by Characters

dlek-user/[1175] Prime Arrangements
Return the number of permutations of 1 to `n` so that prime numbers are at prime indices (1-indexed.)
_(Recall that an integer is prime if and only if it is greater than 1, and cannot be written as a product of two positive integers both smaller than it.)_
Since the answer may be large, return the answer **modulo** `10^9 + 7`.
> Input: n = 5
> Output: 12
> Explanation: For example [1,2,5,4,3] is a valid permutation, but [5,2,3,4,1] is not because the prime number 5 is at index 1.
> Input: n = 100
> Output: 682289015
```
private static final int MOD = 1_000_000_007;
public int numPrimeArrangements(int n) {
int primeCount = countPrimes(n);
int nonPrimeCount = n - primeCount;
return (int) (factorial(primeCount) * factorial(nonPrimeCount) % MOD);
}
private int countPrimes(int …
```
=> [1175] Prime Arrangements

dlek-user/[1184] Distance Between Bus Stops
A bus has `n` stops numbered from `0` to `n - 1` that form a circle. We know the distance between all pairs of neighboring stops where `distance[i]` is the distance between the stops number `i` and `(i + 1) % n`.
The bus goes along both directions i.e. clockwise and counterclockwise.
Return the shortest distance between the given `start` and `destination` stops.
> Input: distance = [1,2,3,4], start = 0, destination = 1
> Output: 1
> Explanation: Distance between 0 and 1 is 1 or 9, minimum is 1.
> Input: distance = [1,2,3,4], start = 0, destination = 2
> Output: 3
> Explanation: Distance between 0 and 2 is 3 or 7, minimum is 3.
> Input: distance = [1,2,3,4], start = 0, destination = 3
> Output: 4
> Explanation: Distance between 0 and 3 is 6 or 4, minimum is 4.
```
public …
```
=> [1184] Distance Between Bus Stops

dlek-user/[1185] Day of the Week
Given a date, return the corresponding day of the week for that date.
The input is given as three integers representing the `day`, `month` and `year` respectively.
Return the answer as one of the following values `{"Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"}`.
> Input: day = 31, month = 8, year = 2019
> Output: "Saturday"
> Input: day = 18, month = 7, year = 1999
> Output: "Sunday"
> Input: day = 15, month = 8, year = 1993
> Output: "Sunday"
```
import java.time.LocalDate;
import java.time.DayOfWeek;
public String dayOfTheWeek(int day, int month, int year) {
LocalDate date = LocalDate.of(year, month, day);
DayOfWeek dayOfWeek = date.getDayOfWeek();
return dayOfWeek.toString().charAt(0) + dayOfWeek.toString().substring(1).toLowerCase();
} …
```
=> [1185] Day of the Week

dlek-user/[1189] Maximum Number of Balloons
Given a string `text`, you want to use the characters of `text` to form as many instances of the word "**balloon**" as possible.
You can use each character in `text` **at most once**. Return the maximum number of instances that can be formed.
> Input: text = "nlaebolko"
> Output: 1
> Input: text = "loonbalxballpoon"
> Output: 2
> Input: text = "leetcode"
> Output: 0
```
public int maxNumberOfBalloons(String text) {
Map<Character, Integer> balloonMap = new HashMap<>();
balloonMap.put('b', 1);
balloonMap.put('a', 1);
balloonMap.put('l', 2);
balloonMap.put('o', 2);
balloonMap.put('n', 1);
Map<Character, Integer> textMap = new HashMap<>();
for (char c : text.toCharArray()) {
textMap.put(c, textMap.getOrDefault(c, 0) + 1);
}
int maxBalloons = Integer.MAX_VALUE;
for …
```
=> [1189] Maximum Number of Balloons

dlek-user/[1200] Minimum Absolute Difference
Given an array of distinct integers `arr`, find all pairs of elements with the minimum absolute difference of any two elements.
Return a list of pairs in ascending order(with respect to pairs), each pair `[a, b]` follows
- `a, b` are from `arr`
- `a < b`
- `b - a` equals to the minimum absolute difference of any two elements in `arr`
> Input: arr = [4,2,1,3]
> Output: [[1,2],[2,3],[3,4]]
> Explanation: The minimum absolute difference is 1. List all pairs with difference equal to 1 in ascending order.
> Input: arr = [1,3,6,10,15]
> Output: [[1,3]]
> Input: arr = [3,8,-10,23,19,-4,-14,27]
> Output: [[-14,-10],[19,23],[23,27]]
```
public List<List<Integer>> minimumAbsDifference(int[] arr) {
Arrays.sort(arr);
int minDiff = Integer.MAX_VALUE;
for (int i = 1; i < arr.length; …
```
=> [1200] Minimum Absolute Difference

dlek-user/[1207] Unique Number of Occurrences
Given an array of integers `arr`, return `true` _if the number of occurrences of each value in the array is **unique** or_ `false` _otherwise_.
> Input: arr = [1,2,2,1,1,3]
> Output: true
> Explanation: The value 1 has 3 occurrences, 2 has 2 and 3 has 1. No two values have the same number of occurrences.
> Input: arr = [1,2]
> Input: arr = [-3,0,1,-3,1,1,1,-3,10,0]
> Output: true
```
public boolean uniqueOccurrences(int[] arr) {
Map<Integer, Integer> countMap = new HashMap<>();
countMap.put(num, countMap.getOrDefault(num, 0) + 1);
}
Set<Integer> occurrences = new HashSet<>();
for (int count : countMap.values()) {
if (!occurrences.add(count)) {
return false;
}
}
return true;
}
}
```
#
```
Map<Integer, Integer> countMap = new …
```
=> [1207] Unique Number of Occurrences

dlek-user/[1221] Split a String in Balanced Strings
Balanced strings are those that have an equal quantity of `'L'` and `'R'` characters.
Given a **balanced** string `s`, split it into some number of substrings such that:
- Each substring is balanced.
Return _the **maximum** number of balanced strings you can obtain._
> Input: s = "RLRRLLRLRL"
> Output: 4
> Explanation: s can be split into "RL", "RRLL", "RL", "RL", each substring contains same number of 'L' and 'R'.
> Input: s = "RLRRRLLRLL"
> Output: 2
> Explanation: s can be split into "RL", "RRRLLRLL", each substring contains same number of 'L' and 'R'.
> Note that s cannot be split into "RL", "RR", "RL", "LR", "LL", because the 2nd and 5th substrings are not balanced.
> Input: s = "LLLLRRRR"
> Output: 1
> Explanation: s can be split into "LLLLRRRR".
```
public int …
```
=> [1221] Split a String in Balanced Strings

dlek-user/[1232] Check If It Is a Straight
You are given an array `coordinates`, `coordinates[i] = [x, y]`, where `[x, y]` represents the coordinate of a point. Check if these points make a straight line in the XY plane.
> Input: coordinates = [[1,2],[2,3],[3,4],[4,5],[5,6],[6,7]]
> Output: true
> Input: coordinates = [[1,1],[2,2],[3,4],[4,5],[5,6],[7,7]]
```
public boolean checkStraightLine(int[][] coordinates) {
int x1 = coordinates[0][0], y1 = coordinates[0][1];
int x2 = coordinates[1][0], y2 = coordinates[1][1];
for (int i = 2; i < coordinates.length; i++) {
int x3 = coordinates[i][0], y3 = coordinates[i][1];
if ((x2 - x1) * (y3 - y1) != (y2 - y1) * (x3 - x1)) {
return false;
}
}
return true;
}
}
```
#
```
int x1 = coordinates[0][0], y1 = coordinates[0][1];
int x2 = coordinates[1][0], y2 = …
```
=> [1232] Check If It Is a Straight

dlek-user/[1252] Cells with Odd Values in a Matrix
There is an `m x n` matrix that is initialized to all `0`'s. There is also a 2D array `indices` where each `indices[i] = [ri, ci]` represents a **0-indexed location** to perform some increment operations on the matrix.
For each location `indices[i]`, do **both** of the following:
1. Increment **all** the cells on row `ri`.
2. Increment **all** the cells on column `ci`.
Given `m`, `n`, and `indices`, return _the **number of odd-valued cells** in the matrix after applying the increment to all locations in_ `indices`.
> Input: m = 2, n = 3, indices = [[0,1],[1,1]]
> Output: 6
> Explanation: Initial matrix = [[0,0,0],[0,0,0]].
> After applying first increment it becomes [[1,2,1],[0,1,0]].
> The final matrix is [[1,3,1],[1,3,1]], which contains 6 odd numbers.
> Input: m = 2, n = 2, indices = …
=> [1252] Cells with Odd Values in a Matrix

dlek-user/[1260] Shift 2D Grid
Given a 2D `grid` of size `m x n` and an integer `k`. You need to shift the `grid` `k` times.
In one shift operation:
- Element at `grid[i][j]` moves to `grid[i][j + 1]`.
- Element at `grid[i][n - 1]` moves to `grid[i + 1][0]`.
- Element at `grid[m - 1][n - 1]` moves to `grid[0][0]`.
Return the 2D _grid_ after applying shift operation `k` times.
> Input: grid = [[1,2,3],[4,5,6],[7,8,9]], k = 1
> Output: [[9,1,2],[3,4,5],[6,7,8]]
> Input: grid = [[3,8,1,9],[19,7,2,5],[4,6,11,10],[12,0,21,13]], k = 4
> Output: [[12,0,21,13],[3,8,1,9],[19,7,2,5],[4,6,11,10]]
> Input: grid = [[1,2,3],[4,5,6],[7,8,9]], k = 9
> Output: [[1,2,3],[4,5,6],[7,8,9]]
```
public List<List<Integer>> shiftGrid(int[][] grid, int k) {
int m = grid.length;
int n = grid[0].length;
int total = m * n;
k %= …
```
=> [1260] Shift 2D Grid

dlek-user/[1266] Minimum Time Visiting All Points
On a 2D plane, there are `n` points with integer coordinates `points[i] = [xi, yi]`. Return _the **minimum time** in seconds to visit all the points in the order given by_ `points`.
You can move according to these rules:
- In `1` second, you can either:
- move vertically by one unit,
- move horizontally by one unit, or
- move diagonally `sqrt(2)` units (in other words, move one unit vertically then one unit horizontally in `1` second).
- You have to visit the points in the same order as they appear in the array.
- You are allowed to pass through points that appear later in the order, but these do not count as visits.
> Input: points = [[1,1],[3,4],[-1,0]]
> Output: 7
> Explanation: One optimal path is [1,1] -> [2,2] -> [3,3] -> [3,4] -> [2,3] -> [1,2] -> [0,1] -> [-1,0]   
> Time from …
=> [1266] Minimum Time Visiting All Points

dlek-user/[1275] Find Winner on a Tic Tac Toe Game
**Tic-tac-toe** is played by two players `A` and `B` on a `3 x 3` grid. The rules of Tic-Tac-Toe are:
- Players take turns placing characters into empty squares `' '`.
- The first player `A` always places `'X'` characters, while the second player `B` always places `'O'` characters.
- `'X'` and `'O'` characters are always placed into empty squares, never on filled ones.
- The game ends when there are **three** of the same (non-empty) character filling any row, column, or diagonal.
- The game also ends if all squares are non-empty.
- No more moves can be played if the game is over.
Given a 2D integer array `moves` where `moves[i] = [rowi, coli]` indicates that the `ith` move will be played on `grid[rowi][coli]`. return _the winner of the game if it exists_ (`A` or `B`). In case the game …
=> [1275] Find Winner on a Tic Tac Toe Game

dlek-user/[1281] Subtract the Product and Sum of Digits of an Integer
Given an integer number `n`, return the difference between the product of its digits and the sum of its digits.
> Input: n = 234
> Output: 15 
> Product of digits = 2 * 3 * 4 = 24 
> Sum of digits = 2 + 3 + 4 = 9 
> Result = 24 - 9 = 15
> Input: n = 4421
> Output: 21
> Product of digits = 4 * 4 * 2 * 1 = 32 
> Sum of digits = 4 + 4 + 2 + 1 = 11 
> Result = 32 - 11 = 21
```
public int subtractProductAndSum(int n) {
int product = 1;
int sum = 0;
while (n > 0) {
int digit = n % 10;
product *= digit;
sum += digit;
n /= 10;
}
return product - sum;
}
}
```
#
```
int product = 1;
```
product는 곱을 계산하기 위해 1로 초기화.
```
int sum = 0;
```
sum은 합을 계산하기 위해 0으로 초기화.
```
int digit = n % 10;
```
n % 10으로 현재 마지막 자리수를 추출.
```
product *= digit;
sum += digit;
``` …
=> [1281] Subtract the Product and Sum of Digits of an Integer

dlek-user/[1287] Element Appearing More Than 25% In Sorted Array
Given an integer array **sorted** in non-decreasing order, there is exactly one integer in the array that occurs more than 25% of the time, return that integer.
> Input: arr = [1,2,2,6,6,6,6,7,10]
> Output: 6
> Input: arr = [1,1]
> Output: 1
```
public int findSpecialInteger(int[] arr) {
int threshold = n / 4;
for (int i = 0; i < n - threshold; i++) {
if (arr[i] == arr[i + threshold]) {
return arr[i];
}
}
return -1;
}
}
```
#
```
```
n 배열의 길이.
```
int threshold = n / 4;
```
threshold 배열 길이의 25% 기준 값.
```
for (int i = 0; i < n - threshold; i++) {
if (arr[i] == arr[i + threshold]) {
return arr[i];
}
}
```
배열을 순회하며 arr[i]와 arr[i+threshold]가 같은지 확인합니다.
같은 경우 해당 숫자가 25% 이상 등장하므로 반환.
```
return -1;
```
문제 조건에서 25% 이상 등장하는 숫자가 하나만 존재한다고 …
=> [1287] Element Appearing More Than 25% In Sorted Array

dlek-user/[1290] Convert Binary Number in a Linked List to Integer
Given `head` which is a reference node to a singly-linked list. The value of each node in the linked list is either `0` or `1`. The linked list holds the binary representation of a number.
Return the _decimal value_ of the number in the linked list.
The **most significant bit** is at the head of the linked list.
> Input: head = [1,0,1]
> Output: 5
> Explanation: (101) in base 2 = (5) in base 10
> Input: head = [0]
> Output: 0
```
public int getDecimalValue(ListNode head) {
int result = 0;
while (head != null) {
result = result * 2 + head.val;
head = head.next;
}
return result;
}
}
```
#
```
int result = 0;
```
result를 0으로 초기화합니다.
```
while (head != null) {
result = result * 2 + head.val; 
head = head.next; 
}
```
연결 리스트를 순회하며 result에 기존 값을 2배로 확장한 후, 현재 노드의 값을 더합니다.
이는 …
=> [1290] Convert Binary Number in a Linked List to Integer

dlek-user/[1299] Replace Elements with Greatest Element on Right Side
Given an array `arr`, replace every element in that array with the greatest element among the elements to its right, and replace the last element with `-1`.
After doing so, return the array.
> Input: arr = [17,18,5,4,6,1]
> Output: [18,6,6,6,1,-1]
> - index 0 --> the greatest element to the right of index 0 is index 1 (18).
> - index 1 --> the greatest element to the right of index 1 is index 4 (6).
> - index 2 --> the greatest element to the right of index 2 is index 4 (6).
> - index 3 --> the greatest element to the right of index 3 is index 4 (6).
> - index 4 --> the greatest element to the right of index 4 is index 5 (1).
> - index 5 --> there are no elements to the right of index 5, so we put -1.
> Input: arr = [400]
> Output: [-1]
> Explanation: There are no elements …
=> [1299] Replace Elements with Greatest Element on Right Side

dlek-user/[1304] Find N Unique Integers Sum up to Zero
Given an integer `n`, return **any** array containing `n` **unique** integers such that they add up to `0`.
> Input: n = 5
> Output: [-7,-1,1,3,4]
> Explanation: These arrays also are accepted [-5,-1,1,2,3] , [-3,-1,2,-2,4].
> Input: n = 3
> Output: [-1,0,1]
> Input: n = 1
> Output: [0]
```
public int[] sumZero(int n) {
int[] result = new int[n];
int index = 0;
for (int i = 1; i <= n / 2; i++) {
result[index++] = i;
result[index++] = -i;
}
if (n % 2 != 0) {
result[index] = 0;
}
return result;
}
}
```
#
```
int[] result = new int[n];
```
int[] result = new int[n] n 크기의 결과 배열을 생성합니다.
```
for (int i = 1; i <= n / 2; i++)  {
result[index++] = i;
result[index++] = -i;
}
```
i=1부터 n/2까지 반복하여 −i를 배열에 추가합니다.
```
if (n % 2 != 0) {
result[index] = 0;
}
```
n%2!=0이면 배열의 마지막에 0을 …
=> [1304] Find N Unique Integers Sum up to Zero

dlek-user/[1309] Decrypt String from Alphabet to Integer Mapping
You are given a string `s` formed by digits and `'#'`. We want to map `s` to English lowercase characters as follows:
- Characters (`'a'` to `'i'`) are represented by (`'1'` to `'9'`) respectively.
- Characters (`'j'` to `'z'`) are represented by (`'10#'` to `'26#'`) respectively.
Return _the string formed after mapping._
The test cases are generated so that a unique mapping will always exist.
> Input: s = "10#11#12"
> Output: "jkab"
> Explanation: "j" -> "10#" , "k" -> "11#" , "a" -> "1" , "b" -> "2".
> Input: s = "1326#"
> Output: "acz"
```
public String freqAlphabets(String s) {
StringBuilder result = new StringBuilder();
int i = s.length() - 1;
while (i >= 0) {
if (s.charAt(i) == '#') {
int num = Integer.parseInt(s.substring(i - 2, i));
result.append((char) ('a' + num …
```
=> [1309] Decrypt String from Alphabet to Integer Mapping

dlek-user/[1317] Convert Integer to the Sum of Two No-Zero Integers
**No-Zero integer** is a positive integer that **does not contain any** `0` in its decimal representation.
Given an integer `n`, return _a list of two integers_ `[a, b]` _where:_
- `a` and `b` are **No-Zero integers**.
- `a + b = n`
The test cases are generated so that there is at least one valid solution. If there are many valid solutions, you can return any of them.
> Input: n = 2
> Output: [1,1]
> Explanation: Let a = 1 and b = 1.
> Both a and b are no-zero integers, and a + b = 2 = n.
> Input: n = 11
> Output: [2,9]
> Explanation: Let a = 2 and b = 9.
> Both a and b are no-zero integers, and a + b = 11 = n.
> Note that there are other valid answers as [8, 3] that can be accepted.
```
public int[] getNoZeroIntegers(int n) {
for (int a = 1; a < n; a++) {
int b = n - a; …
```
=> [1317] Convert Integer to the Sum of Two No-Zero Integers

dlek-user/[1323] Maximum 69 Number
You are given a positive integer `num` consisting only of digits `6` and `9`.
Return _the maximum number you can get by changing **at most** one digit (_`6` _becomes_ `9`, _and_ `9` _becomes_ `6`_)._
> Input: num = 9669
> Output: 9969
> Changing the first digit results in 6669.
> Changing the second digit results in 9969.
> Changing the third digit results in 9699.
> Changing the fourth digit results in 9666.
> The maximum number is 9969.
> Input: num = 9996
> Output: 9999
> Explanation: Changing the last digit 6 to 9 results in the maximum number.
> Input: num = 9999
> Output: 9999
> Explanation: It is better not to apply any change.
```
public int maximum69Number (int num) {
String numStr = Integer.toString(num);
StringBuilder modifiedNum = new …
```
=> [1323] Maximum 69 Number

dlek-user/[1331] Rank Transform of an Array
Given an array of integers `arr`, replace each element with its rank.
The rank represents how large the element is. The rank has the following rules:
- Rank is an integer starting from 1.
- The larger the element, the larger the rank. If two elements are equal, their rank must be the same.
- Rank should be as small as possible.
> Input: arr = [40,10,20,30]
> Output: [4,1,2,3]
> Explanation: 40 is the largest element. 10 is the smallest. 20 is the second smallest. 30 is the third smallest.
> Input: arr = [100,100,100]
> Output: [1,1,1]
> Explanation: Same elements share the same rank.
> Input: arr = [37,12,28,9,100,56,80,5,12]
> Output: [5,3,4,2,8,6,7,1,3]
```
public int[] arrayRankTransform(int[] arr) {
int[] sortedArr = arr.clone();
Arrays.sort(sortedArr);
Map<Integer, …
```
=> [1331] Rank Transform of an Array

dlek-user/[1337] The K Weakest Rows in a Matrix
You are given an `m x n` binary matrix `mat` of `1`'s (representing soldiers) and `0`'s (representing civilians). The soldiers are positioned **in front** of the civilians. That is, all the `1`'s will appear to the **left** of all the `0`'s in each row.
A row `i` is **weaker** than a row `j` if one of the following is true:
- The number of soldiers in row `i` is less than the number of soldiers in row `j`.
- Both rows have the same number of soldiers and `i < j`.
Return _the indices of the_ `k` _**weakest** rows in the matrix ordered from weakest to strongest._
> Input: mat = 
> [[1,1,0,0,0],
>  [1,1,1,1,0],
>  [1,0,0,0,0],
>  [1,1,0,0,0],
>  [1,1,1,1,1]], 
> k = 3
> Output: [2,0,3]
> The number of soldiers in each row is: 
> - Row 0: 2 
> - Row 1: 4 
> - Row 2: 1 
> - Row …
=> [1337] The K Weakest Rows in a Matrix

dlek-user/[1346] Check If N and Its Double Exist
Given an array `arr` of integers, check if there exist two indices `i` and `j` such that :
- `i != j`
- `0 <= i, j < arr.length`
- `arr[i] == 2 * arr[j]`
> Input: arr = [10,2,5,3]
> Output: true
> Explanation: For i = 0 and j = 2, arr[i] == 10 == 2 * 5 == 2 * arr[j]
> #### Example 2:
> Input: arr = [3,1,7,11]
> Explanation: There is no i and j that satisfy the conditions.
```
public boolean checkIfExist(int[] arr) {
Set<Integer> seen = new HashSet<>();
if (seen.contains(2 * num) || (num % 2 == 0 && seen.contains(num / 2))) {
return true;
}
seen.add(num);
}
return false;
}
}
```
#
```
Set<Integer> seen = new HashSet<>();
```
해시셋 seen을 초기화하여 순회 중 숫자를 저장.
```
if (seen.contains(2 * num) || (num % 2 == 0 && …
```
=> [1346] Check If N and Its Double Exist

dlek-user/[1342] Number of Steps to Reduce a Number to Zero
Given an integer `num`, return _the number of steps to reduce it to zero._
In one step, if the current number is even, you have to divide it by `2`, otherwise, you have to subtract `1` from it.
> Input: num = 14
> Output: 6
> Step 1) 14 is even; divide by 2 and obtain 7. 
> Step 2) 7 is odd; subtract 1 and obtain 6.
> Step 3) 6 is even; divide by 2 and obtain 3. 
> Step 4) 3 is odd; subtract 1 and obtain 2. 
> Step 5) 2 is even; divide by 2 and obtain 1. 
> Step 6) 1 is odd; subtract 1 and obtain 0.
> Input: num = 8
> Output: 4
> Step 1) 8 is even; divide by 2 and obtain 4. 
> Step 2) 4 is even; divide by 2 and obtain 2. 
> Step 3) 2 is even; divide by 2 and obtain 1. 
> Step 4) 1 is odd; subtract 1 and obtain 0.
> Input: num = 123
> Output: 12
```
class …
```
=> [1342] Number of Steps to Reduce a Number to Zero

dlek-user/[1351] Count Negative Numbers in a Sorted Matrix
Given a `m x n` matrix `grid` which is sorted in non-increasing order both row-wise and column-wise, return _the number of **negative** numbers in_ `grid`.
> Input: grid = [[4,3,2,-1],[3,2,1,-1],[1,1,-1,-2],[-1,-1,-2,-3]]
> Output: 8
> Explanation: There are 8 negatives number in the matrix.
> Input: grid = [[3,2],[1,0]]
> Output: 0
```
public int countNegatives(int[][] grid) {
int m = grid.length;
int n = grid[0].length;
int count = 0;
int row = 0, col = n - 1;
while (row < m && col >= 0) {
if (grid[row][col] < 0) {
count += (m - row);
col--;
} else {
row++;
}
}
return count;
}
}
```
#
```
int m = grid.length;
int n = grid[0].length;
int count = 0;
int row = 0, col = n - 1;
```
행(row)은 0, 열(col)은 마지막 열에서 시작.
음수 개수를 저장할 변수 count를 0으로 초기화.
```
while (row < m && col >= 0) { …
```
=> [1351] Count Negative Numbers in a Sorted Matrix

dlek-user/[1356] Sort Integers by The Number of 1 Bits
You are given an integer array `arr`. Sort the integers in the array in ascending order by the number of `1`'s in their binary representation and in case of two or more integers have the same number of `1`'s you have to sort them in ascending order.
Return _the array after sorting it._
> Input: arr = [0,1,2,3,4,5,6,7,8]
> Output: [0,1,2,4,8,3,5,6,7]
> Explantion: [0] is the only integer with 0 bits.
> [1,2,4,8] all have 1 bit.
> [3,5,6] have 2 bits.
> [7] has 3 bits.
> The sorted array by bits is [0,1,2,4,8,3,5,6,7]
> Input: arr = [1024,512,256,128,64,32,16,8,4,2,1]
> Output: [1,2,4,8,16,32,64,128,256,512,1024]
> Explantion: All integers have 1 bit in the binary representation, you should just sort them in ascending order.
```
import java.util.Arrays;
public int[] …
```
=> [1356] Sort Integers by The Number of 1 Bits

dlek-user/[1360] Number of Days Between Two Dates
Write a program to count the number of days between two dates.
The two dates are given as strings, their format is `YYYY-MM-DD` as shown in the examples.
> Input: date1 = "2019-06-29", date2 = "2019-06-30"
> Output: 1
> Input: date1 = "2020-01-15", date2 = "2019-12-31"
> Output: 15
```
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
public int daysBetweenDates(String date1, String date2) {
LocalDate d1 = LocalDate.parse(date1);
LocalDate d2 = LocalDate.parse(date2);
return (int) Math.abs(ChronoUnit.DAYS.between(d1, d2));
}
}
```
#
```
import java.time.LocalDate;
```
날짜를 다룰 수 있는 클래스. 문자열로 주어진 날짜를 쉽게 변환하거나 조작할 수 있습니다.
```
import java.time.temporal.ChronoUnit;
```
날짜와 시간의 차이를 계산하는 유틸리티 클래스.
```
LocalDate d1 = LocalDate.parse(date1);
LocalDate d2 = …
```
=> [1360] Number of Days Between Two Dates

dlek-user/[1365] How Many Numbers Are Smaller Than the Current Number
Given the array `nums`, for each `nums[i]` find out how many numbers in the array are smaller than it. That is, for each `nums[i]` you have to count the number of valid `j's` such that `j != i` **and** `nums[j] < nums[i]`.
Return the answer in an array.
> Input: nums = [8,1,2,2,3]
> Output: [4,0,1,1,3]
> For nums[0]=8 there exist four smaller numbers than it (1, 2, 2 and 3). 
> For nums[1]=1 does not exist any smaller number than it.
> For nums[2]=2 there exist one smaller number than it (1). 
> For nums[3]=2 there exist one smaller number than it (1). 
> For nums[4]=3 there exist three smaller numbers than it (1, 2 and 2).
> Input: nums = [6,5,4,8]
> Output: [2,1,0,3]
> Input: nums = [7,7,7,7]
> Output: [0,0,0,0]
```
public int[] …
```
=> [1365] How Many Numbers Are Smaller Than the Current Number

dlek-user/[1370] Increasing Decreasing String
You are given a string `s`. Reorder the string using the following algorithm:
1. Remove the **smallest** character from `s` and **append** it to the result.
2. Remove the **smallest** character from `s` that is greater than the last appended character, and **append** it to the result.
3. Repeat step 2 until no more characters can be removed.
4. Remove the **largest** character from `s` and **append** it to the result.
5. Remove the **largest** character from `s` that is smaller than the last appended character, and **append** it to the result.
6. Repeat step 5 until no more characters can be removed.
7. Repeat steps 1 through 6 until all characters from `s` have been removed.
If the smallest or largest character appears more than once, you may choose any occurrence to append to the …
=> [1370] Increasing Decreasing String

dlek-user/[1374] Generate a String With Characters That Have Odd Counts
Given an integer `n`, return _a string with `n` characters such that each character in such string occurs **an odd number of times**_.
The returned string must contain only lowercase English letters. If there are multiples valid strings, return any of them.  
> Input: n = 4
> Output: "pppz"
> Explanation: "pppz" is a valid string since the character 'p' occurs three times and the character 'z' occurs once. Note that there are many other valid strings such as "ohhh" and "love".
> Input: n = 2
> Output: "xy"
> Explanation: "xy" is a valid string since the characters 'x' and 'y' occur once. Note that there are many other valid strings such as "ag" and "ur".
> Input: n = 7
> Output: "holasss"
```
public String generateTheString(int n) {
StringBuilder result = new …
```
=> [1374] Generate a String With Characters That Have Odd Counts

dlek-user/[1379] Find a Corresponding Node of a Binary Tree in a Clone of That Tree
Given two binary trees `original` and `cloned` and given a reference to a node `target` in the original tree.
The `cloned` tree is a **copy of** the `original` tree.
Return _a reference to the same node_ in the `cloned` tree.
**Note** that you are **not allowed** to change any of the two trees or the `target` node and the answer **must be** a reference to a node in the `cloned` tree.
> Input: tree = [7,4,3,null,null,6,19], target = 3
> Output: 3
> Explanation: In all examples the original and cloned trees are shown. The target node is a green node from the original tree. The answer is the yellow node from the cloned tree.
> Input: tree = [7], target =  7
> Output: 7
> Input: tree = [8,null,6,null,5,null,4,null,3,null,2,null,1], target = 4
> Output: 4
```
public final …
```
=> [1379] Find a Corresponding Node of a Binary Tree in a Clone of That Tree

dlek-user/[1380] Lucky Numbers in a Matrix
Given an `m x n` matrix of **distinct** numbers, return _all **lucky numbers** in the matrix in **any** order._
A **lucky number** is an element of the matrix such that it is the minimum element in its row and maximum in its column.
> Input: matrix = [[3,7,8],[9,11,13],[15,16,17]]
> Output: [15]
> Explanation: 15 is the only lucky number since it is the minimum in its row and the maximum in its column.
> Input: matrix = [[1,10,4,2],[9,3,8,7],[15,16,17,12]]
> Output: [12]
> Explanation: 12 is the only lucky number since it is the minimum in its row and the maximum in its column.
> Input: matrix = [[7,8],[1,2]]
> Output: [7]
> Explanation: 7 is the only lucky number since it is the minimum in its row and the maximum in its column.
```
public List<Integer> …
```
=> [1380] Lucky Numbers in a Matrix

dlek-user/[1389] Create Target Array in the Given Order
Given two arrays of integers `nums` and `index`. Your task is to create _target_ array under the following rules:
- Initially target array is empty.
- From left to right read nums[i] and index[i], insert at index `index[i]` the value `nums[i]` in _target_ array.
- Repeat the previous step until there are no elements to read in `nums` and `index`.
Return the _target_ array.
It is guaranteed that the insertion operations will be valid.
> Input: nums = [0,1,2,3,4], index = [0,1,2,2,1]
> Output: [0,4,1,3,2]
> Explanation:
> nums       index     target
> 0            0        [0]
> 1            1        [0,1]
> 2            2        [0,1,2]
> 3            2        [0,1,3,2]
> 4            1        [0,4,1,3,2]
> Input: nums = [1,2,3,4,0], index = [0,1,2,3,0]
> Output: [0,1,2,3,4]
> Explanation: …
=> [1389] Create Target Array in the Given Order

dlek-user/[1394] Find Lucky Integer in an Array
Given an array of integers `arr`, a **lucky integer** is an integer that has a frequency in the array equal to its value.
Return _the largest **lucky integer** in the array_. If there is no **lucky integer** return `-1`.
> Input: arr = [2,2,3,4]
> Output: 2
> Explanation: The only lucky number in the array is 2 because frequency[2] == 2.
> Input: arr = [1,2,2,3,3,3]
> Output: 3
> Explanation: 1, 2 and 3 are all lucky numbers, return the largest of them.
> Input: arr = [2,2,2,3,3]
> Output: -1
> Explanation: There are no lucky numbers in the array.
```
public int findLucky(int[] arr) {
Map<Integer, Integer> frequencyMap = new HashMap<>();
frequencyMap.put(num, frequencyMap.getOrDefault(num, 0) + 1);
}
int largestLucky = -1;
for (Map.Entry<Integer, …
```
=> [1394] Find Lucky Integer in an Array

dlek-user/[1403] Minimum Subsequence in Non-Increasing Order
Given the array `nums`, obtain a subsequence of the array whose sum of elements is **strictly greater** than the sum of the non included elements in such subsequence. 
If there are multiple solutions, return the subsequence with **minimum size** and if there still exist multiple solutions, return the subsequence with the **maximum total sum** of all its elements. A subsequence of an array can be obtained by erasing some (possibly zero) elements from the array. 
Note that the solution with the given constraints is guaranteed to be **unique**. Also return the answer sorted in **non-increasing** order.
> Input: nums = [4,3,10,9,8]
> Output: [10,9] 
> Explanation: The subsequences [10,9] and [10,8] are minimal such that the sum of their elements is strictly greater than the sum of elements …
=> [1403] Minimum Subsequence in Non-Increasing Order

dlek-user/[1408] String Matching in an Array
Given an array of string `words`, return _all strings in_ `words` _that is a **substring** of another word_. You can return the answer in **any order**.
A **substring** is a contiguous sequence of characters within a string
> Input: words = ["mass","as","hero","superhero"]
> Output: ["as","hero"]
> Explanation: "as" is substring of "mass" and "hero" is substring of "superhero".
> ["hero","as"] is also a valid answer.
> Input: words = ["leetcode","et","code"]
> Output: ["et","code"]
> Explanation: "et", "code" are substring of "leetcode".
> Input: words = ["blue","green","bu"]
> Output: []
> Explanation: No string of words is substring of another string.
```
public List<String> stringMatching(String[] words) {
for (int i = 0; i < …
```
=> [1408] String Matching in an Array

dlek-user/[1413] Minimum Value to Get Positive Step by Step Sum
Given an array of integers `nums`, you start with an initial **positive** value _startValue_.
In each iteration, you calculate the step by step sum of _startValue_ plus elements in `nums` (from left to right).
Return the minimum **positive** value of _startValue_ such that the step by step sum is never less than 1.
> Input: nums = [-3,2,-3,4,2]
> Output: 5
> Explanation: If you choose startValue = 4, in the third iteration your step by step sum is less than 1.
> step by step sum
> startValue = 4 | startValue = 5 | nums
>   (4 -3 ) = 1  | (5 -3 ) = 2    |  -3
>   (1 +2 ) = 3  | (2 +2 ) = 4    |   2
>   (3 -3 ) = 0  | (4 -3 ) = 1    |  -3
>   (0 +4 ) = 4  | (1 +4 ) = 5    |   4
>   (4 +2 ) = 6  | (5 +2 ) = 7    |   2
> Input: nums = [1,2]
> Output: 1
> Explanation: Minimum start value …
=> [1413] Minimum Value to Get Positive Step by Step Sum

dlek-user/[1417] Reformat The String
You are given an alphanumeric string `s`. (**Alphanumeric string** is a string consisting of lowercase English letters and digits).
You have to find a permutation of the string where no letter is followed by another letter and no digit is followed by another digit. That is, no two adjacent characters have the same type.
Return _the reformatted string_ or return **an empty string** if it is impossible to reformat the string.
> Input: s = "a0b1c2"
> Output: "0a1b2c"
> Explanation: No two adjacent characters have the same type in "0a1b2c". "a0b1c2", "0a1b2c", "0c2a1b" are also valid permutations.
> Input: s = "leetcode"
> Output: ""
> Explanation: "leetcode" has only characters so we cannot separate them by digits.
> Input: s = "1229857369"
> Output: ""
> Explanation: "1229857369" has only …
=> [1417] Reformat The String

dlek-user/[1422] Maximum Score After Splitting a String
Given a string `s` of zeros and ones, return _the maximum score after splitting the string into two **non-empty** substrings_ (i.e. **left** substring and **right** substring).
The score after splitting a string is the number of **zeros** in the **left** substring plus the number of **ones** in the **right** substring.
> Input: s = "011101"
> Output: 5 
> All possible ways of splitting s into two non-empty substrings are:
> left = "0" and right = "11101", score = 1 + 4 = 5 
> left = "01" and right = "1101", score = 1 + 3 = 4 
> left = "011" and right = "101", score = 1 + 2 = 3 
> left = "0111" and right = "01", score = 1 + 1 = 2 
> left = "01110" and right = "1", score = 2 + 1 = 3
> Input: s = "00111"
> Output: 5
> Explanation: When left = "00" and right = "111", we get …
=> [1422] Maximum Score After Splitting a String

dlek-user/[1431] Kids With the Greatest Number of Candies
There are `n` kids with candies. You are given an integer array `candies`, where each `candies[i]` represents the number of candies the `ith` kid has, and an integer `extraCandies`, denoting the number of extra candies that you have.
Return _a boolean array_ `result` _of length_ `n`, _where_ `result[i]` _is_ `true` _if__, after giving the_ `ith` _kid all the_ `extraCandies`, _they will have the **greatest** number of candies among all the kids, or_ `false` _otherwise_.
Note that **multiple** kids can have the **greatest** number of candies.
> Input: candies = [2,3,5,1,3], extraCandies = 3
> Output: [true,true,true,false,true] 
> Explanation: If you give all extraCandies to:
> - Kid 1, they will have 2 + 3 = 5 candies, which is the greatest among the kids.
> - Kid 2, they will have 3 + 3 = …
=> [1431] Kids With the Greatest Number of Candies

dlek-user/[1437] Check If All 1's Are at Least Length K Places Away
Given an binary array `nums` and an integer `k`, return `true` _if all_ `1`'s _are at least_ `k` _places away from each other, otherwise return_ `false`.
> Input: nums = [1,0,0,0,1,0,0,1], k = 2
> Output: true
> Explanation: Each of the 1s are at least 2 places away from each other.
> Input: nums = [1,0,0,1,0,1], k = 2
> Explanation: The second 1 and third 1 are only one apart from each other.
```
public class Solution {
public boolean kLengthApart(int[] nums, int k) {
int prevIndex = -1; 
if (nums[i] == 1) {
if (prevIndex != -1 && (i - prevIndex - 1) < k) {
return false; 
}
prevIndex = i; 
}
}
return true; 
}
}
```
#
```
int prevIndex = -1;
```
prevIndex 변수를 사용하여 마지막으로 발견한 1의 인덱스를 저장.
처음에는 -1로 설정하여 첫 번째 1을 찾을 때 문제없도록 함.
```
for (int …
```
=> [1437] Check If All 1's Are at Least Length K Places Away

dlek-user/[1446] Consecutive Characters
The **power** of the string is the maximum length of a non-empty substring that contains only one unique character.
Given a string `s`, return _the **power** of_ `s`.
> Input: s = "leetcode"
> Output: 2
> Explanation: The substring "ee" is of length 2 with the character 'e' only.
> Input: s = "abbcccddddeeeeedcba"
> Output: 5
> Explanation: The substring "eeeee" is of length 5 with the character 'e' only.
```
public int maxPower(String s) {
int maxPower = 1, currentPower = 1;
for (int i = 1; i < s.length(); i++) {
if (s.charAt(i) == s.charAt(i - 1)) {
currentPower++;
maxPower = Math.max(maxPower, currentPower);
} else {
currentPower = 1;
}
}
return maxPower;
}
}
```
#
```
int maxPower = 1, currentPower = 1;
```
maxPower = 1 최대 길이 저장 변수
currentPower = 1 현재 연속된 동일 문자 개수 저장 …
=> [1446] Consecutive Characters

dlek-user/[1450] Number of Students Doing Homework at a Given Time
Given two integer arrays `startTime` and `endTime` and given an integer `queryTime`.
The `ith` student started doing their homework at the time `startTime[i]` and finished it at time `endTime[i]`.
Return _the number of students_ doing their homework at time `queryTime`. More formally, return the number of students where `queryTime` lays in the interval `[startTime[i], endTime[i]]` inclusive.
> Input: startTime = [1,2,3], endTime = [3,2,7], queryTime = 4
> Output: 1
> Explanation: We have 3 students where:
> The first student started doing homework at time 1 and finished at time 3 and wasn't doing anything at time 4.
> The second student started doing homework at time 2 and finished at time 2 and also wasn't doing anything at time 4.
> The third student started doing homework at time 3 and …
=> [1450] Number of Students Doing Homework at a Given Time

dlek-user/[1455] Check If a Word Occurs As a Prefix of Any Word in a Sentence
Given a `sentence` that consists of some words separated by a **single space**, and a `searchWord`, check if `searchWord` is a prefix of any word in `sentence`.
Return _the index of the word in_ `sentence` _(1-indexed) where_ `searchWord` _is a prefix of this word_. If `searchWord` is a prefix of more than one word, return the index of the first word (**minimum index**). If there is no such word return `-1`.
A **prefix** of a string `s` is any leading contiguous substring of `s`.
> Input: sentence = "i love eating burger", searchWord = "burg"
> Output: 4
> Explanation: "burg" is prefix of "burger" which is the 4th word in the sentence.
> Input: sentence = "this problem is an easy problem", searchWord = "pro"
> Output: 2
> Explanation: "pro" is prefix of "problem" which is the 2nd and the …
=> [1455] Check If a Word Occurs As a Prefix of Any Word in a Sentence

dlek-user/[1460] Make Two Arrays Equal by Reversing Subarrays
You are given two integer arrays of equal length `target` and `arr`. In one step, you can select any **non-empty subarray** of `arr` and reverse it. You are allowed to make any number of steps.
Return `true` _if you can make_ `arr` _equal to_ `target` _or_ `false` _otherwise_.
> Input: target = [1,2,3,4], arr = [2,4,1,3]
> Output: true
> Explanation: You can follow the next steps to convert arr to target:
> 1- Reverse subarray [2,4,1], arr becomes [1,4,2,3]
> 2- Reverse subarray [4,2], arr becomes [1,2,4,3]
> 3- Reverse subarray [4,3], arr becomes [1,2,3,4]
> There are multiple ways to convert arr to target, this is not the only way to do so.
> Input: target = [7], arr = [7]
> Output: true
> Explanation: arr is equal to target without any reverses.
> Input: target = [3,7,9], arr = …
=> [1460] Make Two Arrays Equal by Reversing Subarrays

dlek-user/[1470] Shuffle the Array
Given the array `nums` consisting of `2n` elements in the form `[x1,x2,...,xn,y1,y2,...,yn]`.
_Return the array in the form_ `[x1,y1,x2,y2,...,xn,yn]`.
> Input: nums = [2,5,1,3,4,7], n = 3
> Output: [2,3,5,4,1,7] 
> Explanation: Since x1=2, x2=5, x3=1, y1=3, y2=4, y3=7 then the answer is [2,3,5,4,1,7].
> Input: nums = [1,2,3,4,4,3,2,1], n = 4
> Output: [1,4,2,3,3,2,4,1]
> Input: nums = [1,1,2,2], n = 2
> Output: [1,2,1,2]
```
public int[] shuffle(int[] nums, int n) {
int[] result = new int[2 * n];
result[2 * i] = nums[i];
result[2 * i + 1] = nums[i + n];
}
return result;
}
}
```
#
```
int[] result = new int[2 * n];
```
최종적으로 변환된 배열을 저장할 result를 생성합니다.
원래 nums 배열의 길이가 2n이므로 result도 같은 크기로 선언합니다.
```
result[2 * i] …
```
=> [1470] Shuffle the Array

dlek-user/[1475] Final Prices With a Special Discount in a Shop
You are given an integer array `prices` where `prices[i]` is the price of the `ith` item in a shop.
There is a special discount for items in the shop. If you buy the `ith` item, then you will receive a discount equivalent to `prices[j]` where `j` is the minimum index such that `j > i` and `prices[j] <= prices[i]`. Otherwise, you will not receive any discount at all.
Return an integer array `answer` where `answer[i]` is the final price you will pay for the `ith` item of the shop, considering the special discount.
> Input: prices = [8,4,6,2,3]
> Output: [4,2,4,2,3]
> For item 0 with price[0]=8 you will receive a discount equivalent to prices[1]=4, therefore, the final price you will pay is 8 - 4 = 4.
> For item 1 with price[1]=4 you will receive a discount equivalent to …
=> [1475] Final Prices With a Special Discount in a Shop

dlek-user/[1480] Running Sum of 1d Array
Given an array `nums`. We define a running sum of an array as `runningSum[i] = sum(nums[0]…nums[i])`.
Return the running sum of `nums`.
> Output: [1,3,6,10]
> Explanation: Running sum is obtained as follows: [1, 1+2, 1+2+3, 1+2+3+4].
> Input: nums = [1,1,1,1,1]
> Output: [1,2,3,4,5]
> Explanation: Running sum is obtained as follows: [1, 1+1, 1+1+1, 1+1+1+1, 1+1+1+1+1].
> Input: nums = [3,1,2,10,1]
> Output: [3,4,6,16,17]
```
public int[] runningSum(int[] nums) {
int[] result = new int[n];
result[0] = nums[0];
for (int i = 1; i < n; i++) {
result[i] = result[i - 1] + nums[i];
}
return result;
}
}
```
#
```
int[] result = new int[n];
```
nums의 길이를 n에 저장
결과를 저장할 result 배열 선언
```
result[0] = nums[0];
```
첫 번째 …
=> [1480] Running Sum of 1d Array

dlek-user/[1486] XOR Operation in an Array
You are given an integer `n` and an integer `start`.
Define an array `nums` where `nums[i] = start + 2 * i` (**0-indexed**) and `n == nums.length`.
Return _the bitwise XOR of all elements of_ `nums`.
> Input: n = 5, start = 0
> Output: 8
> Explanation: Array nums is equal to [0, 2, 4, 6, 8] where (0 ^ 2 ^ 4 ^ 6 ^ 8) = 8.
> Where "^" corresponds to bitwise XOR operator.
> Input: n = 4, start = 3
> Output: 8
> Explanation: Array nums is equal to [3, 5, 7, 9] where (3 ^ 5 ^ 7 ^ 9) = 8.
> 
```
public int xorOperation(int n, int start) {
int xorResult = 0;
xorResult ^= (start + 2 * i);
}
return xorResult;
}
}
```
#
```
int xorResult = 0;
```
XOR 연산의 기본 값은 0 입니다.(왜냐하면 x ^ 0 = x이므로)
```
xorResult ^= (start + 2 * i);
} …
```
=> [1486] XOR Operation in an Array

dlek-user/[1491] Average Salary Excluding the Minimum and Maximum Salary
You are given an array of **unique** integers `salary` where `salary[i]` is the salary of the `ith` employee.
Return _the average salary of employees excluding the minimum and maximum salary_. Answers within `10-5` of the actual answer will be accepted.
> Input: salary = [4000,3000,1000,2000]
> Output: 2500.00000
> Explanation: Minimum salary and maximum salary are 1000 and 4000 respectively.
> Average salary excluding minimum and maximum salary is (2000+3000) / 2 = 2500
> Input: salary = [1000,2000,3000]
> Output: 2000.00000
> Explanation: Minimum salary and maximum salary are 1000 and 3000 respectively.
> Average salary excluding minimum and maximum salary is (2000) / 1 = 2000
```
public double average(int[] salary) {
int minSalary = Integer.MAX_VALUE, maxSalary = …
```
=> [1491] Average Salary Excluding the Minimum and Maximum Salary

dlek-user/[1496] Path Crossing
Given a string `path`, where `path[i] = 'N'`, `'S'`, `'E'` or `'W'`, each representing moving one unit north, south, east, or west, respectively. You start at the origin `(0, 0)` on a 2D plane and walk on the path specified by `path`.
Return `true` _if the path crosses itself at any point, that is, if at any time you are on a location you have previously visited._ Return `false` otherwise.
> Input: path = "NES"
> Output: false 
> Explanation: Notice that the path doesn't cross any point more than once.
> Input: path = "NESWW"
> Output: true
> Explanation: Notice that the path visits the origin twice.
```
public boolean isPathCrossing(String path) {
Set<String> visited = new HashSet<>();
int x = 0, y = 0;
visited.add(x + "," + y);
for (char dir : path.toCharArray()) {
if …
```
=> [1496] Path Crossing

dlek-user/[1502] Can Make Arithmetic Progression From Sequence
A sequence of numbers is called an **arithmetic progression** if the difference between any two consecutive elements is the same.
Given an array of numbers `arr`, return `true` _if the array can be rearranged to form an **arithmetic progression**. Otherwise, return_ `false`.
> Input: arr = [3,5,1]
> Output: true
> Explanation: We can reorder the elements as [1,3,5] or [5,3,1] with differences 2 and -2 respectively, between each consecutive elements.
> Input: arr = [1,2,4]
> Explanation: There is no way to reorder the elements to obtain an arithmetic progression.
```
public boolean canMakeArithmeticProgression(int[] arr) {
Arrays.sort(arr);
int d = arr[1] - arr[0];
for (int i = 2; i < arr.length; i++) {
if (arr[i] - arr[i - 1] != d) {
return false;
}
} …
```
=> [1502] Can Make Arithmetic Progression From Sequence

dlek-user/[1507] Reformat Date
Given a `date` string in the form `Day Month Year`, where:
- `Day` is in the set `{"1st", "2nd", "3rd", "4th", ..., "30th", "31st"}`.
- `Month` is in the set `{"Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"}`.
- `Year` is in the range `[1900, 2100]`.
Convert the date string to the format `YYYY-MM-DD`, where:
- `YYYY` denotes the 4 digit year.
- `MM` denotes the 2 digit month.
- `DD` denotes the 2 digit day.
> Input: date = "20th Oct 2052"
> Output: "2052-10-20"
> Input: date = "6th Jun 1933"
> Output: "1933-06-06"
> Input: date = "26th May 1960"
> Output: "1960-05-26"
```
public String reformatDate(String date) {
HashMap<String, String> monthMap = new HashMap<>();
monthMap.put("Jan", "01"); monthMap.put("Feb", "02"); monthMap.put("Mar", …
```
=> [1507] Reformat Date

dlek-user/[1512] Number of Good Pairs
Given an array of integers `nums`, return _the number of **good pairs**_.
A pair `(i, j)` is called good if `nums[i] == nums[j]` and `i < j`.
> Input: nums = [1,2,3,1,1,3]
> Output: 4
> Explanation: There are 4 good pairs (0,3), (0,4), (3,4), (2,5) 0-indexed.
> Input: nums = [1,1,1,1]
> Output: 6
> Explanation: Each pair in the array are good.
> Output: 0
```
public int numIdenticalPairs(int[] nums) {
HashMap<Integer, Integer> freqMap = new HashMap<>();
int count = 0;
if (freqMap.containsKey(num)) {
count += freqMap.get(num);
}
freqMap.put(num, freqMap.getOrDefault(num, 0) + 1);
}
return count;
}
}
```
#
```
HashMap<Integer, Integer> freqMap = new HashMap<>();
```
해시맵(HashMap) 생성, freqMap을 사용하여 nums[i]의 빈도수를 저장
```
for (int …
```
=> [1512] Number of Good Pairs

dlek-user/[1518] Water Bottles
There are `numBottles` water bottles that are initially full of water. You can exchange `numExchange` empty water bottles from the market with one full water bottle.
The operation of drinking a full water bottle turns it into an empty bottle.
Given the two integers `numBottles` and `numExchange`, return _the **maximum** number of water bottles you can drink_.
> Input: numBottles = 9, numExchange = 3
> Output: 13
> Explanation: You can exchange 3 empty bottles to get 1 full water bottle.
> Number of water bottles you can drink: 9 + 3 + 1 = 13.
> Input: numBottles = 15, numExchange = 4
> Output: 19
> Explanation: You can exchange 4 empty bottles to get 1 full water bottle. 
> Number of water bottles you can drink: 15 + 3 + 1 = 19.
> 
```
public int numWaterBottles(int …
```
=> [1518] Water Bottles

dlek-user/[1523] Count Odd Nubmers in an Interval Range
Given two non-negative integers `low` and `high`. Return the _count of odd numbers between_ `low` _and_ `high` _(inclusive)_.
> Input: low = 3, high = 7
> Output: 3
> Explanation: The odd numbers between 3 and 7 are [3,5,7].
> Input: low = 8, high = 10
> Output: 1
> Explanation: The odd numbers between 8 and 10 are [9].
```
public int countOdds(int low, int high) {
return (high - low) / 2 + (low % 2 == 1 || high % 2 == 1 ? 1 : 0);
}
}
```
#
```
(high - low) / 2
```
low부터 high까지 홀수와 짝수가 번갈아 나열됨
따라서 (high - low) / 2로 먼저 기본적인 개수를 구함
```
(low % 2 == 1 || high % 2 == 1 ? 1 : 0)
```
low나 high 중 하나라도 홀수이면 추가적인 홀수가 존재함
이 경우 +1을 추가하여 올바른 개수를 반환
=> [1523] Count Odd Nubmers in an Interval Range

dlek-user/[1528] Shuffle String
You are given a string `s` and an integer array `indices` of the **same length**. The string `s` will be shuffled such that the character at the `ith` position moves to `indices[i]` in the shuffled string.
Return _the shuffled string_.
> Input: s = "codeleet", indices = [4,5,6,7,0,2,1,3]
> Output: "leetcode"
> Explanation: As shown, "codeleet" becomes "leetcode" after shuffling.
> Input: s = "abc", indices = [0,1,2]
> Output: "abc"
> Explanation: After shuffling, each character remains in its position.
> 
```
public String restoreString(String s, int[] indices) {
char[] result = new char[s.length()];
result[indices[i]] = s.charAt(i);
}
return new String(result);
}
}
```
#
```
char[] result = new char[s.length()];
```
char[] result …
=> [1528] Shuffle String

dlek-user/[1534] Count Good Triplets
Given an array of integers `arr`, and three integers `a`, `b` and `c`. You need to find the number of good triplets.
A triplet `(arr[i], arr[j], arr[k])` is good if the following conditions are true:
- `0 <= i < j < k < arr.length`
- `|arr[i] - arr[j]| <= a`
- `|arr[j] - arr[k]| <= b`
- `|arr[i] - arr[k]| <= c`
Where `|x|` denotes the absolute value of `x`.
Return _the number of good triplets._
> Input: arr = [3,0,1,1,9,7], a = 7, b = 2, c = 3
> Output: 4
> Explanation: There are 4 good triplets: [(3,0,1), (3,0,1), (3,1,1), (0,1,1)].
> Input: arr = [1,1,2,2,3], a = 0, b = 0, c = 1
> Output: 0
> Explanation: No triplet satisfies all conditions.
```
public int countGoodTriplets(int[] arr, int a, int b, int c) {
int count = 0;
for (int i = 0; i < n - 2; …
```
=> [1534] Count Good Triplets

dlek-user/[1544] Make The String Great
Given a string `s` of lower and upper case English letters.
A good string is a string which doesn't have two adjacent characters `s[i]` and `s[i + 1]` where:
- `0 <= i <= s.length - 2`
- `s[i]` is a lower-case letter and `s[i + 1]` is the same letter but in upper-case or **vice-versa**.
To make the string good, you can choose **two adjacent** characters that make the string bad and remove them. You can keep doing this until the string becomes good.
Return _the string_ after making it good. The answer is guaranteed to be unique under the given constraints.
**Notice** that an empty string is also good.
> Input: s = "leEeetcode"
> Output: "leetcode"
> Explanation: In the first step, either you choose i = 1 or i = 2, both will result "leEeetcode" to be reduced to "leetcode".
> Input: s = …
=> [1544] Make The String Great

dlek-user/[1550] Three Consecutive Odds
Given an integer array `arr`, return `true` if there are three consecutive odd numbers in the array. Otherwise, return `false`.
> Input: arr = [2,6,4,1]
> Explanation: There are no three consecutive odds.
> Input: arr = [1,2,34,3,4,5,7,23,12]
> Output: true
> Explanation: [5,7,23] are three consecutive odds.
```
public boolean threeConsecutiveOdds(int[] arr) {
int count = 0;
if (num % 2 == 1) {
count++;
if (count == 3) return true;
} else {
count = 0;
}
}
return false;
}
}
```
#
```
int count = 0;
```
count 변수를 선언하여 연속된 홀수 개수를 센다.
```
if (num % 2 == 1) {
count++;
```
배열을 O(n)으로 순회하며 홀수일 경우 count++, 짝수일 경우 count 초기화.
```
if (count == 3) return true;
```
count == 3이면 true 반환.
```
else {
count = 0;
}
```
끝까지 반복 후에도 …
=> [1550] Three Consecutive Odds

dlek-user/[1556] Thousand Separator
Given an integer `n`, add a dot (".") as the thousands separator and return it in string format.
> Input: n = 987
> Output: "987"
> Input: n = 1234
> Output: "1.234"
```
public String thousandSeparator(int n) {
String numStr = String.valueOf(n);
StringBuilder sb = new StringBuilder();
int count = 0;
for (int i = numStr.length() - 1; i >= 0; i--) {
sb.append(numStr.charAt(i));
count++;
if (count % 3 == 0 && i != 0) {
sb.append('.');
}
}
return sb.reverse().toString();
}
}
```
#
```
String numStr = String.valueOf(n);
StringBuilder sb = new StringBuilder();
int count = 0;
```
숫자 n을 문자열로 변환 (String.valueOf(n))
```
for (int i = numStr.length() - 1; i >= 0; i--) {
sb.append(numStr.charAt(i));
count++;
if (count % 3 == 0 && i != 0) {
sb.append('.');
}
}
```
뒤에서부터 한 자리씩 …
=> [1556] Thousand Separator

dlek-user/[1576] Replace All ?'s to Avoid Consecutive Repeating Characters
Given a string s containing only lowercase English letters and the `'?'` character, convert **all** the `'?'` characters into lowercase letters such that the final string does not contain any **consecutive repeating** characters. You **cannot** modify the non `'?'` characters.
It is **guaranteed** that there are no consecutive repeating characters in the given string **except** for `'?'`.
Return _the final string after all the conversions (possibly zero) have been made_. If there is more than one solution, return **any of them**. It can be shown that an answer is always possible with the given constraints.
> Input: s = "?zs"
> Output: "azs"
> Explanation: There are 25 solutions for this problem. From "azs" to "yzs", all are valid. Only "z" is an invalid modification as the string will …
=> [1576] Replace All ?'s to Avoid Consecutive Repeating Characters

dlek-user/[1592] Rearrange Spaces Between Words
You are given a string `text` of words that are placed among some number of spaces. Each word consists of one or more lowercase English letters and are separated by at least one space. It's guaranteed that `text` **contains at least one word**.
Rearrange the spaces so that there is an **equal** number of spaces between every pair of adjacent words and that number is **maximized**. If you cannot redistribute all the spaces equally, place the **extra spaces at the end**, meaning the returned string should be the same length as `text`.
Return _the string after rearranging the spaces_.
> Input: text = "  this   is  a sentence "
> Output: "this   is   a   sentence"
> Explanation: There are a total of 9 spaces and 4 words. We can evenly divide the 9 spaces between the words: 9 / (4-1) = 3 …
=> [1592] Rearrange Spaces Between Words

dlek-user/[1603] Design Parking System
Design a parking system for a parking lot. The parking lot has three kinds of parking spaces: big, medium, and small, with a fixed number of slots for each size.
Implement the `ParkingSystem` class:
- `ParkingSystem(int big, int medium, int small)` Initializes object of the `ParkingSystem` class. The number of slots for each parking space are given as part of the constructor.
- `bool addCar(int carType)` Checks whether there is a parking space of `carType` for the car that wants to get into the parking lot. `carType` can be of three kinds: big, medium, or small, which are represented by `1`, `2`, and `3` respectively. **A car can only park in a parking space of its** `carType`. If there is no space available, return `false`, else park the car in that size space and return `true`.
> Input …
=> [1603] Design Parking System

dlek-user/[2] Add Two Numbers
You are given two **non-empty** linked lists representing two non-negative integers. The digits are stored in **reverse order**, and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list.
You may assume the two numbers do not contain any leading zero, except the number 0 itself.
> Input: l1 = [2,4,3], l2 = [5,6,4]
> Output: [7,0,8]
> Explanation: 342 + 465 = 807.
> Input: l1 = [0], l2 = [0]
> Output: [0]
> Input: l1 = [9,9,9,9,9,9,9], l2 = [9,9,9,9]
> Output: [8,9,9,9,0,0,0,1]
```
public ListNode addTwoNumbers(ListNode l1, ListNode l2) {
ListNode dummyHead = new ListNode(0);
ListNode current = dummyHead;
int carry = 0;
while (l1 != null || l2 != null || carry != 0) {
int sum = carry;
if (l1 != null) {
sum += l1.val;
l1 = …
```
=> [2] Add Two Numbers

dlek-user/[3] Longest Substring Without Repeating Characters
Given a string `s`, find the length of the **longest substring** without duplicate characters.
> Input: s = "abcabcbb"
> Output: 3
> Explanation: The answer is "abc", with the length of 3.
> Input: s = "bbbbb"
> Output: 1
> Explanation: The answer is "b", with the length of 1.
> Input: s = "pwwkew"
> Output: 3
> Explanation: The answer is "wke", with the length of 3.
> Notice that the answer must be a substring, "pwke" is a subsequence and not a substring.
```
public int lengthOfLongestSubstring(String s) {
HashSet<Character> set = new HashSet<>();
int left = 0, maxLength = 0;
for (int right = 0; right < s.length(); right++) {
while (set.contains(s.charAt(right))) {
set.remove(s.charAt(left));
left++;
}
set.add(s.charAt(right));
maxLength = Math.max(maxLength, right - …
```
=> [3] Longest Substring Without Repeating Characters

dlek-user/[5] Longest Palindromic Substring
Given a string `s`, return _the longest palindromic substring_ in `s`.
> Input: s = "babad"
> Output: "bab"
> Explanation: "aba" is also a valid answer.
> Input: s = "cbbd"
> Output: "bb"
```
public String longestPalindrome(String s) {
if (s == null || s.length() < 1) return "";
int start = 0, end = 0;
int len1 = expandFromCenter(s, i, i);
int len2 = expandFromCenter(s, i, i + 1);
int len = Math.max(len1, len2);
if (len > end - start) {
start = i - (len - 1) / 2;
end = i + len / 2;
}
}
return s.substring(start, end + 1);
}
private int expandFromCenter(String s, int left, int right) {
while (left >= 0 && right < s.length() && s.charAt(left) == s.charAt(right)) {
left--;
right++;
}
return right - left - 1;
}
}
```
#
```
for (int i = 0; …
```
=> [5] Longest Palindromic Substring

dlek-user/[6] Zigzag Conversion
The string `"PAYPALISHIRING"` is written in a zigzag pattern on a given number of rows like this: (you may want to display this pattern in a fixed font for better legibility)
> P   A   H   N
> A P L S I I G
> Y   I   R
And then read line by line: `"PAHNAPLSIIGYIR"`
Write the code that will take a string and make this conversion given a number of rows:
> string convert(string s, int numRows);
> Input: s = "PAYPALISHIRING", numRows = 3
> Output: "PAHNAPLSIIGYIR"
> Input: s = "PAYPALISHIRING", numRows = 4
> Output: "PINALSIGYAHRPI"
> Explanation:
> P     I    N
> A   L S  I G
> Y A   H R
> P     I
> Input: s = "A", numRows = 1
> Output: "A"
```
public String convert(String s, int numRows) {
if (numRows == 1 || s.length() <= numRows) return s;
StringBuilder[] rows = new …
```
=> [6] Zigzag Conversion

dlek-user/[7] Reverse Integer
Given a signed 32-bit integer `x`, return `x` _with its digits reversed_. If reversing `x` causes the value to go outside the signed 32-bit integer range `[-231, 231 - 1]`, then return `0`.
**Assume the environment does not allow you to store 64-bit integers (signed or unsigned)**.
> Input: x = 123
> Output: 321
> Input: x = -123
> Output: -321
> Input: x = 120
> Output: 21
```
public int reverse(int x) {
int rev = 0;
while (x != 0) {
int digit = x % 10;
x /= 10;
if (rev > Integer.MAX_VALUE / 10 || (rev == Integer.MAX_VALUE / 10 && digit > 7)) return 0;
if (rev < Integer.MIN_VALUE / 10 || (rev == Integer.MIN_VALUE / 10 && digit < -8)) return 0;
rev = rev * 10 + digit;
}
return rev;
}
}
```
#
```
int digit = x % 10;
x /= 10;
```
x % 10 으로 마지막 자리를 가져오고, x /= 10 으로 제거.
``` …
```
=> [7] Reverse Integer

dlek-user/[8] String to Integer (atoi)
Implement the `myAtoi(string s)` function, which converts a string to a 32-bit signed integer.
The algorithm for `myAtoi(string s)` is as follows:
1. **Whitespace**: Ignore any leading whitespace (`" "`).
2. **Signedness**: Determine the sign by checking if the next character is `'-'` or `'+'`, assuming positivity if neither present.
3. **Conversion**: Read the integer by skipping leading zeros until a non-digit character is encountered or the end of the string is reached. If no digits were read, then the result is 0.
4. **Rounding**: If the integer is out of the 32-bit signed integer range `[-2^31, 2^31 - 1]`, then round the integer to remain in the range. Specifically, integers less than `-2^31` should be rounded to `-2^31`, and integers greater than `2^31 - 1` should be rounded to …
=> [8] String to Integer (atoi)

dlek-user/[11] Container With Most Water
You are given an integer array `height` of length `n`. There are `n` vertical lines drawn such that the two endpoints of the `ith` line are `(i, 0)` and `(i, height[i])`.
Find two lines that together with the x-axis form a container, such that the container contains the most water.
Return _the maximum amount of water a container can store_.
**Notice** that you may not slant the container.
> Input: height = [1,8,6,2,5,4,8,3,7]
> Output: 49
> Explanation: The above vertical lines are represented by array [1,8,6,2,5,4,8,3,7]. In this case, the max area of water (blue section) the container can contain is 49.
> Input: height = [1,1]
> Output: 1
```
public int maxArea(int[] height) {
int left = 0, right = height.length - 1;
int maxWater = 0;
int width = …
```
=> [11] Container With Most Water

dlek-user/[16] 3Sum Closest
Given an integer array `nums` of length `n` and an integer `target`, find three integers in `nums` such that the sum is closest to `target`.
Return _the sum of the three integers_.
You may assume that each input would have exactly one solution.
> Input: nums = [-1,2,1,-4], target = 1
> Output: 2
> Explanation: The sum that is closest to the target is 2. (-1 + 2 + 1 = 2).
> Input: nums = [0,0,0], target = 1
> Output: 0
> Explanation: The sum that is closest to the target is 0. (0 + 0 + 0 = 0).
```
public int threeSumClosest(int[] nums, int target) {
Arrays.sort(nums);
int closestSum = nums[0] + nums[1] + nums[2];
for (int i = 0; i < nums.length - 2; i++) {
int left = i + 1, right = nums.length - 1;
int sum = nums[i] + nums[left] + nums[right];
if …
```
=> [16] 3Sum Closest

dlek-user/[17] Letter Combinations of a Phone Number
Given a string containing digits from `2-9` inclusive, return all possible letter combinations that the number could represent. Return the answer in **any order.**
A mapping of digits to letters (just like on the telephone buttons) is given below. Note that 1 does not map to any letters.
> Input: digits = "23"
> Output: ["ad","ae","af","bd","be","bf","cd","ce","cf"]
> Input: digits = ""
> Output: []
> Input: digits = "2"
> Output: ["a","b","c"]
```
private static final Map<Character, String> phoneMap = new HashMap<>();
static {
phoneMap.put('2', "abc");
phoneMap.put('3', "def");
phoneMap.put('4', "ghi");
phoneMap.put('5', "jkl");
phoneMap.put('6', "mno");
phoneMap.put('7', "pqrs");
phoneMap.put('8', "tuv");
phoneMap.put('9', "wxyz");
}
public List<String> …
```
=> [17] Letter Combinations of a Phone Number

dlek-user/[19] Remove Nth Node From End of List
Given the `head` of a linked list, remove the `nth` node from the end of the list and return its head.
> Input: head = [1,2,3,4,5], n = 2
> Output: [1,2,3,5]
> Input: head = [1], n = 1
> Output: []
> Input: head = [1,2], n = 1
> Output: [1]
```
public ListNode removeNthFromEnd(ListNode head, int n) {
ListNode dummy = new ListNode(0);
dummy.next = head;
ListNode fast = dummy;
ListNode slow = dummy;
for (int i = 0; i <= n; i++) {
fast = fast.next;
}
while (fast != null) {
fast = fast.next;
slow = slow.next;
}
slow.next = slow.next.next;
return dummy.next;
}
}
```
#
```
ListNode dummy = new ListNode(0);
dummy.next = head;
```
가상의 dummy 노드 생성 (val=0, next=head).
이렇게 하면 head가 삭제되는 경우도 쉽게 처리 가능.
```
for (int i = 0; i <= n; i++) {
fast = fast.next;
}
```
fast 포인터를 n+1번 이동하여 …
=> [19] Remove Nth Node From End of List

dlek-user/[22] Generate Parentheses
Given `n` pairs of parentheses, write a function to _generate all combinations of well-formed parentheses_.
> Input: n = 3
> Output: ["((()))","(()())","(())()","()(())","()()()"]
> Input: n = 1
> Output: ["()"]
```
public List<String> generateParenthesis(int n) {
backtrack(result, "", 0, 0, n);
return result;
}
private void backtrack(List<String> result, String current, int open, int close, int max) {
if (current.length() == max * 2) {
result.add(current);
return;
}
if (open < max) {
backtrack(result, current + "(", open + 1, close, max);
}
if (close < open) {
backtrack(result, current + ")", open, close + 1, max);
}
}
}
```
#
```
backtrack(result, "", 0, 0, n);
```
결과를 저장할 List<String> …
=> [22] Generate Parentheses

dlek-user/[24] Swap Nodes in Pairs
Given a linked list, swap every two adjacent nodes and return its head. You must solve the problem without modifying the values in the list's nodes (i.e., only nodes themselves may be changed.)
> Input: head = [1,2,3,4]
> Output: [2,1,4,3]
> Explanation:
> Input: head = []
> Output: []
> Input: head = [1]
> Output: [1]
> Input: head = [1,2,3]
> Output: [2,1,3]
```
public ListNode swapPairs(ListNode head) {
if (head == null || head.next == null) {
return head;
}
ListNode first = head;
ListNode second = head.next;
first.next = swapPairs(second.next);
second.next = first;
return second;
}
}
```
#
```
if (head == null || head.next == null) {
return head;
}
```
노드가 0개이거나 1개만 남으면 더 이상 스왑할 필요가 없음.
```
ListNode first = head;
ListNode second = head.next;
```
first: 현재 위치의 첫 번째 노드. …
=> [24] Swap Nodes in Pairs

dlek-user/[29] Divide Two Integers
Given two integers `dividend` and `divisor`, divide two integers **without** using multiplication, division, and mod operator.
The integer division should truncate toward zero, which means losing its fractional part. For example, `8.345` would be truncated to `8`, and `-2.7335` would be truncated to `-2`.
Return _the **quotient** after dividing_ `dividend` _by_ `divisor`.
**Note**: Assume we are dealing with an environment that could only store integers within the **32-bit** signed integer range: `[−231, 231 − 1]`. For this problem, if the quotient is **strictly greater than** `231 - 1`, then return `231 - 1`, and if the quotient is strictly **less than** `-231`, then return `-231`.
> Input: dividend = 10, divisor = 3
> Output: 3
> Explanation: 10/3 = 3.33333.. which is truncated to 3.
> …
=> [29] Divide Two Integers

dlek-user/[31] Next Permutation
A **permutation** of an array of integers is an arrangement of its members into a sequence or linear order.
- For example, for `arr = [1,2,3]`, the following are all the permutations of `arr: [1,2,3], [1,3,2], [2, 1, 3], [2, 3, 1], [3,1,2], [3,2,1]`.
The **next permutation** of an array of integers is the next lexicographically greater permutation of its integer. More formally, if all the permutations of the array are sorted in one container according to their lexicographical order, then the **next permutation** of that array is the permutation that follows it in the sorted container. If such arrangement is not possible, the array must be rearranged as the lowest possible order (i.e., sorted in ascending order).
- For example, the next permutation of `arr = [1,2,3]` is `[1,3,2]`.
- …
=> [31] Next Permutation

dlek-user/[33] Search in Rotated Sorted Array
There is an integer array `nums` sorted in ascending order (with **distinct** values).
Prior to being passed to your function, `nums` is **possibly rotated** at an unknown pivot index `k` (`1 <= k < nums.length`) such that the resulting array is `[nums[k], nums[k+1], ..., nums[n-1], nums[0], nums[1], ..., nums[k-1]]` (**0-indexed**). For example, `[0,1,2,4,5,6,7]` might be rotated at pivot index `3` and become `[4,5,6,7,0,1,2]`.
Given the array `nums` **after** the possible rotation and an integer `target`, return _the index of_ `target` _if it is in_ `nums`, _or_ `-1` _if it is not in_ `nums`.
You must write an algorithm with `O(log n)` runtime complexity.
> Input: nums = [4,5,6,7,0,1,2], target = 0
> Output: 4
> Input: nums = [4,5,6,7,0,1,2], target = 3
> Output: -1
> Input: nums = [1], …
=> [33] Search in Rotated Sorted Array

dlek-user/[34] Find First and Last Position of Element in Sorted Array
Given an array of integers `nums` sorted in non-decreasing order, find the starting and ending position of a given `target` value.
If `target` is not found in the array, return `[-1, -1]`.
You must write an algorithm with `O(log n)` runtime complexity.
> Input: nums = [5,7,7,8,8,10], target = 8
> Output: [3,4]
> Input: nums = [5,7,7,8,8,10], target = 6
> Output: [-1,-1]
> Input: nums = [], target = 0
> Output: [-1,-1]
```
public int[] searchRange(int[] nums, int target) {
int first = findBound(nums, target, true);
int last = findBound(nums, target, false);
return new int[]{first, last};
}
private int findBound(int[] nums, int target, boolean isFirst) {
int left = 0, right = nums.length - 1;
int bound = -1;
int mid = left + (right - left) / 2;
if …
```
=> [34] Find First and Last Position of Element in Sorted Array

dlek-user/[36] Valid Sudoku
Determine if a `9 x 9` Sudoku board is valid. Only the filled cells need to be validated **according to the following rules**:
1. Each row must contain the digits `1-9` without repetition.
2. Each column must contain the digits `1-9` without repetition.
3. Each of the nine `3 x 3` sub-boxes of the grid must contain the digits `1-9` without repetition.
**Note**:
- A Sudoku board (partially filled) could be valid but is not necessarily solvable.
- Only the filled cells need to be validated according to the mentioned rules.
> Input: board = 
> [["5","3",".",".","7",".",".",".","."]
> ,["6",".",".","1","9","5",".",".","."]
> ,[".","9","8",".",".",".",".","6","."]
> ,["8",".",".",".","6",".",".",".","3"]
> ,["4",".",".","8",".","3",".",".","1"]
> ,["7",".",".",".","2",".",".",".","6"]
> …
=> [36] Valid Sudoku

dlek-user/38. Count and Say
The **count-and-say** sequence is a sequence of digit strings defined by the recursive formula:
- `countAndSay(1) = "1"`
- `countAndSay(n)` is the run-length encoding of `countAndSay(n - 1)`.
[Run-length encoding](http://en.wikipedia.org/wiki/Run-length_encoding) (RLE) is a string compression method that works by replacing consecutive identical characters (repeated 2 or more times) with the concatenation of the character and the number marking the count of the characters (length of the run). For example, to compress the string `"3322251"` we replace `"33"` with `"23"`, replace `"222"` with `"32"`, replace `"5"` with `"15"` and replace `"1"` with `"11"`. Thus the compressed string becomes `"23321511"`.
Given a positive integer `n`, return _the_ `nth` _element of the **count-and-say** …
=> 38. Count and Say

dlek-user/[39] Combination Sum
Given an array of **distinct** integers `candidates` and a target integer `target`, return _a list of all **unique combinations** of_ `candidates` _where the chosen numbers sum to_ `target`. You may return the combinations in **any order**.
The same number may be chosen from `candidates` an `unlimited number of times`. Two combinations are unique if the frequency of at least one of the chosen numbers is different.
The test cases are generated such that the number of unique combinations that sum up to `target` is less than `150` combinations for the given input.
> Input: candidates = [2,3,6,7], target = 7
> Output: [[2,2,3],[7]]
> Explanation:
> 2 and 3 are candidates, and 2 + 2 + 3 = 7. Note that 2 can be used multiple times.
> 7 is a candidate, and 7 = 7.
> These are the only two …
=> [39] Combination Sum

dlek-user/[40] Combination Sum II
Given a collection of candidate numbers (`candidates`) and a target number (`target`), find all unique combinations in `candidates` where the candidate numbers sum to `target`.
Each number in `candidates` may only be used **once** in the combination.
**Note**: The solution set must not contain duplicate combinations.
> Input: candidates = [10,1,2,7,6,1,5], target = 8
> Output: 
> [
> [1,1,6],
> [1,2,5],
> [1,7],
> [2,6]
> ]
> Input: candidates = [2,5,2,1,2], target = 5
> Output: 
> [
> [1,2,2],
> [5]
> ]
```
public List<List<Integer>> combinationSum2(int[] candidates, int target) {
Arrays.sort(candidates);
backtrack(candidates, target, 0, new ArrayList<>(), result);
return result;
}
private void backtrack(int[] candidates, …
```
=> [40] Combination Sum II

dlek-user/[43] Multiply Strings
Given two non-negative integers `num1` and `num2` represented as strings, return the product of `num1` and `num2`, also represented as a string.
**Note**: You must not use any built-in BigInteger library or convert the inputs to integer directly.
> Input: num1 = "2", num2 = "3"
> Output: "6"
> Input: num1 = "123", num2 = "456"
> Output: "56088"
```
public String multiply(String num1, String num2) {
if (num1.equals("0") || num2.equals("0")) return "0";
int n = num1.length();
int m = num2.length();
int[] result = new int[n + m];
for (int i = n - 1; i >= 0; i--) {
int digit1 = num1.charAt(i) - '0';
for (int j = m - 1; j >= 0; j--) {
int digit2 = num2.charAt(j) - '0';
int product = digit1 * digit2;
int pos1 = i + j;
int pos2 = i + j + 1;
int sum = product + result[pos2]; …
```
=> [43] Multiply Strings

dlek-user/[45] Jump Game II
You are given a **0-indexed** array of integers `nums` of length `n`. You are initially positioned at `nums[0]`.
Each element `nums[i]` represents the maximum length of a forward jump from index `i`. In other words, if you are at `nums[i]`, you can jump to any `nums[i + j]` where:
- `0 <= j <= nums[i]` and
- `i + j < n`
Return _the minimum number of jumps to reach_ `nums[n - 1]`. The test cases are generated such that you can reach `nums[n - 1]`.
> Input: nums = [2,3,1,1,4]
> Output: 2
> Explanation: The minimum number of jumps to reach the last index is 2. Jump 1 step from index 0 to 1, then 3 steps to the last index.
> Input: nums = [2,3,0,1,4]
> Output: 2
```
public int jump(int[] nums) {
int jumps = 0;
int currentEnd = 0;
int farthest = 0;
for (int i = 0; i < …
```
=> [45] Jump Game II

dlek-user/[46] Permutations
Given an array `nums` of distinct integers, return all the possible permutations. You can return the answer in **any order**.
> Output: [[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]
> Input: nums = [0,1]
> Output: [[0,1],[1,0]]
> Input: nums = [1]
```
public List<List<Integer>> permute(int[] nums) {
backtrack(nums, new ArrayList<>(), new boolean[nums.length], result);
return result;
}
private void backtrack(int[] nums, List<Integer> current, boolean[] used, List<List<Integer>> result) {
if (current.size() == nums.length) {
result.add(new ArrayList<>(current));
return;
}
if (used[i]) continue;
used[i] = true;
current.add(nums[i]); …
```
=> [46] Permutations

dlek-user/[48] Rotate Image
You are given an `n x n` 2D `matrix` representing an image, rotate the image by **90** degrees (clockwise).
You have to rotate the image [in-place](https://en.wikipedia.org/wiki/In-place_algorithm), which means you have to modify the input 2D matrix directly. **DO NOT** allocate another 2D matrix and do the rotation.
> Input: matrix = [[1,2,3],[4,5,6],[7,8,9]]
> Output: [[7,4,1],[8,5,2],[9,6,3]]
> Input: matrix = [[5,1,9,11],[2,4,8,10],[13,3,6,7],[15,14,12,16]]
> Output: [[15,13,2,5],[14,3,4,1],[12,6,8,9],[16,7,10,11]]
```
public void rotate(int[][] matrix) {
int n = matrix.length;
for (int j = i + 1; j < n; j++) {
int temp = matrix[i][j];
matrix[i][j] = matrix[j][i];
matrix[j][i] = temp;
}
}
int left = 0, right …
```
=> [48] Rotate Image

dlek-user/[49] Group Anagrams
Given an array of strings `strs`, group the anagrams together. You can return the answer in **any order**.
> Input: strs = ["eat","tea","tan","ate","nat","bat"]
> 
> Output: [["bat"],["nat","tan"],["ate","eat","tea"]]
> 
> Explanation:
> 
> There is no string in strs that can be rearranged to form "bat".
> The strings "nat" and "tan" are anagrams as they can be rearranged to form each other.
> The strings "ate", "eat", and "tea" are anagrams as they can be rearranged to form each other.
> Input: strs = [""]
> 
> Output: [[""]]
> Input: strs = ["a"]
> 
> Output: [["a"]]
```
public List<List<String>> groupAnagrams(String[] strs) {
Map<String, List<String>> map = new HashMap<>();
for (String s : strs) {
char[] chars = s.toCharArray();
Arrays.sort(chars);
String key = new …
```
=> [49] Group Anagrams

dlek-user/[50] Pow(x, n)
Implement [pow(x, n)](http://www.cplusplus.com/reference/valarray/pow/), which calculates `x` raised to the power `n` (i.e., `xn`).
> Input: x = 2.00000, n = 10
> Output: 1024.00000
> Input: x = 2.10000, n = 3
> Output: 9.26100
> Input: x = 2.00000, n = -2
> Output: 0.25000
> Explanation: 2-2 = 1/22 = 1/4 = 0.25
```
public double myPow(double x, int n) {
long N = n;
if (N < 0) {
x = 1 / x;
N = -N;
}
return fastPow(x, N);
}
private double fastPow(double x, long n) {
if (n == 0) return 1.0;
double half = fastPow(x, n / 2);
if (n % 2 == 0) {
return half * half;
} else {
return half * half * x;
}
}
}
```
#
```
long N = n;
```
Java에서 int의 범위는 [-2^31, 2^31-1]인데, -n을 하면 오버플로우가 발생할 수 있어서 long으로 바꿉니다.
```
if (N < 0) {
x = 1 / x;
N = -N;
}
```
지수가 음수일 경우에는 밑을 역수로 바꾸고 지수를 양수로 바꿉니다. …
=> [50] Pow(x, n)

dlek-user/[53] Maximum Subarray
Given an integer array `nums`, find the subarray with the largest sum, and return _its sum_.
> Input: nums = [-2,1,-3,4,-1,2,1,-5,4]
> Output: 6
> Explanation: The subarray [4,-1,2,1] has the largest sum 6.
> Input: nums = [1]
> Output: 1
> Explanation: The subarray [1] has the largest sum 1.
> Input: nums = [5,4,-1,7,8]
> Output: 23
> Explanation: The subarray [5,4,-1,7,8] has the largest sum 23.
```
public int maxSubArray(int[] nums) {
int maxSum = nums[0];
int currentSum = nums[0];
for (int i = 1; i < nums.length; i++) {
currentSum = Math.max(nums[i], currentSum + nums[i]);
maxSum = Math.max(maxSum, currentSum);
}
return maxSum;
}
}
```
#
```
int maxSum = nums[0]; 
int currentSum = nums[0];
```
배열의 첫 번째 값을 기준으로 시작합니다.
```
for (int i = 1; i < nums.length; i++) {
```
두 …
=> [53] Maximum Subarray

dlek-user/[54] Spiral Matrix
Given an `m x n` `matrix`, return _all elements of the_ `matrix` _in spiral order_.
> Input: matrix = [[1,2,3],[4,5,6],[7,8,9]]
> Output: [1,2,3,6,9,8,7,4,5]
> Input: matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
> Output: [1,2,3,4,8,12,11,10,9,5,6,7]
```
public List<Integer> spiralOrder(int[][] matrix) {
if (matrix == null || matrix.length == 0) return result;
int top = 0;
int bottom = matrix.length - 1;
int left = 0;
int right = matrix[0].length - 1;
while (top <= bottom && left <= right) {
for (int col = left; col <= right; col++) {
result.add(matrix[top][col]);
}
top++;
for (int row = top; row <= bottom; row++) {
result.add(matrix[row][right]);
}
right--;
if (top <= bottom) {
for (int col = right; col >= left; col--) { …
```
=> [54] Spiral Matrix

dlek-user/[55] Jump Game
You are given an integer array `nums`. You are initially positioned at the array's **first index**, and each element in the array represents your maximum jump length at that position.
Return `true` _if you can reach the last index, or_ `false` _otherwise_.
> Input: nums = [2,3,1,1,4]
> Output: true
> Explanation: Jump 1 step from index 0 to 1, then 3 steps to the last index.
> Input: nums = [3,2,1,0,4]
> Explanation: You will always arrive at index 3 no matter what. Its maximum jump length is 0, which makes it impossible to reach the last index.
```
public boolean canJump(int[] nums) {
int maxReach = 0;
if (i > maxReach) {
return false;
}
maxReach = Math.max(maxReach, i + nums[i]);
}
return true;
}
}
```
#
```
int …
```
=> [55] Jump Game

dlek-user/[56] Merge Intervals
Given an array of intervals where `intervals[i] = [starti, endi]`, merge all overlapping intervals, and return _an array of the non-overlapping intervals that cover all the intervals in the input_.
> Input: intervals = [[1,3],[2,6],[8,10],[15,18]]
> Output: [[1,6],[8,10],[15,18]]
> Explanation: Since intervals [1,3] and [2,6] overlap, merge them into [1,6].
> Input: intervals = [[1,4],[4,5]]
> Output: [[1,5]]
> Explanation: Intervals [1,4] and [4,5] are considered overlapping.
```
public int[][] merge(int[][] intervals) {
if (intervals.length <= 1) {
return intervals;
}
Arrays.sort(intervals, (a, b) -> Integer.compare(a[0], b[0]));
List<int[]> merged = new ArrayList<>();
int[] currentInterval = intervals[0];
merged.add(currentInterval);
for (int[] interval : intervals) { …
```
=> [56] Merge Intervals

dlek-user/[57] Insert Interval
You are given an array of non-overlapping intervals `intervals` where `intervals[i] = [starti, endi]` represent the start and the end of the `ith` interval and `intervals` is sorted in ascending order by `starti`. You are also given an interval `newInterval = [start, end]` that represents the start and end of another interval.
Insert `newInterval` into `intervals` such that `intervals` is still sorted in ascending order by `starti` and `intervals` still does not have any overlapping intervals (merge overlapping intervals if necessary).
Return `intervals` _after the insertion_.
**Note** that you don't need to modify `intervals` in-place. You can make a new array and return it.
> Input: intervals = [[1,3],[6,9]], newInterval = [2,5]
> Output: [[1,5],[6,9]]
> Input: intervals = …
=> [57] Insert Interval

dlek-user/[61] Rotate List
Given the `head` of a linked list, rotate the list to the right by `k` places.
> Input: head = [1,2,3,4,5], k = 2
> Output: [4,5,1,2,3]
> Input: head = [0,1,2], k = 4
> Output: [2,0,1]
```
public ListNode rotateRight(ListNode head, int k) {
if (head == null || head.next == null || k == 0) return head;
ListNode current = head;
int length = 1;
while (current.next != null) {
length++;
}
current.next = head;  // tail -> head
k = k % length;
int stepsToNewHead = length - k;
ListNode newTail = current;
for (int i = 0; i < stepsToNewHead; i++) {
newTail = newTail.next;
}
ListNode newHead = newTail.next;
newTail.next = null;
return newHead;
}
}
```
#
```
ListNode current = head;
int length = 1;
while (current.next != null) { …
```
=> [61] Rotate List

dlek-user/[62] Unique Paths
There is a robot on an `m x n` grid. The robot is initially located at the **top-left corner** (i.e., `grid[0][0]`). The robot tries to move to the **bottom-right corner** (i.e., `grid[m - 1][n - 1]`). The robot can only move either down or right at any point in time.
Given the two integers `m` and `n`, return _the number of possible unique paths that the robot can take to reach the bottom-right corner_.
The test cases are generated so that the answer will be less than or equal to `2 * 109`.
> Input: m = 3, n = 7
> Output: 28
> Input: m = 3, n = 2
> Output: 3
> Explanation: From the top-left corner, there are a total of 3 ways to reach the bottom-right corner:
> 1. Right -> Down -> Down
> 2. Down -> Down -> Right
> 3. Down -> Right -> Down
```
public int uniquePaths(int …
```
=> [62] Unique Paths

dlek-user/[63] Unique Paths II
You are given an `m x n` integer array `grid`. There is a robot initially located at the **top-left corner** (i.e., `grid[0][0]`). The robot tries to move to the **bottom-right corner** (i.e., `grid[m - 1][n - 1]`). The robot can only move either down or right at any point in time.
An obstacle and space are marked as `1` or `0` respectively in `grid`. A path that the robot takes cannot include **any** square that is an obstacle.
Return _the number of possible unique paths that the robot can take to reach the bottom-right corner_.
The testcases are generated so that the answer will be less than or equal to `2 * 109`.
> Input: obstacleGrid = [[0,0,0],[0,1,0],[0,0,0]]
> Output: 2
> Explanation: There is one obstacle in the middle of the 3x3 grid above.
> There are two ways to reach the …
=> [63] Unique Paths II

dlek-user/[71] Simplify Path
ou are given an _absolute_ path for a Unix-style file system, which always begins with a slash `'/'`. Your task is to transform this absolute path into its **simplified canonical path**.
The _rules_ of a Unix-style file system are as follows:
- A single period `'.'` represents the current directory.
- A double period `'..'` represents the previous/parent directory.
- Multiple consecutive slashes such as `'//'` and `'///'` are treated as a single slash `'/'`.
- Any sequence of periods that does **not match** the rules above should be treated as a **valid directory or file name**. For example, `'...'` and `'....'` are valid directory or file names.
The simplified canonical path should follow these rules:
- The path must start with a single slash `'/'`.
- Directories within the path must be …
=> [71] Simplify Path

dlek-user/[72] Edit Distance
Given two strings `word1` and `word2`, return _the minimum number of operations required to convert `word1` to `word2`_.
You have the following three operations permitted on a word:
- Insert a character
- Delete a character
- Replace a character
> Input: word1 = "horse", word2 = "ros"
> Output: 3
> horse -> rorse (replace 'h' with 'r')
> rorse -> rose (remove 'r')
> rose -> ros (remove 'e')
> Input: word1 = "intention", word2 = "execution"
> Output: 5
> intention -> inention (remove 't')
> inention -> enention (replace 'i' with 'e')
> enention -> exention (replace 'n' with 'x')
> exention -> exection (replace 'n' with 'c')
> exection -> execution (insert 'u')
```
public int minDistance(String word1, String word2) {
int m = word1.length(), n …
```
=> [72] Edit Distance

dlek-user/[73] Set Matrix Zeroes
Given an `m x n` integer `matrix` matrix, if an element is `0`, set its entire row and column to `0`'s.
You must do it [in place](https://en.wikipedia.org/wiki/In-place_algorithm).
> Input: matrix = [[1,1,1],[1,0,1],[1,1,1]]
> Output: [[1,0,1],[0,0,0],[1,0,1]]
> Input: matrix = [[0,1,2,0],[3,4,5,2],[1,3,1,5]]
> Output: [[0,0,0,0],[0,4,5,0],[0,3,1,0]]
```
public void setZeroes(int[][] matrix) {
int m = matrix.length;
int n = matrix[0].length;
boolean firstRowHasZero = false;
boolean firstColHasZero = false;
for (int j = 0; j < n; j++) {
if (matrix[0][j] == 0) {
firstRowHasZero = true;
break;
}
}
for (int i = 0; i < m; i++) {
if (matrix[i][0] == 0) {
firstColHasZero = true;
break;
}
}
for (int i = 1; i < m; i++) {
for (int j = 1; j < n; j++) {
if (matrix[i][j] == 0) { …
```
=> [73] Set Matrix Zeroes

dlek-user/[74] Search a 2D Matrix
You are given an `m x n` integer matrix `matrix` with the following two properties:
- Each row is sorted in non-decreasing order.
- The first integer of each row is greater than the last integer of the previous row.
Given an integer `target`, return `true` _if_ `target` _is in_ `matrix` _or_ `false` _otherwise_.
You must write a solution in `O(log(m * n))` time complexity.
> Input: matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]], target = 3
> Output: true
> Input: matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]], target = 13
```
public boolean searchMatrix(int[][] matrix, int target) {
int m = matrix.length;
int n = matrix[0].length;
int left = 0;
int right = m * n - 1;
int mid = left + (right - left) / 2;
int row = mid / n;
int …
```
=> [74] Search a 2D Matrix

dlek-user/[75] Sort Colors
Given an array `nums` with `n` objects colored red, white, or blue, sort them [in-place](https://en.wikipedia.org/wiki/In-place_algorithm) so that objects of the same color are adjacent, with the colors in the order red, white, and blue.
We will use the integers `0`, `1`, and `2` to represent the color red, white, and blue, respectively.
You must solve this problem without using the library's sort function.
> Input: nums = [2,0,2,1,1,0]
> Output: [0,0,1,1,2,2]
> Input: nums = [2,0,1]
> Output: [0,1,2]
```
public void sortColors(int[] nums) {
int low = 0;
int mid = 0;
int high = nums.length - 1;
while (mid <= high) {
if (nums[mid] == 0) {
swap(nums, low, mid);
low++;
mid++;
} else if (nums[mid] == 1) {
mid++;
} else {
swap(nums, mid, high);
high--;
}
}
}
private void …
```
=> [75] Sort Colors

dlek-user/[77] Combinations
Given two integers `n` and `k`, return _all possible combinations of_ `k` _numbers chosen from the range_ `[1, n]`.
You may return the answer in **any order**.
> Input: n = 4, k = 2
> Output: [[1,2],[1,3],[1,4],[2,3],[2,4],[3,4]]
> Explanation: There are 4 choose 2 = 6 total combinations.
> Note that combinations are unordered, i.e., [1,2] and [2,1] are considered to be the same combination.
> Input: n = 1, k = 1
> Explanation: There is 1 choose 1 = 1 total combination.
```
public List<List<Integer>> combine(int n, int k) {
backtrack(result, new ArrayList<>(), n, k, 1);
return result;
}
private void backtrack(List<List<Integer>> result, List<Integer> temp, int n, int k, int start) {
if (temp.size() == k) { …
```
=> [77] Combinations

dlek-user/[78] Subsets
Given an integer array `nums` of **unique** elements, return _all possible subsets (the power set)_.
The solution set **must not** contain duplicate subsets. Return the solution in **any order**.
> Output: [[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]
> Input: nums = [0]
> Output: [[],[0]]
```
public List<List<Integer>> subsets(int[] nums) {
backtrack(result, new ArrayList<>(), nums, 0);
return result;
}
private void backtrack(List<List<Integer>> result, List<Integer> temp, int[] nums, int start) {
result.add(new ArrayList<>(temp));
for (int i = start; i < nums.length; i++) {
temp.add(nums[i]);  
backtrack(result, temp, nums, i + 1); 
temp.remove(temp.size() - 1);
}
}
}
```
#
```
List<List<Integer>> …
```
=> [78] Subsets

dlek-user/[80] Remove Duplicates from Sorted Array II
Given an integer array `nums` sorted in **non-decreasing order**, remove some duplicates [in-place](https://en.wikipedia.org/wiki/In-place_algorithm) such that each unique element appears **at most twice**. The **relative order** of the elements should be kept the **same**.
Since it is impossible to change the length of the array in some languages, you must instead have the result be placed in the **first part** of the array `nums`. More formally, if there are `k` elements after removing the duplicates, then the first `k` elements of `nums` should hold the final result. It does not matter what you leave beyond the first `k` elements.
Return `k` _after placing the final result in the first_ `k` _slots of_ `nums`.
Do **not** allocate extra space for another array. You must do this by …
=> [80] Remove Duplicates from Sorted Array II

dlek-user/[81] Search in Rotated Sorted Array II
There is an integer array `nums` sorted in non-decreasing order (not necessarily with **distinct** values).
Before being passed to your function, `nums` is **rotated** at an unknown pivot index `k` (`0 <= k < nums.length`) such that the resulting array is `[nums[k], nums[k+1], ..., nums[n-1], nums[0], nums[1], ..., nums[k-1]]` (**0-indexed**). For example, `[0,1,2,4,4,4,5,6,6,7]` might be rotated at pivot index `5` and become `[4,5,6,6,7,0,1,2,4,4]`.
Given the array `nums` **after** the rotation and an integer `target`, return `true` _if_ `target` _is in_ `nums`, _or_ `false` _if it is not in_ `nums`.
You must decrease the overall operation steps as much as possible.
> Input: nums = [2,5,6,0,0,1,2], target = 0
> Output: true
> Input: nums = [2,5,6,0,0,1,2], target = 3
``` …
```
=> [81] Search in Rotated Sorted Array II

dlek-user/[82] Remove Duplicates from Sorted List II
Given the `head` of a sorted linked list, _delete all nodes that have duplicate numbers, leaving only distinct numbers from the original list. Return the linked list **sorted** as well_.
> Input: head = [1,2,3,3,4,4,5]
> Output: [1,2,5]
> Input: head = [1,1,1,2,3]
> Output: [2,3]
```
public ListNode deleteDuplicates(ListNode head) {
ListNode dummy = new ListNode(0);
dummy.next = head;
ListNode prev = dummy;
ListNode current = head;
while (current != null) {
if (current.next != null && current.val == current.next.val) {
int duplicateVal = current.val;
while (current != null && current.val == duplicateVal) {
}
prev.next = current;
} else {
prev = current;
}
}
return dummy.next;
}
}
```
#
```
ListNode dummy = new ListNode(0); …
```
=> [82] Remove Duplicates from Sorted List II

dlek-user/[86] Partition List
Given the `head` of a linked list and a value `x`, partition it such that all nodes **less than** `x` come before nodes **greater than or equal** to `x`.
You should **preserve** the original relative order of the nodes in each of the two partitions.
> Input: head = [1,4,3,2,5,2], x = 3
> Output: [1,2,2,4,3,5]
> Input: head = [2,1], x = 2
> Output: [1,2]
```
public ListNode partition(ListNode head, int x) {
ListNode beforeHead = new ListNode(0);
ListNode afterHead = new ListNode(0);
ListNode before = beforeHead;
ListNode after = afterHead;
while (head != null) {
if (head.val < x) {
before.next = head;
before = before.next;
} else {
after.next = head;
after = after.next;
}
head = head.next;
}
after.next = null;
before.next = afterHead.next;
return beforeHead.next;
}
}
```
# …
=> [86] Partition List

dlek-user/[89] Gray Code
An **n-bit gray code sequence** is a sequence of `2n` integers where:
- Every integer is in the **inclusive** range `[0, 2n - 1]`,
- The first integer is `0`,
- An integer appears **no more than once** in the sequence,
- The binary representation of every pair of **adjacent** integers differs by **exactly one bit**, and
- The binary representation of the **first** and **last** integers differs by **exactly one bit**.
Given an integer `n`, return _any valid **n-bit gray code sequence**_.
> Input: n = 2
> Output: [0,1,3,2]
> Explanation:
> The binary representation of [0,1,3,2] is [00,01,11,10].
> - 00 and 01 differ by one bit
> - 01 and 11 differ by one bit
> - 11 and 10 differ by one bit
> - 10 and 00 differ by one bit
> [0,2,3,1] is also a valid gray code sequence, whose binary …
=> [89] Gray Code

dlek-user/[90] Subsets II
Given an integer array `nums` that may contain duplicates, return _all possible subsets (the power set)_.
The solution set **must not** contain duplicate subsets. Return the solution in **any order**.
> Input: nums = [1,2,2]
> Output: [[],[1],[1,2],[1,2,2],[2],[2,2]]
> Input: nums = [0]
> Output: [[],[0]]
```
public List<List<Integer>> subsetsWithDup(int[] nums) {
Arrays.sort(nums); 
backtrack(nums, 0, new ArrayList<>(), result);
return result;
}
private void backtrack(int[] nums, int start, List<Integer> current, List<List<Integer>> result) {
result.add(new ArrayList<>(current));
for (int i = start; i < nums.length; i++) {
if (i > start && nums[i] == nums[i - 1]) continue;
current.add(nums[i]);
backtrack(nums, i + 1, …
```
=> [90] Subsets II

dlek-user/[91] Decode Ways
You have intercepted a secret message encoded as a string of numbers. The message is **decoded** via the following mapping:
`"1" -> 'A'`
`"2" -> 'B'`
`...`
`"25" -> 'Y'`
`"26" -> 'Z'`
However, while decoding the message, you realize that there are many different ways you can decode the message because some codes are contained in other codes (`"2"` and `"5"` vs `"25"`).
For example, `"11106"` can be decoded into:
- `"AAJF"` with the grouping `(1, 1, 10, 6)`
- `"KJF"` with the grouping `(11, 10, 6)`
- The grouping `(1, 11, 06)` is invalid because `"06"` is not a valid code (only `"6"` is valid).
Note: there may be strings that are impossible to decode.
Given a string s containing only digits, return the **number of ways** to **decode** it. If the entire string cannot be decoded in any valid …
=> [91] Decode Ways

dlek-user/[92] Reverse Linked List II
Given the `head` of a singly linked list and two integers `left` and `right` where `left <= right`, reverse the nodes of the list from position `left` to position `right`, and return _the reversed list_.
> Input: head = [1,2,3,4,5], left = 2, right = 4
> Output: [1,4,3,2,5]
> Input: head = [5], left = 1, right = 1
> Output: [5]
```
public ListNode reverseBetween(ListNode head, int left, int right) {
if (head == null || left == right) return head;
ListNode dummy = new ListNode(0);
dummy.next = head;
ListNode prev = dummy;
for (int i = 1; i < left; i++) {
prev = prev.next;
}
ListNode current = prev.next;
ListNode next = null;
for (int i = 0; i < right - left; i++) {
next = current.next;
current.next = next.next;
next.next = prev.next;
prev.next = next;
}
return dummy.next; …
```
=> [92] Reverse Linked List II

dlek-user/[93] Restore IP Addresses
A **valid IP address** consists of exactly four integers separated by single dots. Each integer is between `0` and `255` (**inclusive**) and cannot have leading zeros.
- For example, `"0.1.2.201"` and `"192.168.1.1"` are **valid** IP addresses, but `"0.011.255.245"`, `"192.168.1.312"` and `"192.168@1.1"` are **invalid** IP addresses.
Given a string `s` containing only digits, return _all possible valid IP addresses that can be formed by inserting dots into_ `s`. You are **not** allowed to reorder or remove any digits in `s`. You may return the valid IP addresses in **any** order.
> Input: s = "25525511135"
> Output: ["255.255.11.135","255.255.111.35"]
> Input: s = "0000"
> Output: ["0.0.0.0"]
> Input: s = "101023"
> Output: ["1.0.10.23","1.0.102.3","10.1.0.23","10.10.2.3","101.0.2.3"]
``` …
```
=> [93] Restore IP Addresses

dlek-user/[95] Unique Binary Search Trees II
Given an integer `n`, return _all the structurally unique **BST**'s (binary search trees), which has exactly `n` nodes of unique values from `1` to `n`_. Return the answer in **any order**.
> Input: n = 3
> Output: [[1,null,2,null,3],[1,null,3,2],[2,1,3],[3,1,null,null,2],[3,2,null,1]]
> Input: n = 1
```
public List<TreeNode> generateTrees(int n) {
if (n == 0) return new ArrayList<>();
return buildTrees(1, n);
}
private List<TreeNode> buildTrees(int start, int end) {
List<TreeNode> allTrees = new ArrayList<>();
if (start > end) {
allTrees.add(null);
return allTrees;
}
for (int i = start; i <= end; i++) {
List<TreeNode> leftTrees = buildTrees(start, i - 1);
List<TreeNode> rightTrees = buildTrees(i + 1, end);
for (TreeNode left : leftTrees) {
for (TreeNode …
```
=> [95] Unique Binary Search Trees II

dlek-user/[97] Interleaving String
Given strings `s1`, `s2`, and `s3`, find whether `s3` is formed by an **interleaving** of `s1` and `s2`.
An **interleaving** of two strings `s` and `t` is a configuration where `s` and `t` are divided into `n` and `m` substrings respectively, such that:
- `s = s1 + s2 + ... + sn`
- `t = t1 + t2 + ... + tm`
- `|n - m| <= 1`
- The **interleaving** is `s1 + t1 + s2 + t2 + s3 + t3 + ...` or `t1 + s1 + t2 + s2 + t3 + s3 + ...`
**Note**: `a + b` is the concatenation of strings `a` and `b`.
> Input: s1 = "aabcc", s2 = "dbbca", s3 = "aadbbcbcac"
> Output: true
> Explanation: One way to obtain s3 is:
> Split s1 into s1 = "aa" + "bc" + "c", and s2 into s2 = "dbbc" + "a".
> Interleaving the two splits, we get "aa" + "dbbc" + "bc" + "a" + "c" = "aadbbcbcac".
> Since s3 can be obtained by interleaving …
=> [97] Interleaving String

dlek-user/[99] Recover Binary Search Tree
You are given the `root` of a binary search tree (BST), where the values of **exactly** two nodes of the tree were swapped by mistake. _Recover the tree without changing its structure_.
> Input: root = [1,3,null,null,2]
> Output: [3,1,null,null,2]
> Explanation: 3 cannot be a left child of 1 because 3 > 1. Swapping 1 and 3 makes the BST valid.
> Input: root = [3,1,4,null,null,2]
> Output: [2,1,4,null,null,3]
> Explanation: 2 cannot be in the right subtree of 3 because 2 < 3. Swapping 2 and 3 makes the BST valid.
```
private TreeNode first = null;
private TreeNode second = null;
private TreeNode prev = new TreeNode(Integer.MIN_VALUE);
public void recoverTree(TreeNode root) {
inorder(root);
int temp = first.val;
first.val = second.val;
second.val = temp;
}
private void …
```
=> [99] Recover Binary Search Tree

dlek-user/[102] Binary Tree Level Order Traversal
Given the `root` of a binary tree, return _the level order traversal of its nodes' values_. (i.e., from left to right, level by level).
> Output: [[3],[9,20],[15,7]]
> Output: []
```
public List<List<Integer>> levelOrder(TreeNode root) {
if (root == null) return result;
queue.offer(root); 
int levelSize = queue.size();
List<Integer> level = new ArrayList<>();
for (int i = 0; i < levelSize; i++) {
TreeNode current = queue.poll();
level.add(current.val); 
if (current.left != null) queue.offer(current.left);
if (current.right != null) queue.offer(current.right);
} …
```
=> [102] Binary Tree Level Order Traversal

dlek-user/[103] Binary Tree Zigzag Level Order Traversal
Given the `root` of a binary tree, return _the zigzag level order traversal of its nodes' values_. (i.e., from left to right, then right to left for the next level and alternate between).
> Output: [[3],[20,9],[15,7]]
> Output: []
```
public List<List<Integer>> zigzagLevelOrder(TreeNode root) {
if (root == null) return result;
queue.offer(root);
boolean leftToRight = true;
int size = queue.size();
LinkedList<Integer> level = new LinkedList<>();
for (int i = 0; i < size; i++) {
TreeNode node = queue.poll();
if (leftToRight) {
level.addLast(node.val); 
} else { …
```
=> [103] Binary Tree Zigzag Level Order Traversal

dlek-user/[105] Construct Binary Tree from Preorder and Inorder Traversal
Given two integer arrays `preorder` and `inorder` where `preorder` is the preorder traversal of a binary tree and `inorder` is the inorder traversal of the same tree, construct and return _the binary tree_.
> Input: preorder = [3,9,20,15,7], inorder = [9,3,15,20,7]
> Output: [3,9,20,null,null,15,7]
> Input: preorder = [-1], inorder = [-1]
> Output: [-1]
```
public TreeNode buildTree(int[] preorder, int[] inorder) {
Map<Integer, Integer> inorderIndexMap = new HashMap<>();
for (int i = 0; i < inorder.length; i++) {
inorderIndexMap.put(inorder[i], i);
}
return build(preorder, 0, preorder.length - 1,
inorder, 0, inorder.length - 1,
inorderIndexMap);
}
private TreeNode build(int[] preorder, int preStart, int preEnd,
int[] inorder, int inStart, int inEnd,
Map<Integer, Integer> …
```
=> [105] Construct Binary Tree from Preorder and Inorder Traversal

[106] Construct Binary Tree from Inorder and Postorder Traversal
Given two integer arrays `inorder` and `postorder` where `inorder` is the inorder traversal of a binary tree and `postorder` is the postorder traversal of the same tree, construct and return _the binary tree_.
> Input: inorder = [9,3,15,20,7], postorder = [9,15,7,20,3]
> Output: [3,9,20,null,null,15,7]
> Input: inorder = [-1], postorder = [-1]
> Output: [-1]
```
public TreeNode buildTree(int[] inorder, int[] postorder) {
Map<Integer, Integer> inorderMap = new HashMap<>();
for (int i = 0; i < inorder.length; i++) {
inorderMap.put(inorder[i], i);
}
return build(inorder, 0, inorder.length - 1,
postorder, 0, postorder.length - 1,
inorderMap);
}
private TreeNode build(int[] inorder, int inStart, int inEnd,
int[] postorder, int postStart, int postEnd,
Map<Integer, Integer> …
```
=> [106] Construct Binary Tree from Inorder and Postorder Traversal

dlek-user/[107] Binary Tree Level Order Traversal II
Given the `root` of a binary tree, return _the bottom-up level order traversal of its nodes' values_. (i.e., from left to right, level by level from leaf to root).
> Output: [[15,7],[9,20],[3]]
> Output: []
```
public List<List<Integer>> levelOrderBottom(TreeNode root) {
List<List<Integer>> result = new LinkedList<>();
return result;
}
queue.offer(root);
int levelSize = queue.size();
List<Integer> currentLevel = new ArrayList<>();
for (int i = 0; i < levelSize; i++) {
TreeNode currentNode = queue.poll();
currentLevel.add(currentNode.val);
if (currentNode.left != null) { …
```
=> [107] Binary Tree Level Order Traversal II

dlek-user/[114] Flatten Binary Tree to Linked List
Given the `root` of a binary tree, flatten the tree into a "linked list":
- The "linked list" should use the same `TreeNode` class where the `right` child pointer points to the next node in the list and the `left` child pointer is always `null`.
- The "linked list" should be in the same order as a [pre-order traversal](https://en.wikipedia.org/wiki/Tree_traversal#Pre-order,_NLR) of the binary tree.
> Input: root = [1,2,5,3,4,null,6]
> Output: [1,null,2,null,3,null,4,null,5,null,6]
> Output: []
> Input: root = [0]
> Output: [0]
```
public void flatten(TreeNode root) {
if (root == null) return;
flatten(root.left);
flatten(root.right);
TreeNode leftSubtree = root.left;
TreeNode rightSubtree = root.right;
root.left = null;
root.right = leftSubtree; …
```
=> [114] Flatten Binary Tree to Linked List

dlek-user/[116] Populating Next Right Pointers in Each Node
You are given a **perfect binary tree** where all leaves are on the same level, and every parent has two children. The binary tree has the following definition:
> struct Node {
>   int val;
>   Node *left;
>   Node *right;
>   Node *next;
> }
Populate each next pointer to point to its next right node. If there is no next right node, the next pointer should be set to `NULL`.
Initially, all next pointers are set to `NULL`.
> Input: root = [1,2,3,4,5,6,7]
> Output: [1,#,2,3,#,4,5,6,7,#]
> Explanation: Given the above perfect binary tree (Figure A), your function should populate each next pointer to point to its next right node, just like in Figure B. The serialized output is in level order as connected by the next pointers, with '#' signifying the end of each level.
> …
=> [116] Populating Next Right Pointers in Each Node

dlek-user/[117] Populating Next Right Pointers in Each Node II
Given a binary tree
> struct Node {
>   int val;
>   Node *left;
>   Node *right;
>   Node *next;
> }
Populate each next pointer to point to its next right node. If there is no next right node, the next pointer should be set to `NULL`.
Initially, all next pointers are set to `NULL`.
> Input: root = [1,2,3,4,5,null,7]
> Output: [1,#,2,3,#,4,5,7,#]
> Explanation: Given the above binary tree (Figure A), your function should populate each next pointer to point to its next right node, just like in Figure B. The serialized output is in level order as connected by the next pointers, with '#' signifying the end of each level.
> Output: []
```
public Node connect(Node root) {
if (root == null) return null;
Queue<Node> queue = new LinkedList<>(); …
```
=> [117] Populating Next Right Pointers in Each Node II

dlek-user/[122] Best Time to Buy and Sell Stock II
You are given an integer array `prices` where `prices[i]` is the price of a given stock on the `ith` day.
On each day, you may decide to buy and/or sell the stock. You can only hold **at most one** share of the stock at any time. However, you can buy it then immediately sell it on the **same day**.
Find and return _the **maximum** profit you can achieve_.
> Input: prices = [7,1,5,3,6,4]
> Output: 7
> Explanation: Buy on day 2 (price = 1) and sell on day 3 (price = 5), profit = 5-1 = 4.
> Then buy on day 4 (price = 3) and sell on day 5 (price = 6), profit = 6-3 = 3.
> Total profit is 4 + 3 = 7.
> Input: prices = [1,2,3,4,5]
> Output: 4
> Explanation: Buy on day 1 (price = 1) and sell on day 5 (price = 5), profit = 5-1 = 4.
> Total profit is 4.
> Input: prices = [7,6,4,3,1]
> Output: 0
> …
=> [122] Best Time to Buy and Sell Stock II

dlek-user/[128] Longest Consecutive Sequence
Given an unsorted array of integers `nums`, return _the length of the longest consecutive elements sequence_.
You must write an algorithm that runs in `O(n)` time.
> Input: nums = [100,4,200,1,3,2]
> Output: 4
> Explanation: The longest consecutive elements sequence is [1, 2, 3, 4]. Therefore its length is 4.
> Input: nums = [0,3,7,2,5,8,4,6,0,1]
> Output: 9
> Input: nums = [1,0,1,2]
> Output: 3
```
public int longestConsecutive(int[] nums) {
Set<Integer> set = new HashSet<>();
set.add(num);
}
int longestStreak = 0;
for (int num : set) {
if (!set.contains(num - 1)) {
int currentNum = num;
int currentStreak = 1;
while (set.contains(currentNum + 1)) {
currentNum++;
currentStreak++;
}
longestStreak = Math.max(longestStreak, currentStreak);
}
}
return …
```
=> [128] Longest Consecutive Sequence

dlek-user/[133] Clone Graph
Given a reference of a node in a [connected](https://en.wikipedia.org/wiki/Connectivity_(graph_theory)#Connected_graph) undirected graph.
Return a [deep copy](https://en.wikipedia.org/wiki/Object_copying#Deep_copy) (clone) of the graph.
Each node in the graph contains a value (`int`) and a list (`List[Node]`) of its neighbors.
> class Node {
>     public int val;
>     public List<Node> neighbors;
> }
**Test case format:**
For simplicity, each node's value is the same as the node's index (1-indexed). For example, the first node with `val == 1`, the second node with `val == 2`, and so on. The graph is represented in the test case using an adjacency list.
**An adjacency list** is a collection of unordered **lists** used to represent a finite graph. Each list describes the set of neighbors …
=> [133] Clone Graph

dlek-user/[134] Gas Station
There are `n` gas stations along a circular route, where the amount of gas at the `ith` station is `gas[i]`.
You have a car with an unlimited gas tank and it costs `cost[i]` of gas to travel from the `ith` station to its `next (i + 1)th` station. You begin the journey with an empty tank at one of the gas stations.
Given two integer arrays `gas` and `cost`, return _the starting gas station's index if you can travel around the circuit once in the clockwise direction, otherwise return_ `-1`. If there exists a solution, it is **guaranteed** to be **unique**.
> Input: gas = [1,2,3,4,5], cost = [3,4,5,1,2]
> Output: 3
> Explanation:
> Start at station 3 (index 3) and fill up with 4 unit of gas. Your tank = 0 + 4 = 4
> Travel to station 4. Your tank = 4 - 1 + 5 = 8
> Travel to station 0. Your …
=> [134] Gas Station

dlek-user/[137] Single Number II
Given an integer array `nums` where every element appears **three times** except for one, which appears **exactly once**. _Find the single element and return it_.
You must implement a solution with a linear runtime complexity and use only constant extra space.
> Input: nums = [2,2,3,2]
> Output: 3
> Input: nums = [0,1,0,1,0,1,99]
> Output: 99
```
public int singleNumber(int[] nums) {
int ones = 0, twos = 0;
ones = (ones ^ num) & ~twos;
twos = (twos ^ num) & ~ones;
}
return ones;
}
}
```
#
```
ones = (ones ^ num) & ~twos;
twos = (twos ^ num) & ~ones;
```
'한 번 등장한 비트'와 '두 번 등장한 비트'를 추적하는 변수 선언
```
for (int num : nums)
```
배열의 모든 숫자를 하나씩 탐색
```
ones = (ones ^ num) & ~twos;
twos = (twos ^ num) & ~ones;
```
ones는 num을 XOR한 후 twos에 이미 있는 비트는 제거한다
twos는 …
=> [137] Single Number II

dlek-user/[138] Copy List with Random Pointer
A linked list of length `n` is given such that each node contains an additional random pointer, which could point to any node in the list, or `null`.
Construct a [deep copy](https://en.wikipedia.org/wiki/Object_copying#Deep_copy) of the list. The deep copy should consist of exactly `n` **brand new** nodes, where each new node has its value set to the value of its corresponding original node. Both the `next` and `random` pointer of the new nodes should point to new nodes in the copied list such that the pointers in the original list and copied list represent the same list state. **None of the pointers in the new list should point to nodes in the original list**.
For example, if there are two nodes `X` and `Y` in the original list, where `X.random --> Y`, then for the corresponding two …
=> [138] Copy List with Random Pointer

dlek-user/[143] Reorder List
You are given the head of a singly linked-list. The list can be represented as:
> L0 → L1 → … → Ln - 1 → Ln
_Reorder the list to be on the following form:_
> L0 → Ln → L1 → Ln - 1 → L2 → Ln - 2 → …
You may not modify the values in the list's nodes. Only nodes themselves may be changed.
> Input: head = [1,2,3,4]
> Output: [1,4,2,3]
> Input: head = [1,2,3,4,5]
> Output: [1,5,2,4,3]
```
public void reorderList(ListNode head) {
if (head == null || head.next == null) return;
ListNode slow = head, fast = head;
while (fast != null && fast.next != null) {
slow = slow.next;
fast = fast.next.next;
}
ListNode second = reverse(slow.next);
slow.next = null;
ListNode first = head;
while (second != null) {
ListNode tmp1 = first.next;
ListNode tmp2 = second.next;
first.next = second; …
```
=> [143] Reorder List

dlek-user/[147] Insertion Sort List
Given the `head` of a singly linked list, sort the list using **insertion sort**, and return _the sorted list's head_.
The steps of the **insertion sort** algorithm:
1. Insertion sort iterates, consuming one input element each repetition and growing a sorted output list.
2. At each iteration, insertion sort removes one element from the input data, finds the location it belongs within the sorted list and inserts it there.
3. It repeats until no input elements remain.
The following is a graphical example of the insertion sort algorithm. The partially sorted list (black) initially contains only the first element in the list. One element (red) is removed from the input data and inserted in-place into the sorted list with each iteration.
> Input: head = [4,2,1,3]
> Output: [1,2,3,4]
> Input: …
=> [147] Insertion Sort List

dlek-user/[153] Find Minimum in Rotated Sorted Array
Suppose an array of length `n` sorted in ascending order is **rotated** between `1` and `n` times. For example, the array `nums = [0,1,2,4,5,6,7]` might become:
- `[4,5,6,7,0,1,2]` if it was rotated `4` times.
- `[0,1,2,4,5,6,7]` if it was rotated `7` times.
Notice that rotating an array `[a[0], a[1], a[2], ..., a[n-1]]` 1 time results in the array `[a[n-1], a[0], a[1], a[2], ..., a[n-2]]`.
Given the sorted rotated array `nums` of **unique** elements, return _the minimum element of this array_.
You must write an algorithm that runs in `O(log n) time`.
> Input: nums = [3,4,5,1,2]
> Output: 1
> Explanation: The original array was [1,2,3,4,5] rotated 3 times.
> Input: nums = [4,5,6,7,0,1,2]
> Output: 0
> Explanation: The original array was [0,1,2,4,5,6,7] and it was rotated 4 times.
> Input: …
=> [153] Find Minimum in Rotated Sorted Array

dlek-user/[155] Min Stack
Design a stack that supports push, pop, top, and retrieving the minimum element in constant time.
Implement the `MinStack` class:
- `MinStack()` initializes the stack object.
- `void push(int val)` pushes the element `val` onto the stack.
- `void pop()` removes the element on the top of the stack.
- `int top()` gets the top element of the stack.
- `int getMin()` retrieves the minimum element in the stack.
You must implement a solution with `O(1)` time complexity for each function.
> Input
> ["MinStack","push","push","push","getMin","pop","top","getMin"]
> [[],[-2],[0],[-3],[],[],[],[]]
> 
> Output
> [null,null,null,null,-3,null,0,-2]
> 
> Explanation
> MinStack minStack = new MinStack();
> minStack.push(-2);
> minStack.push(0);
> minStack.push(-3);
> minStack.getMin(); // return -3
> …
=> [155] Min Stack

dlek-user/[187] Repeated DNA Sequences
The **DNA sequence** is composed of a series of nucleotides abbreviated as `'A'`, `'C'`, `'G'`, and `'T'`.
- For example, `"ACGAATTCCG"` is a **DNA sequence**.
When studying **DNA**, it is useful to identify repeated sequences within the DNA.
Given a string `s` that represents a **DNA** **sequence**, return all the **`10`-letter-long** sequences (substrings) that occur more than once in a DNA molecule. You may return the answer in **any order**.
> Input: s = "AAAAACCCCCAAAAACCCCCCAAAAAGGGTTT"
> Output: ["AAAAACCCCC","CCCCCAAAAA"]
> Input: s = "AAAAAAAAAAAAA"
> Output: ["AAAAAAAAAA"]
```
public List<String> findRepeatedDnaSequences(String s) {
Set<String> seen = new HashSet<>();
Set<String> repeated = new HashSet<>();
for (int i = 0; i <= s.length() - 10; i++) {
String sub …
```
=> [187] Repeated DNA Sequences

dlek-user/[189] Rotate Array
Given an integer array `nums`, rotate the array to the right by `k` steps, where `k` is non-negative.
> Input: nums = [1,2,3,4,5,6,7], k = 3
> Output: [5,6,7,1,2,3,4]
> Explanation:
> rotate 1 steps to the right: [7,1,2,3,4,5,6]
> rotate 2 steps to the right: [6,7,1,2,3,4,5]
> rotate 3 steps to the right: [5,6,7,1,2,3,4]
> Input: nums = [-1,-100,3,99], k = 2
> Output: [3,99,-1,-100]
> rotate 1 steps to the right: [99,-1,-100,3]
> rotate 2 steps to the right: [3,99,-1,-100]
```
public void rotate(int[] nums, int k) {
k %= n; 
reverse(nums, 0, n - 1);
reverse(nums, 0, k - 1);
reverse(nums, k, n - 1);
}
private void reverse(int[] nums, int start, int end) {
while (start < end) {
int temp = nums[start];
nums[start] = nums[end];
nums[end] = …
```
=> [189] Rotate Array

dlek-user/[198] House Robber
You are a professional robber planning to rob houses along a street. Each house has a certain amount of money stashed, the only constraint stopping you from robbing each of them is that adjacent houses have security systems connected and **it will automatically contact the police if two adjacent houses were broken into on the same night**.
Given an integer array `nums` representing the amount of money of each house, return _the maximum amount of money you can rob tonight **without alerting the police**_.
> Input: nums = [1,2,3,1]
> Output: 4
> Explanation: Rob house 1 (money = 1) and then rob house 3 (money = 3).
> Total amount you can rob = 1 + 3 = 4.
> Input: nums = [2,7,9,3,1]
> Output: 12
> Explanation: Rob house 1 (money = 2), rob house 3 (money = 9) and rob house 5 (money = 1).
> …
=> [198] House Robber

dlek-user/[199] Binary Tree Right Side View
Given the `root` of a binary tree, imagine yourself standing on the **right side** of it, return _the values of the nodes you can see ordered from top to bottom_.
> Input: root = [1,2,3,null,5,null,4]
> Output: [1,3,4]
> Input: root = [1,2,3,4,null,null,null,5]
> Output: [1,3,4,5]
> Input: root = [1,null,3]
> Output: [1,3]
> Output: []
```
public List<Integer> rightSideView(TreeNode root) {
if (root == null) return result;
queue.offer(root);
int levelSize = queue.size();  
for (int i = 0; i < levelSize; i++) {
TreeNode node = queue.poll();
if (i == levelSize - 1) {
result.add(node.val);
}
if (node.left != null) queue.offer(node.left);
if …
```
=> [199] Binary Tree Right Side View

dlek-user/[208] Implement Trie (Prefix Tree)
A [trie](https://en.wikipedia.org/wiki/Trie) (pronounced as "try") or **prefix tree** is a tree data structure used to efficiently store and retrieve keys in a dataset of strings. There are various applications of this data structure, such as autocomplete and spellchecker.
Implement the Trie class:
- `Trie()` Initializes the trie object.
- `void insert(String word)` Inserts the string `word` into the trie.
- `boolean search(String word)` Returns `true if the string `word` is in the trie (i.e., was inserted before), and `false` otherwise.
- `boolean startsWith(String prefix)` Returns `true` if there is a previously inserted string `word` that has the prefix `prefix`, and `false` otherwise.
> Input
> ["Trie", "insert", "search", "search", "startsWith", "insert", "search"]
> [[], ["apple"], …
=> [208] Implement Trie (Prefix Tree)

dlek-user/[209] Minimum Size Subarray Sum
Given an array of positive integers `nums` and a positive integer `target`, return _the minimal length of a subarray whose sum is greater than or equal to_ `target`. If there is no such subarray, return `0` instead.
> Input: target = 7, nums = [2,3,1,2,4,3]
> Output: 2
> Explanation: The subarray [4,3] has the minimal length under the problem constraint.
> Input: target = 4, nums = [1,4,4]
> Output: 1
> Input: target = 11, nums = [1,1,1,1,1,1,1,1]
> Output: 0
```
public int minSubArrayLen(int target, int[] nums) {
int minLength = Integer.MAX_VALUE;
int left = 0, sum = 0;
for (int right = 0; right < n; right++) {
sum += nums[right];
while (sum >= target) {
minLength = Math.min(minLength, right - left + 1);
sum -= nums[left++];
}
}
return (minLength == …
```
=> [209] Minimum Size Subarray Sum

dlek-user/[216] Combination Sum III
Find all valid combinations of `k` numbers that sum up to `n` such that the following conditions are true:
- Only numbers `1` through `9` are used.
- Each number is used **at most once**.
Return _a list of all possible valid combinations_. The list must not contain the same combination twice, and the combinations may be returned in any order.
> Input: k = 3, n = 7
> Output: [[1,2,4]]
> Explanation:
> 1 + 2 + 4 = 7
> There are no other valid combinations.
> Input: k = 3, n = 9
> Output: [[1,2,6],[1,3,5],[2,3,4]]
> Explanation:
> 1 + 2 + 6 = 9
> 1 + 3 + 5 = 9
> 2 + 3 + 4 = 9
> There are no other valid combinations.
> Input: k = 4, n = 1
> Output: []
> Explanation: There are no valid combinations.
> Using 4 different numbers in the range [1,9], the smallest sum we can get is 1+2+3+4 = 10 and …
=> [216] Combination Sum III

dlek-user/[223] Rectangle Area
Given the coordinates of two **rectilinear** rectangles in a 2D plane, return _the total area covered by the two rectangles_.
The first rectangle is defined by its **bottom-left** corner `(ax1, ay1)` and its **top-right** corner `(ax2, ay2)`.
The second rectangle is defined by its **bottom-left** corner `(bx1, by1)` and its **top-right** corner `(bx2, by2)`.
> Rectangle Area
> Input: ax1 = -3, ay1 = 0, ax2 = 3, ay2 = 4, bx1 = 0, by1 = -1, bx2 = 9, by2 = 2
> Output: 45
> Input: ax1 = -2, ay1 = -2, ax2 = 2, ay2 = 2, bx1 = -2, by1 = -2, bx2 = 2, by2 = 2
> Output: 16
```
public int computeArea(int ax1, int ay1, int ax2, int ay2, int bx1, int by1, int bx2, int by2) {
int areaA = (ax2 - ax1) * (ay2 - ay1);
int areaB = (bx2 - bx1) * (by2 - by1);
int overlapWidth = Math.max(0, …
```
=> [223] Rectangle Area

dlek-user/[227] Basic Calculator II
Given a string `s` which represents an expression, _evaluate this expression and return its value_. 
The integer division should truncate toward zero.
You may assume that the given expression is always valid. All intermediate results will be in the range of `[-231, 231 - 1]`.
**Note**: You are not allowed to use any built-in function which evaluates strings as mathematical expressions, such as `eval()`.
> Input: s = "3+2*2"
> Output: 7
> Input: s = " 3/2 "
> Output: 1
> Input: s = " 3+5 / 2 "
> Output: 5
```
public int calculate(String s) {
Stack<Integer> stack = new Stack<>();
int num = 0;
char sign = '+'; 
char c = s.charAt(i);
if (Character.isDigit(c)) {
num = num * 10 + (c - '0');
}
if ((!Character.isDigit(c) && c != ' ') || i == …
```
=> [227] Basic Calculator II

dlek-user/[229] Majority Element II
Given an integer array of size `n`, find all elements that appear more than `⌊ n/3 ⌋` times.
> Input: nums = [3,2,3]
> Output: [3]
> Input: nums = [1]
> Output: [1]
> Input: nums = [1,2]
> Output: [1,2]
```
public List<Integer> majorityElement(int[] nums) {
int candidate1 = 0, candidate2 = 1; 
int count1 = 0, count2 = 0;
if (num == candidate1) {
count1++;
} else if (num == candidate2) {
count2++;
} else if (count1 == 0) {
candidate1 = num;
count1 = 1;
} else if (count2 == 0) {
candidate2 = num;
count2 = 1;
} else {
count1--;
count2--;
}
}
count1 = 0;
count2 = 0;
if (num == candidate1) count1++;
else if (num == candidate2) count2++;
}
int threshold = nums.length / 3;
if (count1 > …
```
=> [229] Majority Element II

dlek-user/[237] Delete Node in a Linked List
There is a singly-linked list `head` and we want to delete a node `node` in it.
You are given the node to be deleted `node`. You will **not be given access** to the first node of `head`.
All the values of the linked list are **unique**, and it is guaranteed that the given node `node` is not the last node in the linked list.
Delete the given node. Note that by deleting the node, we do not mean removing it from memory. We mean:
- The value of the given node should not exist in the linked list.
- The number of nodes in the linked list should decrease by one.
- All the values before `node` should be in the same order.
- All the values after `node` should be in the same order.
**Custom testing:**
- For the input, you should provide the entire linked list `head` and the node to be given `node`. …
=> [237] Delete Node in a Linked List

dlek-user/[238] Product of Array Except Self
Given an integer array `nums`, return _an array_ `answer` _such that_ `answer[i]` _is equal to the product of all the elements of_ `nums` _except_ `nums[i]`.
The product of any prefix or suffix of `nums` is **guaranteed** to fit in a **32-bit** integer.
You must write an algorithm that runs in `O(n)` time and without using the division operation.
> Output: [24,12,8,6]
> Input: nums = [-1,1,0,-3,3]
> Output: [0,0,9,0,0]
```
public int[] productExceptSelf(int[] nums) {
int[] answer = new int[n];
answer[0] = 1;
for (int i = 1; i < n; i++) {
answer[i] = answer[i - 1] * nums[i - 1];
}
int right = 1;
for (int i = n - 1; i >= 0; i--) {
answer[i] = answer[i] * right;
right *= nums[i];
}
return answer;
}
}
```
#
```
int n = …
```
=> [238] Product of Array Except Self

dlek-user/[240] Search a 2D Matrix II
Write an efficient algorithm that searches for a value `target` in an `m x n` integer matrix `matrix`. This matrix has the following properties:
- Integers in each row are sorted in ascending from left to right.
- Integers in each column are sorted in ascending from top to bottom.
> Input: matrix = [[1,4,7,11,15],[2,5,8,12,19],[3,6,9,16,22],[10,13,14,17,24],[18,21,23,26,30]], target = 5
> Output: true
> Input: matrix = [[1,4,7,11,15],[2,5,8,12,19],[3,6,9,16,22],[10,13,14,17,24],[18,21,23,26,30]], target = 20
```
public boolean searchMatrix(int[][] matrix, int target) {
int m = matrix.length;       
int n = matrix[0].length;    
int row = 0;     
int col = n - 1;     
while (row < m && col >= 0) {
int val = matrix[row][col];
if (val == target) {
return …
```
=> [240] Search a 2D Matrix II

dlek-user/[279] Perfect Squares
Given an integer `n`, return _the least number of perfect square numbers that sum to_ `n`.
A **perfect square** is an integer that is the square of an integer; in other words, it is the product of some integer with itself. For example, `1`, `4`, `9`, and `16` are perfect squares while `3` and `11` are not.
Input: n = 12
Output: 3
Explanation: 12 = 4 + 4 + 4.
Input: n = 13
Output: 2
Explanation: 13 = 4 + 9.
```
public int numSquares(int n) {
Arrays.fill(dp, Integer.MAX_VALUE);
dp[0] = 0;
for (int i = 1; i <= n; i++) {
for (int j = 1; j * j <= i; j++) {
dp[i] = Math.min(dp[i], dp[i - j * j] + 1);
}
}
return dp[n];
}
}
```
#
```
```
크기가 n+1인 정수 배열 dp를 생성합니다.
dp[i]는 정수 i를 완전제곱수들의 합으로 표현할 때 필요한 최소 개수를 저장합니다.
``` …
```
=> [279] Perfect Squares

dlek-user/[304] Range Sum Query 2D - Immutable
Given a 2D matrix `matrix`, handle multiple queries of the following type:
- Calculate the **sum** of the elements of `matrix` inside the rectangle defined by its **upper left corner** `(row1, col1)` and **lower right corner** `(row2, col2)`.
Implement the `NumMatrix` class:
- `NumMatrix(int[][] matrix)` Initializes the object with the integer matrix `matrix`.
- `int sumRegion(int row1, int col1, int row2, int col2)` Returns the sum of the elements of `matrix` inside the rectangle defined by its **upper left corner** `(row1, col1)` and **lower right corner** `(row2, col2)`.
You must design an algorithm where `sumRegion` works on `O(1)` time complexity.
> Input
> ["NumMatrix", "sumRegion", "sumRegion", "sumRegion"]
> [[[[3, 0, 1, 4, 2], [5, 6, 3, 2, 1], [1, 2, 0, 1, 5], [4, 1, 0, 1, 7], …
=> [304] Range Sum Query 2D - Immutable

dlek-user/[309] Best Time to Buy and Sell Stock with Cooldown
You are given an array `prices` where `prices[i]` is the price of a given stock on the `ith` day.
Find the maximum profit you can achieve. You may complete as many transactions as you like (i.e., buy one and sell one share of the stock multiple times) with the following restrictions:
- After you sell your stock, you cannot buy stock on the next day (i.e., cooldown one day).
**Note**: You may not engage in multiple transactions simultaneously (i.e., you must sell the stock before you buy again).
> Input: prices = [1,2,3,0,2]
> Output: 3
> Explanation: transactions = [buy, sell, cooldown, buy, sell]
> Input: prices = [1]
> Output: 0
```
public int maxProfit(int[] prices) {
if (prices == null || prices.length == 0) return 0;
int n = prices.length;
int hold = -prices[0]; …
```
=> [309] Best Time to Buy and Sell Stock with Cooldown

dlek-user/[310] Minimum Height Trees
A tree is an undirected graph in which any two vertices are connected by exactly one path. In other words, any connected graph without simple cycles is a tree.
Given a tree of `n` nodes labelled from `0` to `n - 1`, and an array of `n - 1` `edges` where `edges[i] = [ai, bi]` indicates that there is an undirected edge between the two nodes `ai` and `bi` in the tree, you can choose any node of the tree as the root. When you select a node `x` as the root, the result tree has height `h`. Among all possible rooted trees, those with minimum height (i.e. `min(h)`)  are called **minimum height trees** (MHTs).
Return _a list of all **MHTs**' root labels. You can return the answer in_ **any order**.
The **height** of a rooted tree is the number of edges on the longest downward path between the root …
=> [310] Minimum Height Trees

dlek-user/[313] Super Ugly Number
A **super ugly number** is a positive integer whose prime factors are in the array `primes`.
Given an integer `n` and an array of integers `primes`, return _the_ `nth` _**super ugly number**_.
The `nth` **super ugly number** is **guaranteed** to fit in a **32-bit** signed integer.
> Input: n = 12, primes = [2,7,13,19]
> Output: 32
> Explanation: [1,2,4,7,8,13,14,16,19,26,28,32] is the sequence of the first 12 super ugly numbers given primes = [2,7,13,19].
> Input: n = 1, primes = [2,3,5]
> Output: 1
> Explanation: 1 has no prime factors, therefore all of its prime factors are in the array primes = [2,3,5].
```
public int nthSuperUglyNumber(int n, int[] primes) {
int[] ugly = new int[n];
ugly[0] = 1;
int k = primes.length;
int[] index = new int[k];
long[] nextMultiple = …
```
=> [313] Super Ugly Number

dlek-user/[371] Sum of Two Integers
Given two integers `a` and `b`, return _the sum of the two integers without using the operators_ `+` _and_ `-`.
> Input: a = 1, b = 2
> Output: 3
> Input: a = 2, b = 3
> Output: 5
```
public int getSum(int a, int b) {
return b == 0 ? a : getSum(a ^ b, (a & b) << 1);
}
}
```
#
```
return b == 0 ? a : getSum(a ^ b, (a & b) << 1);
```
종료 조건: b == 0 (carry 없음)
재귀적으로 sum과 carry를 갱신하며 합산.
=> [371] Sum of Two Integers

dlek-user/[373] Find K Pairs with Smallest Sums
You are given two integer arrays `nums1` and `nums2` sorted in **non-decreasing order** and an integer `k`.
Define a pair `(u, v)` which consists of one element from the first array and one element from the second array.
Return _the_ `k` _pairs_ `(u1, v1), (u2, v2), ..., (uk, vk)` _with the smallest sums_.
> Input: nums1 = [1,7,11], nums2 = [2,4,6], k = 3
> Output: [[1,2],[1,4],[1,6]]
> Explanation: The first 3 pairs are returned from the sequence: [1,2],[1,4],[1,6],[7,2],[7,4],[11,2],[7,6],[11,4],[11,6]
> Input: nums1 = [1,1,2], nums2 = [1,2,3], k = 2
> Output: [[1,1],[1,1]]
> Explanation: The first 2 pairs are returned from the sequence: [1,1],[1,1],[1,2],[2,1],[1,2],[2,2],[1,3],[1,3],[2,3]
```
public List<List<Integer>> kSmallestPairs(int[] nums1, int[] nums2, int k) { …
```
=> [373] Find K Pairs with Smallest Sums

dlek-user/[377] Combination Sum IV
Given an array of **distinct** integers `nums` and a target integer `target`, return _the number of possible combinations that add up to_ `target`.
The test cases are generated so that the answer can fit in a **32-bit** integer.
> Input: nums = [1,2,3], target = 4
> Output: 7
> Explanation:
> The possible combination ways are:
> (1, 1, 1, 1)
> (1, 1, 2)
> (1, 2, 1)
> (1, 3)
> (2, 1, 1)
> (2, 2)
> (3, 1)
> Note that different sequences are counted as different combinations.
> Input: nums = [9], target = 3
> Output: 0
```
public int combinationSum4(int[] nums, int target) {
int[] dp = new int[target + 1];
dp[0] = 1; 
for (int i = 1; i <= target; i++) {
if (i - num >= 0) {
dp[i] += dp[i - num];
}
}
}
return dp[target];
}
}
```
#
```
int[] dp = new …
```
=> [377] Combination Sum IV

dlek-user/[388] Longest Absolute File Path
Suppose we have a file system that stores both files and directories. An example of one system is represented in the following picture:
Here, we have `dir` as the only directory in the root. `dir` contains two subdirectories, `subdir1` and `subdir2`. `subdir1` contains a file `file1.ext` and subdirectory `subsubdir1`. `subdir2` contains a subdirectory `subsubdir2`, which contains a `file file2.ext`.
In text form, it looks like this (with ⟶ representing the tab character):
> dir
> ⟶ subdir1
> ⟶ ⟶ file1.ext
> ⟶ ⟶ subsubdir1
> ⟶ subdir2
> ⟶ ⟶ subsubdir2
> ⟶ ⟶ ⟶ file2.ext
If we were to write this representation in code, it will look like this: `"dir\n\tsubdir1\n\t\tfile1.ext\n\t\tsubsubdir1\n\tsubdir2\n\t\tsubsubdir2\n\t\t\tfile2.ext"`. Note that the `'\n'` and `'\t'` are the new-line and tab …
=> [388] Longest Absolute File Path

dlek-user/[398] Random Pick Index
Given an integer array `nums` with possible **duplicates**, randomly output the index of a given `target` number. You can assume that the given target number must exist in the array.
Implement the `Solution` class:
- `Solution(int[] nums)` Initializes the object with the array `nums`.
- `int pick(int target)` Picks a random index `i` from `nums` where `nums[i] == target`. If there are multiple valid i's, then each index should have an equal probability of returning.
> Input
> ["Solution", "pick", "pick", "pick"]
> [[[1, 2, 3, 3, 3]], [3], [1], [3]]
> Output
> [null, 4, 0, 2]
> 
> Explanation
> Solution solution = new Solution([1, 2, 3, 3, 3]);
> solution.pick(3); // It should return either index 2, 3, or 4 randomly. Each index should have equal probability of returning.
> …
=> [398] Random Pick Index

dlek-user/[399] Evaluate Division
You are given an array of variable pairs `equations` and an array of real numbers `values`, where `equations[i] = [Ai, Bi]` and `values[i]` represent the equation `Ai / Bi = values[i]`. Each `Ai` or `Bi` is a string that represents a single variable.
You are also given some `queries`, where `queries[j] = [Cj, Dj]` represents the `jth` query where you must find the answer for `Cj / Dj = ?`.
Return _the answers to all queries_. If a single answer cannot be determined, return `-1.0`.
**Note**: The input is always valid. You may assume that evaluating the queries will not result in division by zero and that there is no contradiction.
**Note**: The variables that do not occur in the list of equations are undefined, so the answer cannot be determined for them.
> Input: equations = …
=> [399] Evaluate Division

dlek-user/[400] Nth Digit
Given an integer `n`, return the `n^th` digit of the infinite integer sequence `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, ...]`.
> Input: n = 3
> Output: 3
> Input: n = 11
> Output: 0
> Explanation: The 11th digit of the sequence 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, ... is a 0, which is part of the number 10.
```
public int findNthDigit(int n) {
long digitLength = 1;     
long count = 9;         
long start = 1;      
while (n > digitLength * count) {
n -= digitLength * count;  
digitLength++;            
count *= 10;           
start *= 10;  
}
long number = start + (n - 1) / digitLength;
String numStr = Long.toString(number);
int index = (int)((n - 1) % digitLength);
return numStr.charAt(index) - '0';
}
}
```
#
```
long digitLength = 1;     
long count = 9;           
long …
```
=> [400] Nth Digit

dlek-user/[402] Remove K Digits
Given string num representing a non-negative integer `num`, and an integer `k`, return _the smallest possible integer after removing_ `k` _digits from_ `num`.
> Input: num = "1432219", k = 3
> Output: "1219"
> Explanation: Remove the three digits 4, 3, and 2 to form the new number 1219 which is the smallest.
> Input: num = "10200", k = 1
> Output: "200"
> Explanation: Remove the leading 1 and the number is 200. Note that the output must not contain leading zeroes.
> Input: num = "10", k = 2
> Output: "0"
> Explanation: Remove all the digits from the number and it is left with nothing which is 0.
```
public String removeKdigits(String num, int k) {
Stack<Character> stack = new Stack<>();
for (char digit : num.toCharArray()) {
while (!stack.isEmpty() && k > 0 && …
```
=> [402] Remove K Digits

dlek-user/[413] Arithmetic Slices
An integer array is called arithmetic if it consists of **at least three elements** and if the difference between any two consecutive elements is the same.
- For example, `[1,3,5,7,9]`, `[7,7,7,7]`, and `[3,-1,-5,-9]` are arithmetic sequences.
Given an integer array `nums`, return _the number of arithmetic **subarrays** of `nums`_.
A **subarray** is a contiguous subsequence of the array.
> Output: 3
> Explanation: We have 3 arithmetic slices in nums: [1, 2, 3], [2, 3, 4] and [1,2,3,4] itself.
> Input: nums = [1]
> Output: 0
```
public int numberOfArithmeticSlices(int[] nums) {
if (n < 3) return 0; 
int count = 0;
int curr = 0; 
for (int i = 2; i < n; i++) {
if (nums[i] - nums[i - 1] == nums[i - 1] - nums[i - 2]) {
curr += 1; …
```
=> [413] Arithmetic Slices

dlek-user/[421] Maximum XOR of Two Numbers in an Array
Given an integer array `nums`, return _the maximum result of_ `nums[i] XOR nums[j]`, where `0 <= i <= j < n`.
> Input: nums = [3,10,5,25,2,8]
> Output: 28
> Explanation: The maximum result is 5 XOR 25 = 28.
> Input: nums = [14,70,53,83,49,91,36,80,92,51,66,70]
> Output: 127
```
static class TrieNode {
TrieNode[] children = new TrieNode[2]; 
}
private void insert(TrieNode root, int num) {
TrieNode node = root;
for (int i = 31; i >= 0; i--) {
int bit = (num >> i) & 1;
if (node.children[bit] == null) {
node.children[bit] = new TrieNode();
}
node = node.children[bit];
}
}
private int findMaxXor(TrieNode root, int num) {
TrieNode node = root;
int maxXor = 0;
for (int i = 31; i >= 0; i--) {
int bit = (num >> i) & 1;
int oppositeBit = bit ^ 1; 
if (node.children[oppositeBit] != …
```
=> [421] Maximum XOR of Two Numbers in an Array

dlek-user/[423] Reconstruct Original Digits from English
Given a string `s` containing an out-of-order English representation of digits `0-9`, return _the digits in **ascending** order_.
> Input: s = "owoztneoer"
> Output: "012"
> Input: s = "fviefuro"
> Output: "45"
```
public String originalDigits(String s) {
int[] count = new int[26];
count[c - 'a']++;
}
int[] numCount = new int[10];
numCount[0] = count['z' - 'a']; 
numCount[2] = count['w' - 'a']; 
numCount[4] = count['u' - 'a'];
numCount[6] = count['x' - 'a']; 
numCount[8] = count['g' - 'a']; 
numCount[3] = count['h' - 'a'] - numCount[8]; 
numCount[5] = count['f' - 'a'] - numCount[4]; 
numCount[7] = count['s' - 'a'] - numCount[6];
numCount[1] = count['o' - 'a'] - numCount[0] - numCount[2] - numCount[4]; 
numCount[9] = count['i' - 'a'] - …
```
=> [423] Reconstruct Original Digits from English

dlek-user/[424] Longest Repeating Character Replacement
You are given a string `s` and an integer `k`. You can choose any character of the string and change it to any other uppercase English character. You can perform this operation at most `k` times.
Return _the length of the longest substring containing the same letter you can get after performing the above operations_.
> Input: s = "ABAB", k = 2
> Output: 4
> Explanation: Replace the two 'A's with two 'B's or vice versa.
> Input: s = "AABABBA", k = 1
> Output: 4
> Explanation: Replace the one 'A' in the middle with 'B' and form "AABBBBA".
> The substring "BBBB" has the longest repeating letters, which is 4.
> There may exists other ways to achieve this answer too.
```
public int characterReplacement(String s, int k) {
int[] count = new int[26]; 
int left = 0;
int maxCount = …
```
=> [424] Longest Repeating Character Replacement

dlek-user/[427] Construct Quad Tree
Given a `n * n` matrix `grid` of `0's` and `1's` only. We want to represent `grid` with a Quad-Tree.
Return _the root of the Quad-Tree representing_ `grid`.
A Quad-Tree is a tree data structure in which each internal node has exactly four children. Besides, each node has two attributes:
- `val`: True if the node represents a grid of 1's or False if the node represents a grid of 0's. Notice that you can assign the `val` to True or False when `isLeaf` is False, and both are accepted in the answer.
- `isLeaf`: True if the node is a leaf node on the tree or False if the node has four children.
> class Node {
>     public boolean val;
>     public boolean isLeaf;
>     public Node topLeft;
>     public Node topRight;
>     public Node bottomLeft;
>     public Node bottomRight;
> }
We can …
=> [427] Construct Quad Tree

dlek-user/[429] N-ary Tree Level Order Traversal
Given an n-ary tree, return _the level order_ traversal of its nodes' values.
_Nary-Tree input serialization is represented in their level order traversal, each group of children is separated by the null value (See examples)._
> Input: root = [1,null,3,2,4,null,5,6]
> Output: [[1],[3,2,4],[5,6]]
> Input: root = [1,null,2,3,4,5,null,null,6,7,null,8,null,9,10,null,null,11,null,12,null,13,null,null,14]
> Output: [[1],[2,3,4,5],[6,7,8,9,10],[11,12,13],[14]]
```
public List<List<Integer>> levelOrder(Node root) {
if (root == null) return result; 
Queue<Node> queue = new LinkedList<>();
queue.add(root);
int size = queue.size();
List<Integer> level = new ArrayList<>();
for (int i = 0; i < size; i++) {
Node …
```
=> [429] N-ary Tree Level Order Traversal

dlek-user/[430] Flatten a Multilevel Doubly Linked List
You are given a doubly linked list, which contains nodes that have a next pointer, a previous pointer, and an additional child pointer. This child pointer may or may not point to a separate doubly linked list, also containing these special nodes. These child lists may have one or more children of their own, and so on, to produce a **multilevel data structure** as shown in the example below.
Given the `head` of the first level of the list, **flatten** the list so that all the nodes appear in a single-level, doubly linked list. Let `curr` be a node with a child list. The nodes in the child list should appear **after** `curr` and **before** `curr.next` in the flattened list.
Return _the_ `head` _of the flattened list. The nodes in the list must have **all** of their child pointers set to_ …
=> [430] Flatten a Multilevel Doubly Linked List
