hyeontaek/DeleteDuplicates.java
Given the head of a sorted linked list, delete all duplicates such that each element appears only
once. Return the linked list sorted as well.
> Input: head = [1,1,2] \
Output: [1,2]
```
public ListNode deleteDuplicates(ListNode head) {
ListNode current = head;
while (current != null && current.next != null) {
if (current.val == current.next.val) {
current.next = current.next.next;
} else {
}
}
return head;
}
```
`ListNode current = head;` 현재 노드를 가리키는 포인터 `current`를 리스트의 첫 번째 노드인 `head`로 초기화합니다.
`while (current != null && current.next != null) {` `curren`t가 `null`이 아니고, `current`의 다음 노드도 `null`이 아닌 동안 반복합니다. 이 조건은 리스트의 끝에 도달하거나, 마지막 노드를 처리할 때 반복을 멈추게 합니다.
`if (current.val == current.next.val) {` 현재 노드의 값과 다음 노드의 값이 같은 경우, 즉 중복이 발견된 경우,
`current.next = …
=> [83] Remove Duplicates From Sorted List

hyeontaek/PathSum.java
Given the root of a binary tree and an integer targetSum, return true if the tree has a root-to-leaf path such that adding up all the values along the path equals targetSum.
A leaf is a node with no children.
>Input: root = [5,4,8,11,null,13,4,7,2,null,null,null,1], targetSum = 22 \
Output: true \
Explanation: The root-to-leaf path with the target sum is shown.
```
public boolean hasPathSum(TreeNode root, int targetSum) {
if(root == null) return false;
if(root.left == null && root.right == null) return targetSum == root.val;
return hasPathSum(root.left, targetSum - root.val) || hasPathSum(root.right, targetSum - root.val);
}
```
`if(root == null) return false;`
현재 노드가 `null`인 경우, 트리가 비어있거나 잎 노드의 자식인 경우이므로, 경로 합이 존재할 수 없으므로 `false`를 반환합니다.
`if(root.left == null && root.right == null) …
=> [112] Path Sum

dlek-user/[112]Path_Sum
Given the `root` of a binary tree and an integer `targetSum`, return `true` if the tree has a root-to-leaf path such that adding up all the values along the path equals `targetSum`.
A leaf is a node with no children.
> Input: root = [5,4,8,11,null,13,4,7,2,null,null,null,1], targetSum = 22
> Output: true
> Explanation: The root-to-leaf path with the target sum is shown.
> Input: root = [1,2,3], targetSum = 5
> Explanation: There two root-to-leaf paths in the tree:
> (1 --> 2): The sum is 3.
> (1 --> 3): The sum is 4.
> There is no root-to-leaf path with sum = 5.
> Input: root = [], targetSum = 0
> Explanation: Since the tree is empty, there are no root-to-leaf paths.
```
public boolean hasPathSum(TreeNode root, int targetSum) {
if (root == …
```
=> [112]Path Sum

dlek-user/[203] Remove Linked List Elements
Given the head of a linked list and an integer `val`, remove all the nodes of the linked list that has `Node.val == val`, and return _the new head_.
> Input: head = [1,2,6,3,4,5,6], val = 6
> Output: [1,2,3,4,5]
> Input: head = [], val = 1
> Output: []
> Input: head = [7,7,7,7], val = 7
> Output: []
```
public ListNode removeElements(ListNode head, int val) {
ListNode dummy = new ListNode(0);
dummy.next = head;
ListNode current = dummy;
while (current.next != null) {
if (current.next.val == val) {
current.next = current.next.next;
} else {
}
}
return dummy.next;
}
}
```
#
```
ListNode dummy = new ListNode(0);
dummy.next = head;
```
더미 노드를 생성하고, 더미 노드의 다음을 현재 리스트의 머리로 설정합니다.
더미 노드는 리스트의 시작 부분을 처리하는 데 도움이 됩니다.
```
ListNode current = dummy;
```
현재 노드를 …
=> [203] Remove Linked List Elements

dlek-user/[303] Range Sum Query-Immutable
Given an integer array `nums`, handle multiple queries of the following type:
1. Calculate the sum of the elements of `nums` between indices `left` and `right` inclusive where `left <= right`.
- Implement the `NumArray` class:
- `NumArray(int[] nums)` Initializes the object with the integer array `nums`.
- `int sumRange(int left, int right)` Returns the sum of the elements of nums between indices `left` and `right` inclusive (i.e. `nums[left] + nums[left + 1] + ... + nums[right]`).
> Input
> ["NumArray", "sumRange", "sumRange", "sumRange"]
> [[[-2, 0, 3, -5, 2, -1]], [0, 2], [2, 5], [0, 5]]
> Output
> [null, 1, -1, -3]
> 
> Explanation
> NumArray numArray = new NumArray([-2, 0, 3, -5, 2, -1]);
> numArray.sumRange(0, 2); // return (-2) + 0 + 3 = 1
> numArray.sumRange(2, 5); // return 3 + …
=> [303] Range Sum Query-Immutable

dlek-user/[463] Island Perimeter
You are given `row x col` `grid` representing a map where `grid[i][j] = 1` represents land and `grid[i][j] = 0` represents water.
Grid cells are connected **horizontally/vertically** (not diagonally). The `grid` is completely surrounded by water, and there is exactly one island (i.e., one or more connected land cells).
The island doesn't have "lakes", meaning the water inside isn't connected to the water around the island. One cell is a square with side length 1. The grid is rectangular, width and height don't exceed 100. Determine the perimeter of the island.
> Input: grid = [[0,1,0,0],[1,1,1,0],[0,1,0,0],[1,1,0,0]]
> Output: 16
> Explanation: The perimeter is the 16 yellow stripes in the image above.
> Input: grid = [[1]]
> Output: 4
> Input: grid = [[1,0]]
> Output: 4
```
class …
```
=> [463] Island Perimeter

dlek-user/[674] Longest Continuous Increasing Subsequence
Given an unsorted array of integers `nums`, return _the length of the longest **continuous increasing subsequence** (i.e. subarray)_. The subsequence must be **strictly** increasing.
A **continuous increasing subsequence** is defined by two indices `l` and `r` (`l < r`) such that it is `[nums[l], nums[l + 1], ..., nums[r - 1], nums[r]]` and for each `l <= i < r`, `nums[i] < nums[i + 1]`.
> Input: nums = [1,3,5,4,7]
> Output: 3
> Explanation: The longest continuous increasing subsequence is [1,3,5] with length 3.
> Even though [1,3,5,7] is an increasing subsequence, it is not continuous as elements 5 and 7 are separated by element
> 4.
> Input: nums = [2,2,2,2,2]
> Output: 1
> Explanation: The longest continuous increasing subsequence is [2] with length 1. Note that it must be strictly
> …
=> [674] Longest Continuous Increasing Subsequence

dlek-user/[696] Count Binary Substrings
Given a binary string `s`, return the number of non-empty substrings that have the same number of `0`'s and `1`'s, and all the `0`'s and all the `1`'s in these substrings are grouped consecutively.
Substrings that occur multiple times are counted the number of times they occur.
> Input: s = "00110011"
> Output: 6
> Explanation: There are 6 substrings that have equal number of consecutive 1's and 0's: "0011", "01", "1100", "10", "0011", and "01".
> Notice that some of these substrings repeat and are counted the number of times they occur.
> Also, "00110011" is not a valid substring because all the 0's (and 1's) are not grouped together.
Input: s = "10101"
Output: 4
Explanation: There are 4 substrings: "10", "01", "10", "01" that have equal number of consecutive 1's and 0's.
```
class …
```
=> [696] Count Binary Substrings

dlek-user/[724] Find Pivot Index
Given an array of integers `nums`, calculate the **pivot index** of this array.
The **pivot index** is the index where the sum of all the numbers **strictly** to the left of the index is equal to the sum of all the numbers **strictly** to the index's right.
If the index is on the left edge of the array, then the left sum is `0` because there are no elements to the left. This also applies to the right edge of the array.
Return the **leftmost pivot index**. If no such index exists, return `-1`.
> Input: nums = [1,7,3,6,5,6]
> Output: 3
> Explanation:
> The pivot index is 3.
> Left sum = nums[0] + nums[1] + nums[2] = 1 + 7 + 3 = 11
> Right sum = nums[4] + nums[5] = 5 + 6 = 11
> Output: -1
> Explanation:
> There is no index that satisfies the conditions in the problem …
=> [724] Find Pivot Index

dlek-user/[762] Prime Number of Set Bits in Binary Representation
Given two integers `left` and `right`, return _the **count** of numbers in the inclusive range_ `[left, right]` _having a **prime number of set bits** in their binary representation_.
Recall that the **number of set bits** an integer has is the number of `1`'s present when written in binary.
- For example, `21` written in binary is `10101`, which has `3` set bits.
> Input: left = 6, right = 10
> Output: 4
> Explanation:
> 6  -> 110 (2 set bits, 2 is prime)
> 7  -> 111 (3 set bits, 3 is prime)
> 8  -> 1000 (1 set bit, 1 is not prime)
> 9  -> 1001 (2 set bits, 2 is prime)
> 10 -> 1010 (2 set bits, 2 is prime)
> 4 numbers have a prime number of set bits.
> Input: left = 10, right = 15
> Output: 5
> Explanation:
> 10 -> 1010 (2 set bits, 2 is prime)
> 11 -> 1011 (3 set bits, 3 is prime)
> 12 …
=> [762] Prime Number of Set Bits in Binary Representation

dlek-user/[830] Positions of Large Groups
In a string `s` of lowercase letters, these letters form consecutive groups of the same character.
For example, a string like `s = "abbxxxxzyy"` has the groups `"a"`, `"bb"`, `"xxxx"`, `"z"`, and `"yy"`.
A group is identified by an interval `[start, end]`, where `start` and `end` denote the start and end indices (inclusive) of the group. In the above example, `"xxxx"` has the interval `[3,6]`.
A group is considered **large** if it has 3 or more characters.
Return _the intervals of every **large** group sorted in **increasing order by start index**._
> Input: s = "abbxxxxzzy"
> Output: [[3,6]]
> Explanation: "xxxx" is the only large group with start index 3 and end index 6.
> Input: s = "abc"
> Output: []
> Explanation: We have groups "a", "b", and "c", none of which are large groups.
> …
=> [830] Positions of Large Groups

dlek-user/[836] Rectangle Overlap
An axis-aligned rectangle is represented as a list `[x1, y1, x2, y2]`, where `(x1, y1)` is the coordinate of its bottom-left corner, and `(x2, y2)` is the coordinate of its top-right corner. Its top and bottom edges are parallel to the X-axis, and its left and right edges are parallel to the Y-axis.
Two rectangles overlap if the area of their intersection is **positive**. To be clear, two rectangles that only touch at the corner or edges do not overlap.
Given two axis-aligned rectangles `rec1` and `rec2`, return `true` if they overlap, otherwise return `false`.
> Input: rec1 = [0,0,2,2], rec2 = [1,1,3,3]
> Output: true
> Input: rec1 = [0,0,1,1], rec2 = [1,0,2,1]
> Input: rec1 = [0,0,1,1], rec2 = [2,2,3,3]
```
public boolean …
```
=> [836] Rectangle Overlap

dlek-user/[1018] Binary Prefix Divisible By 5
You are given a binary array `nums` **(0-indexed).**
We define `xi` as the number whose binary representation is the subarray `nums[0..i]` (from most-significant-bit to least-significant-bit).
- For example, if `nums = [1,0,1]`, then `x0 = 1`, `x1 = 2`, and `x2 = 5`.
Return _an array of booleans_ `answer` _where_ `answer[i]` _is_ `true` _if_ `xi` _is divisible by_ `5`.
> Input: nums = [0,1,1]
> Output: [true,false,false]
> Explanation: The input numbers in binary are 0, 01, 011; which are 0, 1, and 3 in base-10.
> Only the first number is divisible by 5, so answer[0] is true.
> Input: nums = [1,1,1]
> Output: [false,false,false]
```
public List<Boolean> prefixesDivBy5(int[] nums) {
List<Boolean> result = new ArrayList<>();
int current = 0;
for (int i = 0; i < nums.length; …
```
=> [1018] Binary Prefix Divisible By 5

dlek-user/[1108] Defanging an IP Address
Given a valid (IPv4) IP `address`, return a defanged version of that IP address.
A _defanged IP address_ replaces every period `"."` with `"[.]"`.
> Input: address = "1.1.1.1"
> Output: "1[.]1[.]1[.]1"
> Input: address = "255.100.50.0"
> Output: "255[.]100[.]50[.]0"
```
public String defangIPaddr(String address) {
return address.replace(".", "[.]");
}
}
```
#
```
return address.replace(".", "[.]");
```
replace 메서드를 사용하여 IPv4 주소 문자열에 있는 모든 점(.)을 [.]로 대체합니다.
=> [1108] Defanging an IP Address

dlek-user/[1128] Number of Equivalent Domino Pairs
Given a list of `dominoes`, `dominoes[i] = [a, b]` is equivalent to `dominoes[j] = [c, d]` if and only if either (`a == c` and `b == d`), or (`a == d` and `b == c`) - that is, one domino can be rotated to be equal to another domino.
Return _the number of pairs_ `(i, j)` _for which_ `0 <= i < j < dominoes.length`, _and_ `dominoes[i]` _is **equivalent to**_ `dominoes[j]`.
> Input: dominoes = [[1,2],[2,1],[3,4],[5,6]]
> Output: 1
> Input: dominoes = [[1,2],[1,2],[1,1],[1,2],[2,2]]
> Output: 3
```
public int numEquivDominoPairs(int[][] dominoes) {
Map<Integer, Integer> countMap = new HashMap<>();
int pairs = 0;
for (int[] domino : dominoes) {
int key = Math.min(domino[0], domino[1]) * 10 + Math.max(domino[0], domino[1]);
pairs += countMap.getOrDefault(key, 0); …
```
=> [1128] Number of Equivalent Domino Pairs

dlek-user/[1217] Minimum Cost to Move Chips to The Same Position
We have `n` chips, where the position of the `ith` chip is `position[i]`.
We need to move all the chips to **the same position**. In one step, we can change the position of the `ith` chip from `position[i]` to:
- `position[i] + 2` or `position[i] - 2` with `cost = 0`.
- `position[i] + 1` or `position[i] - 1` with `cost = 1`.
Return _the minimum cost_ needed to move all the chips to the same position.
> Input: position = [1,2,3]
> Output: 1
> Explanation: First step: Move the chip at position 3 to position 1 with cost = 0.
> Second step: Move the chip at position 2 to position 1 with cost = 1.
> Total cost is 1.
> Input: position = [2,2,2,3,3]
> Output: 2
> Explanation: We can move the two chips at position  3 to position 2. Each move has cost = 1. The total cost = 2.
> Input: position = …
=> [1217] Minimum Cost to Move Chips to The Same Position

dlek-user/[1313] Decompress Run-Length Encoded List
We are given a list `nums` of integers representing a list compressed with run-length encoding.
Consider each adjacent pair of elements `[freq, val] = [nums[2*i], nums[2*i+1]]` (with `i >= 0`).  For each such pair, there are `freq` elements with value `val` concatenated in a sublist. Concatenate all the sublists from left to right to generate the decompressed list.
Return the decompressed list.
> Output: [2,4,4,4]
> Explanation: The first pair [1,2] means we have freq = 1 and val = 2 so we generate the array [2].
> The second pair [3,4] means we have freq = 3 and val = 4 so we generate [4,4,4].
> At the end the concatenation [2] + [4,4,4] is [2,4,4,4].
> Input: nums = [1,1,2,3]
> Output: [1,3,3]
```
public int[] decompressRLElist(int[] nums) { …
```
=> [1313] Decompress Run-Length Encoded List

dlek-user/[1436] Destination City
You are given the array `paths`, where `paths[i] = [cityAi, cityBi]` means there exists a direct path going from `cityAi` to `cityBi`. _Return the destination city, that is, the city without any path outgoing to another city_.
It is guaranteed that the graph of paths forms a line without any loop, therefore, there will be exactly one destination city.
> Input: paths = [["London","New York"],["New York","Lima"],["Lima","Sao Paulo"]]
> Output: "Sao Paulo" 
> Explanation: Starting at "London" city you will reach "Sao Paulo" city which is the destination city. Your trip consist of: "London" -> "New York" -> "Lima" -> "Sao Paulo".
> Input: paths = [["B","C"],["D","B"],["C","A"]]
> Output: "A"
> Explanation: All possible trips are: 
> "D" -> "B" -> "C" -> "A". 
> "B" -> "C" -> "A". 
> "C" -> …
=> [1436] Destination City

dlek-user/[1539] Kth Missing Positive Number
Given an array `arr` of positive integers sorted in a **strictly increasing order**, and an integer `k`.
Return _the_ `kth` _**positive** integer that is **missing** from this array_.
> Input: arr = [2,3,4,7,11], k = 5
> Output: 9
> Explanation: The missing positive integers are [1,5,6,8,9,10,12,13,...]. The 5th missing positive integer is 9.
> Input: arr = [1,2,3,4], k = 2
> Output: 6
> Explanation: The missing positive integers are [5,6,7,...]. The 2nd missing positive integer is 6.
> 
```
public int findKthPositive(int[] arr, int k) {
int missingCount = 0, current = 1, index = 0;
while (missingCount < k) {
if (index < arr.length && arr[index] == current) {
index++;
} else {
missingCount++;
if (missingCount == k) return current;
}
current++;
}
return -1;
}
}
```
#
``` …
```
=> [1539] Kth Missing Positive Number

dlek-user/[1572] Matrix Diagonal Sum
Given a square matrix `mat`, return the sum of the matrix diagonals.
Only include the sum of all the elements on the primary diagonal and all the elements on the secondary diagonal that are not part of the primary diagonal.
> Input: mat = [[1,2,3],
>               [4,5,6],
>               [7,8,9]]
> Output: 25
> Explanation: Diagonals sum: 1 + 5 + 9 + 3 + 7 = 25
> Notice that element mat[1][1] = 5 is counted only once.
> Input: mat = [[1,1,1,1],
>               [1,1,1,1],
>               [1,1,1,1],
>               [1,1,1,1]]
> Output: 8
> Input: mat = [[5]]
> Output: 5
```
public int diagonalSum(int[][] mat) {
int n = mat.length;
int sum = 0;
sum += mat[i][i];
sum += mat[i][n - 1 - i];
}
if (n % 2 == 1) {
sum -= mat[n / 2][n / 2];
}
return …
```
=> [1572] Matrix Diagonal Sum

dlek-user/[1588] Sum of All Odd Length Subarrays
Given an array of positive integers `arr`, return _the sum of all possible **odd-length subarrays** of_ `arr`.
A **subarray** is a contiguous subsequence of the array.
> Input: arr = [1,4,2,5,3]
> Output: 58
> Explanation: The odd-length subarrays of arr and their sums are:
> [1] = 1
> [4] = 4
> [2] = 2
> [5] = 5
> [3] = 3
> [1,4,2] = 7
> [4,2,5] = 11
> [2,5,3] = 10
> [1,4,2,5,3] = 15
> If we add all these together we get 1 + 4 + 2 + 5 + 3 + 7 + 11 + 10 + 15 = 58
> Input: arr = [1,2]
> Output: 3
> Explanation: There are only 2 subarrays of odd length, [1] and [2]. Their sum is 3.
> Input: arr = [10,11,12]
> Output: 66
```
public int sumOddLengthSubarrays(int[] arr) {
int sum = 0;
int left = i + 1;
int right = n - i;
int …
```
=> [1588] Sum of All Odd Length Subarrays

dlek-user/[96] Unique Binary Search Trees
Given an integer `n`, return _the number of structurally unique **BST**'s (binary search trees) which has exactly `n` nodes of unique values from `1` to `n`_.
> Input: n = 3
> Output: 5
> Input: n = 1
> Output: 1
```
public int numTrees(int n) {
dp[0] = 1;
dp[1] = 1;
for (int nodes = 2; nodes <= n; nodes++) {
for (int root = 1; root <= nodes; root++) {
int left = dp[root - 1]; 
int right = dp[nodes - root];
dp[nodes] += left * right;
}
}
return dp[n];
}
}
```
#
```
```
dp[i]는 i개의 노드로 만들 수 있는 구조적으로 유일한 BST의 개수를 저장하는 배열입니다.
크기를 n+1로 하는 이유는 0개의 노드도 하나의 트리로 간주되기 때문입니다.
```
dp[0] = 1;
dp[1] = 1;
```
dp[0] = 1: 빈 트리(노드가 없는 트리)도 유효한 구조로 인정
dp[1] = 1: 한 개의 노드는 자신이 루트가 되는 하나의 구조만 가능
```
for (int nodes = 2; nodes <= n; nodes++) …
```
=> [96] Unique Binary Search Trees

dlek-user/[139] Word Break
Given a string `s` and a dictionary of strings `wordDict`, return `true` if `s` can be segmented into a space-separated sequence of one or more dictionary words.
**Note** that the same word in the dictionary may be reused multiple times in the segmentation.
> Input: s = "leetcode", wordDict = ["leet","code"]
> Output: true
> Explanation: Return true because "leetcode" can be segmented as "leet code".
> Input: s = "applepenapple", wordDict = ["apple","pen"]
> Output: true
> Explanation: Return true because "applepenapple" can be segmented as "apple pen apple".
> Note that you are allowed to reuse a dictionary word.
> Input: s = "catsandog", wordDict = ["cats","dog","sand","and","cat"]
```
public boolean wordBreak(String s, List<String> wordDict) { …
```
=> [139] Word Break

dlek-user/[215] Kth Largest Element in an Array
Given an integer array `nums` and an integer `k`, return _the_ `kth` _largest element in the array_.
Note that it is the `kth` largest element in the sorted order, not the `kth` distinct element.
Can you solve it without sorting?
> Input: nums = [3,2,1,5,6,4], k = 2
> Output: 5
> Input: nums = [3,2,3,1,2,4,5,5,6], k = 4
> Output: 4
```
public int findKthLargest(int[] nums, int k) {
PriorityQueue<Integer> minHeap = new PriorityQueue<>();
minHeap.offer(num); 
if (minHeap.size() > k) {
minHeap.poll(); 
}
}
return minHeap.peek();
}
}
```
#
```
PriorityQueue<Integer> minHeap = new PriorityQueue<>();
```
Java의 PriorityQueue는 기본적으로 최소 힙(min heap) 구조입니다. 즉, 가장 작은 값이 먼저 나옵니다.
```
for (int num : nums)
```
nums 배열의 모든 숫자를 순회하면서
```
minHeap.offer(num);
```
숫자를 …
=> [215] Kth Largest Element in an Array

dlek-user/[328] Odd Even Linked List
Given the `head` of a singly linked list, group all the nodes with odd indices together followed by the nodes with even indices, and return _the reordered list_.
The **first** node is considered **odd**, and the **second** node is **even**, and so on.
Note that the relative order inside both the even and odd groups should remain as it was in the input.
You must solve the problem in `O(1)` extra space complexity and `O(n)` time complexity.
> Input: head = [1,2,3,4,5]
> Output: [1,3,5,2,4]
> Input: head = [2,1,3,5,6,4,7]
> Output: [2,3,6,7,1,5,4]
```
public ListNode oddEvenList(ListNode head) {
if (head == null || head.next == null) return head; 
ListNode odd = head;           
ListNode even = head.next;      
ListNode evenHead = even;     
while (even != null && even.next …
```
=> [328] Odd Even Linked List

dlek-user/[376] Wiggle Subsequence
**A wiggle sequence** is a sequence where the differences between successive numbers strictly alternate between positive and negative. The first difference (if one exists) may be either positive or negative. A sequence with one element and a sequence with two non-equal elements are trivially wiggle sequences.
- For example, `[1, 7, 4, 9, 2, 5]` is a **wiggle sequence** because the differences `(6, -3, 5, -7, 3)` alternate between positive and negative.
- In contrast, `[1, 4, 7, 2, 5]` and `[1, 7, 4, 5, 5]` are not wiggle sequences. The first is not because its first two differences are positive, and the second is not because its last difference is zero.
A **subsequence** is obtained by deleting some elements (possibly zero) from the original sequence, leaving the remaining elements in …
=> [376] Wiggle Subsequence
